### PR TITLE
fix(es/transforms/typescript): enum and namespace declaration block scoping

### LINKED ISSUE #2265: Variable missing after compiled duplicate named enum objects on different namespace
Hi guys, thanks a lot for these excellent efforts so far.

**Describe the bug**
Variable missing after compiled duplicate named enum objects on different namespace.
Here's a minimal re-production code and compares between tsc and swc.
In this case, it seems a ```var DUPLICATED_ENUM``` missed by swc compiling.

**Input code**
```typescript
export namespace NS_1 {
  export enum DUPLICATED_ENUM {
    A
  }
}

export namespace NS_2 {
  export enum DUPLICATED_ENUM {
    A = 1
  }
}
```
**Config**
```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": false,
      "dynamicImport": false
    }
  },
  "module": {
    "type": "commonjs",
    "strict": false,
    "strictMode": true,
    "lazy": false,
    "noInterop": false
  }
}
```

**Expected behavior**
Same as tsc or insert the declaration of variable correctly.

**Version**
The version of @swc/core: 1.2.87

**Additional context**
swc:
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.NS_2 = exports.NS_1 = void 0;
var NS_1;
exports.NS_1 = NS_1;
(function(NS_1) {
    var DUPLICATED_ENUM;
    (function(DUPLICATED_ENUM) {
        DUPLICATED_ENUM[DUPLICATED_ENUM["A"] = 0] = "A";
    })(DUPLICATED_ENUM || (DUPLICATED_ENUM = {
    }));
    NS_1.DUPLICATED_ENUM = DUPLICATED_ENUM;
})(NS_1 || (exports.NS_1 = NS_1 = {
}));
var NS_2;
exports.NS_2 = NS_2;
(function(NS_2) {
    // missing a "var DUPLICATED_ENUM;" here, then the runtime will throw an "ReferenceError: DUPLICATED_ENUM is not defined"
    (function(DUPLICATED_ENUM) {
        DUPLICATED_ENUM[DUPLICATED_ENUM["A"] = 1] = "A";
    })(DUPLICATED_ENUM || (DUPLICATED_ENUM = {
    }));
})(NS_2 || (exports.NS_2 = NS_2 = {
}));
```

tsc:
```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NS_2 = exports.NS_1 = void 0;
var NS_1;
(function (NS_1) {
    let DUPLICATED_ENUM;
    (function (DUPLICATED_ENUM) {
        DUPLICATED_ENUM[DUPLICATED_ENUM["A"] = 0] = "A";
    })(DUPLICATED_ENUM = NS_1.DUPLICATED_ENUM || (NS_1.DUPLICATED_ENUM = {}));
})(NS_1 = exports.NS_1 || (exports.NS_1 = {}));
var NS_2;
(function (NS_2) {
    let DUPLICATED_ENUM;
    (function (DUPLICATED_ENUM) {
        DUPLICATED_ENUM[DUPLICATED_ENUM["A"] = 1] = "A";
    })(DUPLICATED_ENUM = NS_2.DUPLICATED_ENUM || (NS_2.DUPLICATED_ENUM = {}));
})(NS_2 = exports.NS_2 || (exports.NS_2 = {}));
```

### LINKED ISSUE #2886: Enum and namespace transpiling does not handle block scope correctly
### Describe the bug

I was testing out enum transpiling while looking into why it's adding `1` on the end of identifiers and noticed that it doesn't handle block scope correctly.

### Input code

```ts
{
    enum Asdf {
        test = 1
    }
    function test() {
        enum Asdf {
            test = 1
        }
        enum Asdf {
            other = 1
        } 
    }
}
enum Asdf {
    asdf = 1
}

export {}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true
    },
    "target": "es2021",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.111&code=H4sIAAAAAAAAA6vm5VIAgtS80lwFx%2BKUNIVqiAAIlKQWlyjYKhhCRGohVFppXnJJZn4eWFZDE1k9VkMwDUIyDK%2Bu%2FJKM1CI0bQpwtwARhs5EEBusASgLlK8oyC8qUaiuBQCjgBG25QAAAA%3D%3D&config=H4sIAAAAAAAAA0WOQQ7DIAwE%2F%2BJzDm0OPfCHPgIRJyIiGNmOVIT4ewGlzc3a3Rm5wC4OTIFkWZD7JTmq%2FYABzQnFsU8KE6i0aLVBcIIFHbFVYgGjfGJtteUNtUEo82N%2BNiAQCf6Rw0e%2F5q53dCRGkbuycQu%2FZW2ug5azB2V8MJwvqLfj4ry8r%2BH44QvfqNagygAAAA%3D%3D

### Expected behavior

Should output something close to the following, like TypeScript does:

```ts
{
    let Asdf;
    (function (Asdf) {
        Asdf[Asdf["test"] = 1] = "test";
    })(Asdf || (Asdf = {}));
    function test() {
        let Asdf;
        (function (Asdf) {
            Asdf[Asdf["test"] = 1] = "test";
        })(Asdf || (Asdf = {}));
        (function (Asdf) {
            Asdf[Asdf["other"] = 1] = "other";
        })(Asdf || (Asdf = {}));
    }
}
var Asdf;
(function (Asdf) {
    Asdf[Asdf["asdf"] = 1] = "asdf";
})(Asdf || (Asdf = {}));
export {};
```

### Actual Behaviour

```js
{
    var Asdf1;
    (function(Asdf) {
        Asdf[Asdf["test"] = 1] = "test";
    })(Asdf1 || (Asdf1 = {
    }));
    function test() {
        (function(Asdf) {
            Asdf[Asdf["test"] = 1] = "test";
        })(Asdf1 || (Asdf1 = {
        }));
        (function(Asdf) {
            Asdf[Asdf["other"] = 1] = "other";
        })(Asdf1 || (Asdf1 = {
        }));
    }
}(function(Asdf) {
    Asdf[Asdf["asdf"] = 1] = "asdf";
})(Asdf1 || (Asdf1 = {
}));
export { };
```

### Version

1.2.111

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dsherret**
This is a re-do of #2887. ~~I will update the tests in this one once the other PRs I opened are merged.~~

Closes #2265
Closes #2886

### CODE REVIEW

File: crates/swc/src/config/mod.rs [hunk 1]
```diff
@@ -365,6 +365,11 @@ impl Options {
                 syntax.decorators()
             ),
             import_assertions(),
+            // Do a resolver pass after decorators as it might
+            // emit runtime declarations and do it before
+            // type stripping as we need to know scope information
+            // for emitting enums and namespaces.
+            resolver_with_mark(top_level_mark),
```
Comment (dsherret) [inline crates/swc/src/config/mod.rs:372]: I feel like we should be able to improve the decorators transform to handle having a resolver pass first. Not a big deal though.

File: crates/swc/tests/fixture/issue-2214/output/index.tsx [hunk 2]
```diff
@@ -1,4 +1,4 @@
-import React1 from "react";
+import React from "react";
```
Comment (dsherret) [inline crates/swc/tests/fixture/issue-2214/output/index.tsx:1]: Bug here now fixed.

File: crates/swc/tests/tsc-references/classes/classDeclarations/classHeritageSpecification/classExtendsItselfIndirectly2/input.ts/es2015.1.normal/output.js [hunk 3]
```diff
@@ -16,16 +16,16 @@ var N;
 }));
 var O;
 (function(O) {
-    class C2 extends Q1.E2 {
+    class C2 extends Q.E2 {
```
Comment (dsherret) [inline crates/swc/tests/tsc-references/classes/classDeclarations/classHeritageSpecification/classExtendsItselfIndirectly2/input.ts/es2015.1.normal/output.js:19]: Not a big deal because this is a usage before the declaration, so it would error anyway (maybe even now with a better error message).

File: crates/swc/tests/tsc-references/classes/propertyMemberDeclarations/constructorParameterShadowsOuterScopes/input.ts/es2015.1.normal/output.js [hunk 4]
```diff
@@ -6,15 +6,15 @@ var x = 1;
 class C {
     constructor(x1){
         this.b // error, evaluated in scope of constructor, cannot reference x
-         = x1;
+         = x;
```
Comment (dsherret) [inline crates/swc/tests/tsc-references/classes/propertyMemberDeclarations/constructorParameterShadowsOuterScopes/input.ts/es2015.1.normal/output.js:9]: This seems ok too as it would error. Original code was:

```ts
var x = 1;
class C {
    b = x; // error, evaluated in scope of constructor, cannot reference x
    constructor(x: string) {
        x = 2; // error, x is string
    }    
}
```

File: crates/swc/tests/tsc-references/es6/computedProperties/computedPropertyNames47_ES5/input.ts/es2015.2.minified/output.js [hunk 5]
```diff
@@ -1,4 +1,4 @@
-var E1, E2, E11, E21;
-(E1 = E11 || (E11 = {
-}))[E1.x = 0] = "x", (E2 = E21 || (E21 = {
-}))[E2.x = 0] = "x", E11.x || E21.x;
+var E1, E2, E1, E2;
```
Comment (dsherret) [inline crates/swc/tests/tsc-references/es6/computedProperties/computedPropertyNames47_ES5/input.ts/es2015.2.minified/output.js:1]: I don't understand why it does this, but it's ok because of `var` and won't error at runtime (it's at least better than before because it will assign to `E1` which might be used in the global scope).

Feel like this should be improved to not create the same declaration name twice though.

File: crates/swc/tests/tsc-references/es6/destructuring/destructuringParameterDeclaration1ES5/input.ts/es2015.2.minified/output.js [hunk 6]
```diff
@@ -1,4 +1,4 @@
-var Foo, Foo1;
+var Foo, Foo;
```
Comment (dsherret) [inline crates/swc/tests/tsc-references/es6/destructuring/destructuringParameterDeclaration1ES5/input.ts/es2015.2.minified/output.js:1]: Again, not sure why this is happening, but it seems ok and it's better than before. We should try to eliminate this sometime though.

File: crates/swc_ecma_minifier/src/compress/optimize/if_return.rs [hunk 7]
```diff
@@ -200,6 +200,9 @@ where
                 match s {
                     Stmt::Decl(Decl::Var(v)) => {
                         if v.decls.iter().all(|v| v.init.is_none()) {
+                            if last_idx == 0 {
+                                break;
+                            }
```
Comment (dsherret) [inline crates/swc_ecma_minifier/src/compress/optimize/if_return.rs:205]: I'm not exactly sure if this is the correct fix, but it stops a panic and the output seems ok so 🤷‍♂️

File: crates/swc_ecma_transforms_base/src/resolver/mod.rs [hunk 8]
```diff
@@ -400,31 +398,22 @@ impl<'a> VisitMut for Resolver<'a> {
...
     typed!(visit_mut_ts_index_signature, TsIndexSignature);
     typed!(visit_mut_ts_interface_body, TsInterfaceBody);
-    typed!(visit_mut_ts_module_ref, TsModuleRef);
     typed!(visit_mut_ts_parenthesized_type, TsParenthesizedType);
     typed!(visit_mut_ts_type_lit, TsTypeLit);
     typed!(visit_mut_ts_type_element, TsTypeElement);
-    typed!(visit_mut_ts_module_block, TsModuleBlock);
-    typed!(visit_mut_ts_namespace_body, TsNamespaceBody);
     typed!(visit_mut_ts_optional_type, TsOptionalType);
-    typed!(visit_mut_ts_param_prop, TsParamProp);
```
Comment (dsherret) [inline crates/swc_ecma_transforms_base/src/resolver/mod.rs:415]: Removed all these because they're more like expressions that end up in the output instead of types.

File: crates/swc_ecma_minifier/src/compress/optimize/if_return.rs (hunk 7 above)
Comment (kdy1) [reply crates/swc_ecma_minifier/src/compress/optimize/if_return.rs:205]: Yeah, it's correct fix, thanks!

**Review by kdy1 — APPROVED** [review]
Thanks!
