### PR TITLE
fix(es/minifier): Try inline value ignored assign

### LINKED ISSUE #10041: `es/minifier`: nested function inlining creates unneeded variables
### Describe the feature

See playground example:

[Playground](https://play.swc.rs/?version=1.10.16&code=H4sIAAAAAAAAA2VQMQ7CMAzcecWJKRFRVdYWBsTOwogY0pBAJEil1C1C0L%2BTNilCsORin332mZnWKbK1A%2BN4zoBPrB35R0oCnfRoyLeKsE4pQBY4HEUKqgL5%2BO3LERpNO3nTLHYJzDdXq%2FScD2z%2FPei3MOA09e4t6T15686JzqRIe2RVLP3T%2B26qWmO0F6iNCWME1KRsag82mLLBTy7QBVDZVbszXcqQXKErR85igSVeyPnHdhQ9RM1A24E%2BjgLqIv22PukNMcvjHfq0X7pnOet5eN8DJ2L1eAEAAA%3D%3D&config=H4sIAAAAAAAAA52VwXKjMAyG732KDOce2sPu7PQB9rbP4HGwIM4ai7FkGqaTd68w0LKJyGEvmaBPQui3JH88HQ7Vmerq7fAhf%2BWht4kgfT2LhcbI9iKWCurOUp18z9XzSs80IU4ZiuU6g4ptaoFLEP1YvKuASCC2xgaCxdb56Jtxm6%2FGrk9AtLGJVd6XO4hMS7bnLUr4rtiPiAFsfECMJeMjQwtJ8aoxBNsTmMHquBOxPKGWYYKZwZk%2BYa%2Fy6Dx7jCLFPXVgnanRgYJ8gpr9AFqY5JKwSFLdvzJ%2FYwfH3LblhG%2BiYbAhW1ZywqUciHztPTuhJzZN1kSY2Y4CM9Sl9Y1JwDkp%2Bc7o407UXwApP1iiaLuiz60CxaORVtqHD0N9bKRdeVS49LZWZYRWJDXeN4qukzKQ2GtnmcDlGiZh632q60DegYGmkT7R6Lvn%2BqSl5LEHbBQgh2u175%2FtZm%2F%2BFjyNwj79LQWy2lmLQ2f5tAtp7I6oTdAaDHxCt8%2FlBBh3aZLFcOl3cY4OpB%2FAaR6ZNPs0nGwYTSjL8a4fZCTkhaYNeFQXQy%2FNXY7u9WUxXr82cWdjW%2BZ%2BszUZ%2BwADhP8flodUPniY2nsd8VsnD78Uq4gne%2FP1ZUVrJU%2Frb6mp6tDlTT2lPecL5Wf17bReH2t5lac%2Fa2C5la6fjTfCXuQGAAA%3D)

`"alice"` is assigned to a variable that is only used once. It should be inlined.

### Babel plugin or link to the feature description

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

Well this's kind of awkward

**Related issue:**

 - Closes https://github.com/swc-project/swc/issues/10041

### CODE REVIEW

File: crates/swc_ecma_minifier/src/compress/optimize/mod.rs [hunk 1]
```diff
@@ -990,25 +1012,6 @@ impl Optimizer<'_> {
                 return Some(e.take());
             }
 
-            Expr::Assign(AssignExpr {
-                op: op!("="),
```
Comment (Austaras) [inline crates/swc_ecma_minifier/src/compress/optimize/mod.rs:994]: This never get called because it's shadowed by previous branch.

File: crates/swc_ecma_minifier/tests/fixture/next/syncfusion/933-e9f9a6bf671b96fc/output.js [hunk 2]
```diff
@@ -6993,11 +6993,9 @@
      * @param {MouseEventArgs | TouchEventArgs} evt ?
      * @returns {void} ?
      */ Touch.prototype.tapHoldEvent = function(evt) {
-                    var eTapArgs;
-                    this.tapCount = 0, this.touchAction = !0, EventHandler.remove(this.element, Browser.touchMoveEvent, this.moveEvent), EventHandler.remove(this.element, Browser.touchEndEvent, this.endEvent), // eslint-disable-next-line
-                    eTapArgs = {
+                    this.tapCount = 0, this.touchAction = !0, EventHandler.remove(this.element, Browser.touchMoveEvent, this.moveEvent), EventHandler.remove(this.element, Browser.touchEndEvent, this.endEvent), this.trigger('tapHold', {
                         originalEvent: evt
-                    }, this.trigger('tapHold', eTapArgs), EventHandler.remove(this.element, Browser.touchCancelEvent, this.cancelEvent);
```
Comment (kdy1) [inline crates/swc_ecma_minifier/tests/fixture/next/syncfusion/933-e9f9a6bf671b96fc/output.js:7000]: Is this correct?

Comment (kdy1) [reply crates/swc_ecma_minifier/tests/fixture/next/syncfusion/933-e9f9a6bf671b96fc/output.js:7000]: Nevermind, it was just inlined.

**Review by kdy1 — APPROVED** [review]
