### PR TITLE
fix(@swc/types): Remove `nativeClassProperties`

### LINKED ISSUE #10589: `nativeClassProperties` should be removed from `@swc/types`
### Describe the bug

1. It is an internal config, derived from other config parameters.
2. It is only passed when directly using the TypeScript pass, for example, in @swc/wasm-typescript.

### Input code

```typescript

```

### Config

```json

```

### Link to the code that reproduces this issue

https://play.swc.rs/

### SWC Info output

_No response_

### Expected behavior

N/A

### Actual behavior

_No response_

### Version

N/A

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by CodeMan62**
closes #10589

### CODE REVIEW

**Comment by kdy1** [comment]
Is this what you intended? I'm not sure if `typescript-wasm` would be fine with this change

File: packages/types/index.ts [hunk 1]
```diff
@@ -879,10 +879,6 @@ export interface TransformConfig {
      */
     verbatimModuleSyntax?: boolean;
 
-    /**
-     * Native class properties support
-     */
-    nativeClassProperties?: boolean;
```
Comment (magic-akari) [inline packages/types/index.ts:885]: This is the only change expected; any/all others should be reverted.

**Review by magic-akari — CHANGES_REQUESTED** [review]

File: packages/types/index.ts (hunk 1 above)
Comment (CodeMan62) [reply packages/types/index.ts:885]: Done

**Comment by CodeMan62** [comment]
> Is this what you intended? I'm not sure if `typescript-wasm` would be fine with this change

Sorry i made a mistake i was not intended to remove the rs file code

**Comment by CodeMan62** [comment]
I think now we can merge it

**Comment by kdy1** [comment]
I'll publish this PR tomorrow
