### PR TITLE
fix(es/parser): Use a hard error for missing r-paren in an if stmt

### LINKED ISSUE #7104: No diagnostic for missing paren in if statement
### Describe the bug

No diagnostic given for missing paren in if statement header.

### Input code

```typescript
const foo = <T extends {}>() => {
    if (bar() {
        console.log(1);
    }
};
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2022",
    "transform": {
      "useDefineForClassFields": true,
      "react": {
        "importSource": "https://esm.sh/preact",
        "runtime": "automatic"
      }
    },
    "loose": false
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.41&code=H4sIAAAAAAAAA0vOzysuUUjLz1ewVbAJUUitKEnNSylWqK6109BUsLVTqOblUgCCzDQFjaTEIqAYVAAEkoF683NS9XLy0zUMNa0hErW8XLXWAJRuJZFWAAAA&config=H4sIAAAAAAAAA1WQvW7DMAyE9z6FoTmoCw8ZsrbIlilPQCh0w0J%2FICkgRuB3jyTHcbqJ3%2FF04N0%2Fus78iTWH7l6eZUjAgvyaC5EpKNwKMTolFMuU1OxWVaVKyhkbmRfBKPAvajWhDF%2FDYFbOEGSM7N8TsuAPjhTwGPnbgciR0F3k%2Be8rihGsvvkKIp8i6zlmtljDrqpJDn2P4j%2Fl2qfFstsMnIOSb7uQNXpQsuYpz%2F8ucDFK3RvBSb2tcePjJTvc6qqVLFfuzbZEgcZp9TZEclqdrav5AeQIxLB6AQAA

### Expected behavior

Typescript gives a `')' expected` error.

### Actual behavior

```ts
const foo = ()=>{
    if (bar()) <invalid>;
    {
        console.log(1);
    }
};
```

### Version

1.3.41

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by chenyukang**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
Fixes #7104

### CODE REVIEW

File: crates/swc_ecma_transforms_typescript/tests/fixture/issue-7104/case1/input.ts [hunk 1]
```diff
@@ -0,0 +1,5 @@
+const foo = <T extends {}>() => {
```
Comment (chenyukang) [inline crates/swc_ecma_transforms_typescript/tests/fixture/issue-7104/case1/input.ts:1]: Any better place for this test case?

File: crates/swc_ecma_transforms_typescript/tests/fixture/issue-7104/case1/output.stderr [hunk 2]
```diff
@@ -0,0 +1,14 @@
+
+  x An arrow function is not allowed here
+   ,-[input.js:1:1]
+ 1 | const foo = <T extends {}>() => {
```
Comment (chenyukang) [inline crates/swc_ecma_transforms_typescript/tests/fixture/issue-7104/case1/output.stderr:4]: I didn't understand why this error come out,
I expect we get the same error message as `case2`.

File: crates/swc_ecma_transforms_typescript/tests/fixture/issue-7104/case1/input.ts (hunk 1 above)
Comment (kdy1) [reply crates/swc_ecma_transforms_typescript/tests/fixture/issue-7104/case1/input.ts:1]: Please move this to https://github.com/swc-project/swc/tree/bb80c659b3619c4dd98f34efdfc1094b8d46d114/crates/swc_ecma_parser/tests/typescript

**Review by kdy1 — CHANGES_REQUESTED** [review]
---

swc-bump: 
 - swc_ecma_parser

**Comment by chenyukang** [comment]
> Thank you!
> 
> swc-bump:
> 
> * swc_ecma_parser

I moved it to `crates/swc_ecma_parser/tests/typescript-errors`.

**Review by kdy1 — APPROVED** [review]
Thanks!

---

swc-bump:
 - swc_ecma_parser
