### PR TITLE
fix(es/preset-env): Consider `browserslist` config if `env.target` is not configured

### LINKED ISSUE #3365: Browserslist not being applied from .browserslistrc or package.json
### Describe the bug

Documentation at https://swc.rs/docs/configuration/supported-browsers#browserslist suggests that if `targets` property is omitted in `.swcrc`, the browserslist should be read from `.browserslistrc` or package.json `browserslist` key.

This does not seem to be the case, only way to seemingly enable different targets is to specify the "targets" key in ".swcrc".

Example file at `test.ts`:

```
const myTest = 'foobar'

const someFunc = (test: string) => {
  console.log(test)
}

const myBar = someFunc(myTest);
```

and `.browserslistrc`:

```
chrome 95
```

### Input code

```typescript
yarn run swc ./test.ts -o ./test.js
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    }
  },
  "env": {
    "debug": true,
  }
}
```

### Playground link

_No response_

### Expected behavior

Browser targets from `.browserslist` file applied. Debug output should match the one when `"targets"` is specified in `.swcrc`.

Debug output with `"targets": "chrome 95"` in `.swcrc`:

```
Targets: BrowserData { chrome: Some(Version { major: 95, minor: 0, patch: 0 }), and_chr: None, and_ff: None, op_mob: None, ie: None, edge: None, firefox: None, safari: None, node: None, ios: None, samsung: None, opera: None, android: None, electron: None, phantom: None, opera_mobile: None, rhino: None }
```

### Actual behavior

Targets from browserslist not being applied. A defaults (?) applied instead as per debug output:

```
Targets: BrowserData { chrome: Some(Version { major: 94, minor: 0, patch: 0 }), and_chr: None, and_ff: None, op_mob: None, ie: Some(Version { major: 11, minor: 0, patch: 0 }), edge: Some(Version { major: 95, minor: 0, patch: 0 }), firefox: Some(Version { major: 78, minor: 0, patch: 0 }), safari: Some(Version { major: 13, minor: 1, patch: 0 }), node: None, ios: Some(Version { major: 12, minor: 2, patch: 0 }), samsung: Some(Version { major: 14, minor: 0, patch: 0 }), opera: Some(Version { major: 80, minor: 0, patch: 0 }), android: Some(Version { major: 95, minor: 0, patch: 0 }), electron: None, phantom: None, opera_mobile: None, rhino: None }
```

### Version

@swc/cli: 0.1.55 @swc/core: 1.2.133

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by egfx-notifications**
**Description:**

The `env.path` option in `.swcrc` was originally implemented for `browserslist`, but implementation was (unintentionally?) removed during the migration to `browserslist-rs` (#2845).
Searching the current directory for browserslist configuration was also dropped in the process.

This PR reimplements searching for browserslist configuration using the lookup functionality provided by `browserslist-rs`

**BREAKING CHANGE:**

This may be considered a breaking change since the previous (broken) behavior for unconfigured `env.targets` was to return a `BrowserData` struct with all `Option`s set to `None`. Now the result of a browserslist `defaults` query is returned instead. This probably was the original behavior with `browserslist`, though.
*Update:* Thinking about it again, `targets_to_versions()` is part of `preset_env_base`s public API so we should probably consider this a breaking change anyway.

**Things to consider:**
- only works for non wasm targets as `browserslist-rs` does not provide configuration loading for wasm32 targets (which is probably to be expected that we won't check environment variables or search a filesystem in that case)
- `feat(preset-env): Let browserslist-rs handle default config path` changes the default for an unconfigured `env.path` from an empty string for wasm targets / current dir for other targets to a `None` value. `browserslist-rs` already looks up the current dir if `path` is `None` and it felt better to let it handle this case itself
  The commit which migrated from `browserslist` to `browserslist-rs` mentioned fixing the `default_path`, but does not mention what was broken and I also did not find any other usage of the `path` property. If the previous implementation was intentional, just ignore that last commit in the PR, the first two sufficiently address the bug.

**Related issue:**
Fixes  #3365
Implements #3085

### CODE REVIEW

**Comment by egfx-notifications** [comment]
It seems some of the tests fail due to them expecting a specific prerecorded results, but this result has now changed due to the previous default without a target being `BrowserData` with only `None` values and now it is `BrowserData` according to browserslist-rs `defaults` query, so some stuff that browser now understand natively is not transpiled.

Seems forcing a browserslist query when target is none is not the best approach. I won't try any fixes before hearing your feedback on how to handle this. Should we make the `env.path` option mandatory if a browserslist config lookup is desired?

File: crates/preset_env_base/src/query.rs [hunk 1]
```diff
@@ -96,8 +96,31 @@ impl Query {
...
+                .to_owned();
+            if let Some(path) = path {
+                browserslist_opts.path(
+                    path.clone()
+                        .into_os_string()
+                        .to_str()
+                        .unwrap_or_else(|| panic!("Invalid path \"{:?}\"", path)),
+                );
+            }
+            let distribs = browserslist::execute(&browserslist_opts)
```
Comment (kdy1) [inline crates/preset_env_base/src/query.rs:115]: Does this work with configs that execute javascript? cc @g-plane

Comment (g-plane) [reply crates/preset_env_base/src/query.rs:115]: No, it doesn't execute any code.

**Review by kdy1 — COMMENTED** [review]
Can you rebase?

**Comment by jodaka** [comment]
Nice to see some action here! Thanks @egfx-notifications

**Comment by egfx-notifications** [comment]
I think I addressed all of the changes between my original commits and now. Unfortunately I can't run `cargo test` locally right now as my GLIBC version is too old. Let's see what CI says. I may set up a newer Ubuntu VM tomorrow if necessary.

**Comment by kdy1** [comment]
No worries, I‘ll update the tests if needed

File: .changeset/tidy-pots-report.md [hunk 2]
```diff
@@ -0,0 +1,5 @@
+---
+preset_env_base: major
```
Comment (kdy1) [inline .changeset/tidy-pots-report.md:2]: As this is a breaking change of swc_core, I'll merge it later.

File: crates/preset_env_base/src/query.rs [hunk 3]
```diff
@@ -96,8 +96,35 @@ impl Query {
...
+                mobile_to_desktop: true,
+                ignore_unknown_versions: true,
+                ..Default::default()
+            };
+            if let Some(path) = path {
+                browserslist_opts.path = path
+                    .clone()
+                    .into_os_string()
+                    .into_string()
+                    .unwrap_or_else(|_| panic!("Invalid path \"{:?}\"", path))
```
Comment (kdy1) [inline crates/preset_env_base/src/query.rs:116]: I think we should not `panic!()` here. Can you return an instance of `anyhow::Error` instead?

File: crates/preset_env_base/src/query.rs [hunk 4]
```diff
@@ -96,8 +96,35 @@ impl Query {
...
+                    .into();
+            }
+            let distribs = browserslist::execute(&browserslist_opts)
+                .with_context(|| "failed to resolve browserslist query from browserslist config")?;
+
+            let versions =
+                BrowserData::parse_versions(distribs).expect("failed to parse browser version");
```
Comment (kdy1) [inline crates/preset_env_base/src/query.rs:123]: Same here. We don't have to panic.

**Review by kdy1 — CHANGES_REQUESTED** [review]

**Review by kdy1 — DISMISSED** [review]
Thank you, and sorry for a (very) late review!

**Review by kdy1 — COMMENTED** [review]
I missed it while reviewing, but while trying to update tests to merge this PR, I found that this PR makes the `swc` crate ignore `jsc.target`.
Could you fix it?

You can run `UPDATE=1 cargo test --test projects --test tsc --test error_msg` from `./crates/swc` to update test snapshots.

**Comment by egfx-notifications** [comment]
> I missed it while reviewing, but while trying to update tests to merge this PR, I found that this PR makes the `swc` crate ignore `jsc.target`. Could you fix it?

So, I looked into this and think I need a little more context. The only test failures I could find in the fixture tests were tests which explicitly **didn't** specify `jsc.target`. Those test cases have neither `env.target` nor `jsc.target` defined and as I mentioned the default if specifying no target is now the result of a browserslist `defaults` query, thus making this PR a breaking change. So those are test failures that were expected to happen until the fixtures are updated.
Note that the shopify tests 003-005 also fall into this "defaults" change since their `.swcrc` is wrong, they specify 
```json
{
    "jsc": {
        "parser": {
            "syntax": "ecmascript",
            "jsx": true
        }
    },
    "module": {
        "type": "commonjs"
    },
    "env": {
        "chrome": "50"
    }
}
```
when it should have been
```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    }
  },
  "module": {
    "type": "commonjs"
  },
  "env": {
    "targets": {
      "chrome": "50"
    }
  }
}
```
So those fixtures weren't using that targeted chrome version from the start.

As far as I can tell `jsc.target` should still work as intended if specified.

**Comment by kdy1** [comment]
Oh, I think then it's fine and we should specify `jsc.target: es5` for those tests I think

**Comment by egfx-notifications** [comment]
So, since `jsc.target` and `env` can't be used together and I think the `env` configurations in those test cases may be relevant for the case, I tried another route to solve this. I put `.browserslistrc` files without any content into the crate directories of the failing tests. This way it is picked up by autodiscovery if the test doesn't specify `jsc.target` or `env.targets`, but an empty query results in applying all possible transformations and thus emulates the previous default. This also means we don't have to regenerate all fixtures everytime `browserslist-rs` updates the result of the `defaults` query.  
Let me know if this is a suitable solution.

I also added a new test to check if `env.path` actually works.

**Comment by kdy1** [comment]
We don’t apply everything as default

**Comment by egfx-notifications** [comment]
> We don’t apply everything as default

Ok, maybe this was phrased wrong. I mean that with the empty query in the autodiscovered files we take the same code path as previously without autodiscovery. So every transformation that was applied to the test cases before the PR without explicit configuration would also be applied now.

**Review by kdy1 — APPROVED** [review]
Thank you! I'll merge it once https://github.com/swc-project/swc/actions/runs/14299826346 is done!

**Review by kdy1 — COMMENTED** [review]
~I'll invert this PR with https://github.com/swc-project/swc/pull/10351~

Sorry it was already opt-in.
