### PR TITLE
fix(es/utils): Preserve optional chain effect

### LINKED ISSUE #8844: minifier: invalid parenthesizing when inlining switch statement with case clause expression contains optional chaining
### Describe the bug

Invalid parenthesizing makes expression invalid after compression.

### Input code

```typescript
const k = (() => {
  let x;
  switch (x) {
    case x?.x?.():
    default:
  }
})();
```

### Config

_No response_

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.4.13&code=H4sIAAAAAAAAA0vOzysuUchWsFXQ0NBUsLVTqOZSUMhJLVGosAYyisszS5IzFDQqNMHiCgrJicWpChX2ekCkoWkFFkpJTUsszSkBcWq5ajU1NK0Bkqo9h1QAAAA%3D&config=H4sIAAAAAAAAA32UO3LjMAyG%2B5zCozrFjostcoDtcgYOLYIyvSShIUDHmozvvtDDj40hdRI%2B%2FAAJgPh%2B2%2B2aE7XNx%2B5bPuWnt4Wg3P%2FFQkNmexFLA22y1JbQc%2FN%2BoycakbeRYDJdZ9KwLR3wpKL9r%2F1%2BUTQRkeCmWGwp5OCH55wtpr4A0ZNNrBKyJshM%2F%2BsXVvBrBFzqs%2F2AGMHmDWIsmZAZOiha4BZjtD2BOduiRBlPaksg1FKMsDI40xfsVZ5d4IBZcr5SB9aZFh0oKBRoOZxBk0kukWWS6yn3mbCDQ%2B26qc8%2F1HC2sVpWcsJlaomcVol6xEBsfM1aCWe4UoMZLsX9qQzeFOBa8qvuhCGv9OQvgFQgWqJsE2hxJw8v87Sm9pvKkL2MLA8Kl%2FnWbpmhk6KaELxS2bEyUDho3SzgagtjZVvtOAteKR8FBwa8l1lRQtNX4PaoJeWhB%2FQKkP5ar03VDMz9Fa7w8UFs4D9yS9YHbPFIlo%2FrlIZ0wLiRIAEf0W04SCsY13GRLXHp13nNDmQ0wKkulSbwugTkATCaOO3Ll9mQ5yERTRfx8FgTi8P1voeTzd3jvc%2Br%2BG1xaBK6OsFlyY%2F9nVfz7%2BbhdNvC94M3gT5vyjns9R%2F7ntJqMQYAAA%3D%3D

### SWC Info output

_No response_

### Expected behavior

```javascript
let k = (()=>{
    let x;
    x?.x?.();
})();
```
or
```javascript
let k = (()=>{
})();
```

### Actual behavior

```javascript
let k = (()=>{
    let x;
    (x?.x)();
})();
```
results in function call with `undefined` caller. (`undefined` is not a function Error occurred.)

### Version

1.4.13

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
Closes #8844

### CODE REVIEW

File: crates/swc_ecma_utils/src/lib.rs [hunk 1]
```diff
@@ -2520,11 +2520,6 @@ impl ExprCtx {
                 to.push(Box::new(Expr::New(e)))
             }
             Expr::Member(_) | Expr::SuperProp(_) => to.push(Box::new(expr)),
-            Expr::OptChain(OptChainExpr { ref base, .. })
```
Comment (Austaras) [inline crates/swc_ecma_utils/src/lib.rs:2523]: This is obviously wrong -- hasn't considered computed keys, and I'm worried about nested case too, so it's economical to just remove it.

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_core
 - swc_ecma_utils
