### PR TITLE
fix(ecma/transforms): loose mode for destructing 

### LINKED ISSUE #2841: TypeError: ref.slice is not a function
### Describe the bug

An unexpected error occurred when the array deconstructed the parameter list containing the default parameters.
When running the code transformed by swc, receiving such a bug report
```bash
 ref = arguments, a = ref[0], b = ref[1], restParam = ref.slice(2), ref;
                                                             ^
TypeError: ref.slice is not a function
```

### Input code

```typescript
function foo(a,b)
{
    [a,b,...restParam] = arguments;
    console.log(restParam);         // [3,4]
}
foo(12,2,3,4);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false,
      "dynamicImport": false,
      "privateMethod": false,
      "functionBind": false,
      "exportDefaultFrom": false,
      "exportNamespaceFrom": false,
      "decorators": false,
      "decoratorsBeforeExport": false,
      "topLevelAwait": false,
      "importMeta": false
    },
    "transform": null,
    "target": "es5",
    "loose": false,
    "externalHelpers": false
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.111&code=H4sIAAAAAAAAA0srzUsuyczPU0jLz9dI1EnS5OWq5uVSAIJoIE9HT0%2BvKLW4JCCxKDE3VsFWIbEovTQ3Na%2Bk2BqiKDk%2Frzg%2FJ1UvJz9dA65Q01oBBvT1FaKNdUxieblqeblAVhga6RjpAEU0rQGI7MtvegAAAA%3D%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

The source code is the code with correct semantics, and the output result is [3, 4]

### Version

1.2.111

### Additional context

I run swc use cmd as follows
```bash
npx swc --config-file=.swcrc poc.js -o poc.js
```
The environment is ubuntu 20.04 amd64.

### LINKED ISSUE #2863: Destructure a Non-Iterable Instance
### Describe the bug

A non-iterable instance is destructure correctly by swc. It is grammatically wrong.

### Input code

```typescript
// poc_01
[a] = 0;
// poc_02
[,,]=0
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false,
      "dynamicImport": false,
      "privateMethod": false,
      "functionBind": false,
      "exportDefaultFrom": false,
      "exportNamespaceFrom": false,
      "decorators": false,
      "decoratorsBeforeExport": false,
      "topLevelAwait": false,
      "importMeta": false
    },
    "transform": null,
    "target": "es5",
    "loose": false,
    "externalHelpers": false
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.112&code=H4sIAAAAAAAAA4tOjFWwVTCw5orW0Ym1NQAAuZl3ng8AAAA%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

There should be a syntax error like this:
```bash
cannot read property Symbol(Symbol.iterator)).
```
or 
```bash
Invalid attempt to destructure non-iterable instance.
```
Instead of running correctly after being converted》

### Version

1.2.112

### Additional context

I run swc use cmd as follows
```bash
npx swc --config-file=.swcrc poc.js -o poc.js
```
The environment is ubuntu 20.04 amd64.

### PR DESCRIPTION
**Pull request by RiESAEX**
fix #2841,fix #2863
when `loose: false`:
* if right is `array`: do nothing
* if right is `arguments`: `slice.call`
* if left has rest parameters: `_toArray`
* else: `_slicedToArray`

https://github.com/babel/babel/blob/main/packages/babel-traverse/src/scope/index.ts#L648

### CODE REVIEW

**Comment by Austaras** [comment]
I don't believe `arguments` should be handled specially here. Anything except an array literal should be transformed to `slice.call` in strict mode and `.slice()` in loose mode

**Comment by RiESAEX** [comment]
> I don't believe `arguments` should be handled specially here. Anything except an array literal should be transformed to `slice.call` in strict mode and `.slice()` in loose mode
 
Several case for right side 
1. `ArrayExpression`: distribute value on compile time and `.slice`
2. `arguments` in function: `slice.call`
3. other: helper function:  `_toArray` (and `_maybeArrayLike` if assume array-like object is iterable)

may be related: [babel-plugin-transform-destructuring](https://babeljs.io/docs/en/babel-plugin-transform-destructuring#allowarraylike)

**Comment by Austaras** [comment]
Yes, `new Array` and `Array.from` should also be considered

**Comment by kdy1** [comment]
I agree with @Austaras. Babel does not handle `arguments` specially, and we should not.


https://github.com/babel/babel/blob/23fec0c8c99a70b5739124dc2087a24f291b021e/packages/babel-plugin-transform-destructuring/src/index.ts

File: crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs [hunk 1]
```diff
@@ -650,12 +651,30 @@ impl Fold for AssignFolder {
...
-
+                        let r = match *right {
+                            Expr::Ident(Ident {
+                                sym: js_word!("arguments"),
+                                ..
+                            }) => {
+                                if self.c.loose {
+                                    *right
+                                } else {
+                                    Expr::Call(CallExpr {
```
Comment (kdy1) [inline crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs:662]: This seems inefficient.
Instead of creating a new box, I think creating `Box` here will be better.

File: crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs [hunk 2]
```diff
@@ -650,12 +651,30 @@ impl Fold for AssignFolder {
...
                             }),
                         );
-
+                        let r = match *right {
+                            Expr::Ident(Ident {
+                                sym: js_word!("arguments"),
+                                ..
+                            }) => {
+                                if self.c.loose {
+                                    *right
```
Comment (kdy1) [inline crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs:660]: Aften then, this can be just `r`.

File: crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs [hunk 3]
```diff
@@ -650,12 +651,30 @@ impl Fold for AssignFolder {
...
+                                    Expr::Call(CallExpr {
+                                        span,
+                                        callee: member_expr!(DUMMY_SP, Array.prototype.slice.call)
+                                            .as_callee(),
+                                        args: vec![right.as_arg()],
+                                        type_args: Default::default(),
+                                    })
+                                }
+                            }
+                            _ => *right,
```
Comment (kdy1) [inline crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs:671]: Also this can be modified to remove useless `memmove`.

**Review by kdy1 — CHANGES_REQUESTED** [review]
Thanks!
I found a small performance issue.

File: crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs [hunk 4]
```diff
@@ -650,12 +651,60 @@ impl Fold for AssignFolder {
                                 elems.len()
                             }),
                         );
-
                         exprs.push(Box::new(Expr::Assign(AssignExpr {
                             span: DUMMY_SP,
                             op: op!("="),
                             left: PatOrExpr::Pat(Box::new(Pat::Ident(ref_ident.clone().into()))),
-                            right,
+                            right: match self.c.loose {
```
Comment (kdy1) [inline crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs:658]: I think `if c.loose {} else {}` is better at here.

File: crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs [hunk 5]
```diff
@@ -650,12 +651,60 @@ impl Fold for AssignFolder {
...
+                                        callee: member_expr!(DUMMY_SP, Array.prototype.slice.call)
+                                            .as_callee(),
+                                        args: vec![right.as_arg()],
+                                        type_args: Default::default(),
+                                    })),
+                                    Expr::Array(..) => right,
+                                    _ => {
+                                        // if left has rest then need `_toArray`
+                                        // else `_slicedToArray`
+                                        match elems.iter().find(|elem| match elem {
```
Comment (kdy1) [inline crates/swc_ecma_transforms_compat/src/es2015/destructuring.rs:675]: I think `if iter.any() {}` is better than `match iter.find()` + `Some(_)`

**Review by kdy1 — CHANGES_REQUESTED** [review]
I found some code style issues.

**Review by kdy1 — APPROVED** [review]
LGTM, thanks!
