### PR TITLE
fix(source-map): better handling of multi-byte characters

### LINKED ISSUE #5145: Source maps do not seem to handle multi-byte characters properly
### Describe the bug

I'm trying to switch to swc for our emits completely in Deno, but I ran into this bug. The mapping of source maps has the width of multi-byte characters too long.

For exmaple:

image

...is mapped to two characters:

image

Or this comment:

image

Mapped to:

image

### Input code

```typescript
// This entire interface should be completely ignored by the coverage tool.
export interface Complex {
  // These comments should be ignored.
  foo: string;

  // But this is a stub, so this isn't really documentation.
  bar: string;

  // Really all these are doing is padding the line count.
  baz: string;
}

// Lets add some wide characters to ensure that the absolute byte offsets are
// being matched properly.
//
// 패딩에 대한 더 많은 문자.
function dependency(
  foo: string,
  bar: string,
  baz: string,
): Complex {
  return {
    foo,
    bar,
    baz,
  };
}

// Again just more wide characters for padding.
//
// 良い対策のためにいくつかのユニコード文字を投げる。
export function complex(
  foo: string,
  bar: string,
  baz: string,
): Complex {
  return dependency(
    foo,
    bar,
    baz,
  );
}

// And yet again for good measure.
// 更多用於填充的字元。
export function unused(
  foo: string,
  bar: string,
  baz: string,
): Complex {
  return complex(
    foo,
    bar,
    baz,
  );
}

// Using a non-ascii name again to ensure that the byte offsets match up
// correctly.
export const π = Math.PI;

// And same applies for this one, this one is unused and will show up in
// lacking coverage.
export function ƒ(): number {
  return (
    0
  );
}

// This arrow function should also show up as uncovered.
console.log("%s", () => 1);

// Make sure emojis work properly
console.log("📣❓");
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "target": "es2020",
    "loose": false,
    "externalHelpers": false
  },
  "sourceMaps": true
}
```

### Playground link

_No response_

### Expected behavior

Should be mapped to correct length.

### Actual behavior

https://evanw.github.io/source-map-visualization/#MTAyMwAvLyBMZXRzIGFkZCBzb21lIHdpZGUgY2hhcmFjdGVycyB0byBlbnN1cmUgdGhhdCB0aGUgYWJzb2x1dGUgYnl0ZSBvZmZzZXRzIGFyZQovLyBiZWluZyBtYXRjaGVkIHByb3Blcmx5LgovLwovLyDtjKjrlKnsl5Ag64yA7ZWcIOuNlCDrp47snYAg66y47J6QLgpmdW5jdGlvbiBkZXBlbmRlbmN5KGZvbywgYmFyLCBiYXopIHsKICAgIHJldHVybiB7CiAgICAgICAgZm9vLAogICAgICAgIGJhciwKICAgICAgICBiYXoKICAgIH07Cn0KLy8gQWdhaW4ganVzdCBtb3JlIHdpZGUgY2hhcmFjdGVycyBmb3IgcGFkZGluZy4KLy8KLy8g6Imv44GE5a++562W44Gu44Gf44KB44Gr44GE44GP44Gk44GL44Gu44Om44OL44Kz44O844OJ5paH5a2X44KS5oqV44GS44KL44CCCmV4cG9ydCBmdW5jdGlvbiBjb21wbGV4KGZvbywgYmFyLCBiYXopIHsKICAgIHJldHVybiBkZXBlbmRlbmN5KGZvbywgYmFyLCBiYXopOwp9Ci8vIEFuZCB5ZXQgYWdhaW4gZm9yIGdvb2QgbWVhc3VyZS4KLy8g5pu05aSa55So5pa85aGr5YWF55qE5a2X5YWD44CCCmV4cG9ydCBmdW5jdGlvbiB1bnVzZWQoZm9vLCBiYXIsIGJheikgewogICAgcmV0dXJuIGNvbXBsZXgoZm9vLCBiYXIsIGJheik7Cn0KLy8gVXNpbmcgYSBub24tYXNjaWkgbmFtZSBhZ2FpbiB0byBlbnN1cmUgdGhhdCB0aGUgYnl0ZSBvZmZzZXRzIG1hdGNoIHVwCi8vIGNvcnJlY3RseS4KZXhwb3J0IGNvbnN0IM+AID0gTWF0aC5QSTsKLy8gQW5kIHNhbWUgYXBwbGllcyBmb3IgdGhpcyBvbmUsIHRoaXMgb25lIGlzIHVudXNlZCBhbmQgd2lsbCBzaG93IHVwIGluCi8vIGxhY2tpbmcgY292ZXJhZ2UuCmV4cG9ydCBmdW5jdGlvbiDGkigpIHsKICAgIHJldHVybiAwOwp9Ci8vIFRoaXMgYXJyb3cgZnVuY3Rpb24gc2hvdWxkIGFsc28gc2hvdyB1cCBhcyB1bmNvdmVyZWQuCmNvbnNvbGUubG9nKCIlcyIsICgpPT4xKTsKLy8gTWFrZSBzdXJlIGVtb2ppcyB3b3JrIHByb3Blcmx5CmNvbnNvbGUubG9nKCLwn5Oj4p2TIik7CgoKLy8jIHNvdXJjZU1hcHBpbmdVUkw9ZmlsZS5qcy5tYXAyMzU3AHsidmVyc2lvbiI6Mywic291cmNlcyI6WyJmaWxlLnRzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQVlBLDZFQUE2RTtBQUM3RSwwQkFBMEI7QUFDMUIsRUFBRTtBQUNGLHNDQUFrQjtBQUNFLFNBQVgsVUFBVSxDQUNqQixHQUFXLEVBQ1gsR0FBVyxFQUNYLEdBQVcsRUFDRjtJQUNULE9BQU87UUFDTCxHQUFHO1FBQ0gsR0FBRztRQUNILEdBQUc7S0FDSixDQUFDO0NBQ0g7QUFFRCwrQ0FBK0M7QUFDL0MsRUFBRTtBQUNGLDhFQUE0QjtBQUNzQixPQUEzQyxTQUFTLE9BQU8sQ0FDckIsR0FBVyxFQUNYLEdBQVcsRUFDWCxHQUFXLEVBQ0Y7SUFDVCxPQUFPLFVBQVUsQ0FDZixHQUFHLEVBQ0gsR0FBRyxFQUNILEdBQUcsQ0FDSixDQUFDO0NBQ0g7QUFFRCxrQ0FBa0M7QUFDbEMsaUNBQWE7QUFDTyxPQUFiLFNBQVMsTUFBTSxDQUNwQixHQUFXLEVBQ1gsR0FBVyxFQUNYLEdBQVcsRUFDRjtJQUNULE9BQU8sT0FBTyxDQUNaLEdBQUcsRUFDSCxHQUFHLEVBQ0gsR0FBRyxDQUNKLENBQUM7Q0FDSDtBQUVELHdFQUF3RTtBQUN4RSxhQUFhO0FBQ2IsT0FBTyxNQUFNLEVBQUMsR0FBSSxJQUFJLENBQUMsRUFBRSxDQUFDO0FBRXpCLHdFQUF1RTtBQUN4RSxvQkFBb0I7QUFDcEIsT0FBTyxTQUFTLEVBQUMsR0FBWTtJQUMxQixPQUNDLENBQUMsQ0FDRDtDQUNIO0FBRUQsd0RBQXdEO0FBQ3hELE9BQU8sQ0FBQyxHQUFHLENBQUMsSUFBSSxFQUFFLElBQU0sQ0FBQyxDQUFDLENBQUM7QUFFM0IsaUNBQWlDO0FBQ2pDLE9BQU8sQ0FBQyxHQUFHLENBQUMsU0FBSSxDQUFDLENBQUMiLCJmaWxlIjoiZmlsZS5qcyIsInNvdXJjZXNDb250ZW50IjpbIi8vIFRoaXMgZW50aXJlIGludGVyZmFjZSBzaG91bGQgYmUgY29tcGxldGVseSBpZ25vcmVkIGJ5IHRoZSBjb3ZlcmFnZSB0b29sLlxuZXhwb3J0IGludGVyZmFjZSBDb21wbGV4IHtcbiAgLy8gVGhlc2UgY29tbWVudHMgc2hvdWxkIGJlIGlnbm9yZWQuXG4gIGZvbzogc3RyaW5nO1xuXG4gIC8vIEJ1dCB0aGlzIGlzIGEgc3R1Yiwgc28gdGhpcyBpc24ndCByZWFsbHkgZG9jdW1lbnRhdGlvbi5cbiAgYmFyOiBzdHJpbmc7XG5cbiAgLy8gUmVhbGx5IGFsbCB0aGVzZSBhcmUgZG9pbmcgaXMgcGFkZGluZyB0aGUgbGluZSBjb3VudC5cbiAgYmF6OiBzdHJpbmc7XG59XG5cbi8vIExldHMgYWRkIHNvbWUgd2lkZSBjaGFyYWN0ZXJzIHRvIGVuc3VyZSB0aGF0IHRoZSBhYnNvbHV0ZSBieXRlIG9mZnNldHMgYXJlXG4vLyBiZWluZyBtYXRjaGVkIHByb3Blcmx5LlxuLy9cbi8vIO2MqOuUqeyXkCDrjIDtlZwg642UIOunjuydgCDrrLjsnpAuXG5mdW5jdGlvbiBkZXBlbmRlbmN5KFxuICBmb286IHN0cmluZyxcbiAgYmFyOiBzdHJpbmcsXG4gIGJhejogc3RyaW5nLFxuKTogQ29tcGxleCB7XG4gIHJldHVybiB7XG4gICAgZm9vLFxuICAgIGJhcixcbiAgICBiYXosXG4gIH07XG59XG5cbi8vIEFnYWluIGp1c3QgbW9yZSB3aWRlIGNoYXJhY3RlcnMgZm9yIHBhZGRpbmcuXG4vL1xuLy8g6Imv44GE5a++562W44Gu44Gf44KB44Gr44GE44GP44Gk44GL44Gu44Om44OL44Kz44O844OJ5paH5a2X44KS5oqV44GS44KL44CCXG5leHBvcnQgZnVuY3Rpb24gY29tcGxleChcbiAgZm9vOiBzdHJpbmcsXG4gIGJhcjogc3RyaW5nLFxuICBiYXo6IHN0cmluZyxcbik6IENvbXBsZXgge1xuICByZXR1cm4gZGVwZW5kZW5jeShcbiAgICBmb28sXG4gICAgYmFyLFxuICAgIGJheixcbiAgKTtcbn1cblxuLy8gQW5kIHlldCBhZ2FpbiBmb3IgZ29vZCBtZWFzdXJlLlxuLy8g5pu05aSa55So5pa85aGr5YWF55qE5a2X5YWD44CCXG5leHBvcnQgZnVuY3Rpb24gdW51c2VkKFxuICBmb286IHN0cmluZyxcbiAgYmFyOiBzdHJpbmcsXG4gIGJhejogc3RyaW5nLFxuKTogQ29tcGxleCB7XG4gIHJldHVybiBjb21wbGV4KFxuICAgIGZvbyxcbiAgICBiYXIsXG4gICAgYmF6LFxuICApO1xufVxuXG4vLyBVc2luZyBhIG5vbi1hc2NpaSBuYW1lIGFnYWluIHRvIGVuc3VyZSB0aGF0IHRoZSBieXRlIG9mZnNldHMgbWF0Y2ggdXBcbi8vIGNvcnJlY3RseS5cbmV4cG9ydCBjb25zdCDPgCA9IE1hdGguUEk7XG5cbi8vIEFuZCBzYW1lIGFwcGxpZXMgZm9yIHRoaXMgb25lLCB0aGlzIG9uZSBpcyB1bnVzZWQgYW5kIHdpbGwgc2hvdyB1cCBpblxuLy8gbGFja2luZyBjb3ZlcmFnZS5cbmV4cG9ydCBmdW5jdGlvbiDGkigpOiBudW1iZXIge1xuICByZXR1cm4gKFxuICAgIDBcbiAgKTtcbn1cblxuLy8gVGhpcyBhcnJvdyBmdW5jdGlvbiBzaG91bGQgYWxzbyBzaG93IHVwIGFzIHVuY292ZXJlZC5cbmNvbnNvbGUubG9nKFwiJXNcIiwgKCkgPT4gMSk7XG5cbi8vIE1ha2Ugc3VyZSBlbW9qaXMgd29yayBwcm9wZXJseVxuY29uc29sZS5sb2coXCLwn5Oj4p2TXCIpO1xuIl19

### Version

swc/core: 1.2.210

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dsherret**
**Description:**

Uses character lengths instead of byte lengths in some places.

**Related issue (if exists):**

Closes #5145

### CODE REVIEW

**Comment by alexander-akait** [comment]
@kdy1 Note - we have the same bug in CSS codegen crate too (and in HTML, but HTML doesn't support source maps), so I will fix it after we merge it for ECMA

**Comment by dsherret** [comment]
I wrote a test for this and it seems to have fixed the destination, but there's still a bug in here in the source column so I'm trying to track that down. Compiling swc uses all my 64GB of memory in WSL 😅

File: crates/swc_ecma_codegen/src/text_writer/basic_impl.rs [hunk 1]
```diff
@@ -44,29 +44,27 @@ impl<'a, W: Write> JsWriter<'a, W> {
         }
     }
 
-    fn write_indent_string(&mut self) -> io::Result<usize> {
```
Comment (dsherret) [inline crates/swc_ecma_codegen/src/text_writer/basic_impl.rs:47]: These results were never used, so I removed them.

File: crates/swc_ecma_codegen/src/text_writer/basic_impl.rs [hunk 2]
```diff
@@ -44,29 +44,26 @@ impl<'a, W: Write> JsWriter<'a, W> {
...
-            cnt += self.raw_write(INDENT)?;
+            self.raw_write(INDENT)?;
         }
 
-        Ok(cnt)
+        Ok(())
     }
 
-    fn raw_write(&mut self, data: &[u8]) -> io::Result<usize> {
-        let written = self.wr.write(data)?;
```
Comment (dsherret) [inline crates/swc_ecma_codegen/src/text_writer/basic_impl.rs:59]: Since the `Result<usize>` was never used, the code here assumed that the data would always be written to the output. This would be a bug if not all the data was written, so I changed it to use `write_all`.

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_common
 - swc_ecma_codegen
