### PR TITLE
fix(es/compat): Init this in sub class constructor for async

### LINKED ISSUE #8452: assert_this_initialized check fired before super()
### Describe the bug

In some cases _assert_this_initialized fires before super() call which causes  `ReferenceError: this hasn't been initialised - super() hasn't been called`

### Input code

```typescript
class Test0 {}

class Test extends Test0 {
  constructor() {
    super(),
      console.log(async (e) => {
        await this.test();
      });
  }
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "dynamicImport": true,
      "tsx": true,
      "jsx": true
    },
    "loose": false,
    "externalHelpers": true
  },
  "env": {
    "targets": "> 0.25%, not dead, Safari >=8",
    "mode": "entry",
    "coreJs": "3.27",
    "loose": false,
    "bugfixes": true
  }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAAz2MwQqDMBBE7%2FsVc0ygiHfRr%2BgPhHVphZAUd6UVyb9rozineTPDcAyqeIpai60Q8c2Qn0ka75IAzkltXtjy7HxNAF0%2BctCjwjnJUZqYXy7omhhOPPrhWv8VvmEy2HvSxo5r57urKtUVKrQDPuJyYpYAAAA%3D&config=H4sIAAAAAAAAA32PzQrCQAyE732KJeCtFFFEEexZvfoEcZuWlna3ZKO0lL67a%2B2PePCW%2BWYSJl2gFBROw1F1fvSiRnbEs%2FbEtUaw8QRIV%2Bg057VAOLlJa7DK9aWqLYsPCT9oNsU1v6iY0UD6jwGltY68kWLpxjBQI8QGyzOVNbFb1oYlIPNcagtyRvLOQKzW0Wa3CpWxohLCJFQ3TJFzFZ8OY3GobELDS0a4naC2TNfhxjba7OFPtfsjS%2FOGvjsF%2FQv6%2BI68TQEAAA%3D%3D

### SWC Info output

_No response_

### Expected behavior

```javascript
var _this;
_this = _super.call(this);
var _this1 = _assert_this_initialized(_this);
```

Compiles well if i use `super();` instead of `super(),`

### Actual behavior

```javascript
var _this;
var _this1 = _assert_this_initialized(_this);
_this = _super.call(this),
```

### Version

1.3.101

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Austaras**
**Related issue:**

 - Closes https://github.com/swc-project/swc/issues/8452
 - Closes https://github.com/swc-project/swc/issues/9432

### CODE REVIEW

File: crates/swc_ecma_compat_es2017/src/async_to_generator.rs [hunk 1]
```diff
@@ -62,23 +63,34 @@ pub struct Config {
...
 #[fast_path(ShouldWork)]
 impl<C: Comments + Clone> VisitMut for AsyncToGenerator<C> {
     noop_visit_mut_type!(fail);
 
+    fn visit_mut_class(&mut self, c: &mut Class) {
+        if c.super_class.is_some() {
+            self.in_subclass = true;
+        }
+        c.visit_mut_children_with(self);
+        self.in_subclass = false;
```
Comment (kdy1) [inline crates/swc_ecma_compat_es2017/src/async_to_generator.rs:91]: Is it fine to store `false` directly?
I think it can cause a problem for statements after a nested class

**Review by kdy1 — DISMISSED** [review]
I don't think it's important

**Review by kdy1 — APPROVED** [review]
