### PR TITLE
#4756: instanceof callee should map to operator

### LINKED ISSUE #4756: Instanceof has mappings that are reversed
### Describe the bug

callee in instanceof helper points to first arg instead of `instanceof`.

actual:
Screenshot 2022-05-23 at 8 18 41 PM

expected:
Screenshot 2022-05-23 at 8 18 31 PM

### Input code

```typescript
true && 
	"test" instanceof "";
```

### Config

_No response_

### Playground link

_No response_

### Expected behavior

mapping for callee _instanceof should point to the op

### Actual behavior

mapping points to first argument

### Version

v1.2.189

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by 0xe**
**Description:**

Maps `callee` in `instanceof` helper to the operator location in source.

**BREAKING CHANGE:**

**Related issue (if exists):**

Closes https://github.com/swc-project/swc/issues/4756

### CODE REVIEW

File: crates/swc_ecma_transforms_compat/src/es2015/instanceof.rs [hunk 1]
```diff
@@ -60,9 +60,15 @@ impl VisitMut for InstanceOf {
             right,
         }) = expr
         {
+            let instanceof_span = Span {
+                lo: left.span().hi,
```
Comment (kdy1) [inline crates/swc_ecma_transforms_compat/src/es2015/instanceof.rs:64]: Please use `span_hi()` instead

File: crates/swc_ecma_transforms_compat/src/es2015/instanceof.rs [hunk 2]
```diff
@@ -60,9 +60,15 @@ impl VisitMut for InstanceOf {
...
+                hi: right.span().lo,
```
Comment (kdy1) [inline crates/swc_ecma_transforms_compat/src/es2015/instanceof.rs:65]: Please use `span_lo()` instead

**Review by kdy1 — CHANGES_REQUESTED** [review]

**Review by kdy1 — APPROVED** [review]
Thanks!

---

swc-bump:
 - swc_ecma_transforms_compat
