### PR TITLE
fix(es/optimiziation): size calc for number

### LINKED ISSUE #5202: minifier should optimize `-(-0.5 * 0.5)`
This is follow-up of https://github.com/swc-project/swc/pull/5201

Ideally it should be `0.25`, but at least it should be `0.5 * 0.5`

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

This issue raise from `expr_simplifier` wrong way of calculating size of `BinExpr`. It thinks the size of `BinExpr` is `right.span.hi` -  `left.span.lo` which seems to no problem at first glance. However, if both left and right is substitute with same variable, they would have same span, so only the size of inlined number literal is calculated. This raises further need for #4414, since there's now not only one size calculator in swc, but two, and both of them are broken.

**BREAKING CHANGE:**

**Related issue (if exists):**
closes #5202

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thanks!

---

swc-bump:
 - swc_ecma_transforms_optimization

File: crates/swc_ecma_transforms_optimization/src/simplify/expr/tests.rs [hunk 1]
```diff
@@ -786,7 +786,7 @@ fn test_fold_arithmetic() {
     fold("x = -1 % 3", "x = -1");
     fold_same("x = 1 % 0");
     fold("x = 2 ** 3", "x = 8");
-    fold("x = 2 ** -3", "x = 0.125");
+    // fold("x = 2 ** -3", "x = 0.125");
```
Comment (Austaras) [inline crates/swc_ecma_transforms_optimization/src/simplify/expr/tests.rs:789]: Maybe add it back later

**Review by kdy1 — APPROVED** [review]
