### PR TITLE
fix(es/base): Wrap new opt chain

### LINKED ISSUE #11612: minifier causes invalid optional chain from new expression
### Describe the bug

I noticed a change in minification when updating swc. swc will minify code that looks like this:

```js
const t=XE?.default;r=new t({...e})
```

to this:

```js
r=new XE?.default({...e})
```

which results in a `SyntaxError: Invalid optional chain from new expression` parse error when loading this javascript.

I believe this issue was introduced back in @swc/core 1.3.98 (1.3.97 does not have this problem). It appears to be reproducible on versions from 1.3.98 to 1.5.18 (latest).

The minification output before on 1.3.97 is:

```js
const t=XE?.default;r=new t({...e})
```

This is also fixable by turning off `compress.collapse_vars` and `compress.reduce_vars`.

### Input code

```typescript
const t=XE?.default;r=new t({...e})
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    },
    "target": "es2021",
    "loose": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": true,
        "side_effects": true,
        "switches": true,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true,
        "const_to_let": true,
        "pristine_globals": true
      },
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": true
}
```

### Link to the code that reproduces this issue

https://play.swc.rs/?version=1.15.18&code=H4sIAAAAAAAAA0vOzysuUSixjXC110tJTUsszSmxLrLNSy1XKNGo1tPTS63VBAAhDK1VIwAAAA%3D%3D&config=H4sIAAAAAAAAA32UO5LbMAyG%2Bz2FR3WKZIsUOUC6nIFDk6BMhw8NAXqt2fHdA1H0I2vInYQPP0ACID7fdrvhiGb4tfvkT%2F6ZdEEot3%2B24JxIn9kygIkaTfETDd%2Bu9IgLolKhWS4rGEiXEaiJ8P37%2B48uGELOCGx2OiB0W%2FTJu%2FkxpclxKoD4YGMrh6wREuH%2F%2Bs5K%2FsB%2Bkgf7PucAOr0gSqPyiWCEIgU2OQQ9IaiTLkKU5aS6eMxSigVWAqumkieRJ%2BvJ58Q5n6kFbZXJFgTkCxjyJ5BknItlCfl6wn0atrCv49ja%2FEUNJx2qJiEnnFtL%2BLRC1EP2SMrVJJVwhRs1WGEv7leld6oA1ZKedcfs00ZP%2FgJwBYJGTDqCFLd5OJ6nLbV7qfTJ8cjSLHCeb%2BmWCUYuqvLeCZVdKgOFvNTNArYaWCprpON0LNcBvQUFzvGoSPTDkzlIOWmeIDsBcHu1k4ZqBer2CDf48h5e4N98SZLnq3tETYdtinPc5%2FAiQQQ6ZPvCgTtBeRsXXhLnaZvXZIEnA6zoUrGB5x3A809ZhbYun0aDXwdHVGPI%2B%2FuW6A6X2xaOOo33575u4rfuMMRsa4N9xS%2F9XTfzz%2BHudF3C1xMMHv9chS3n5R%2F%2Fk5KULQYAAA%3D%3D

### SWC Info output

    Operating System:
        Platform: darwin
        Arch: arm64
        Machine Type: arm64
        Version: Darwin Kernel Version 25.2.0: Tue Nov 18 21:09:56 PST 2025; root:xnu-12377.61.12~1/RELEASE_ARM64_T6041
        CPU: (16 cores)
            Models: Apple M4 Max

    Binaries:
        Node: 24.13.0
        npm: 11.6.2
        Yarn: N/A
        pnpm: 10.28.2

    Relevant Packages:
        @swc/core: 1.15.18
        @swc/helpers: 0.5.19
        @swc/types: N/A
        typescript: 5.9.3

    SWC Config:
        output: N/A
        .swcrc path: N/A

    Next.js info:
        output: N/A

### Expected behavior

The minification output should not produce `SyntaxError: Invalid optional chain from new expression` parse error when loading the resulting javascript.

### Actual behavior

@swc/core minification emits code with `?.` (optional chaining) in a new expression that causes parse errors.

### Version

1.15.18

### Additional context

FWIW: the input code is kinda silly because if the optional chain results in `undefined` then the new expression will throw. But this code comes from a large module that I don't have source control access or much hope in maintaining a patch of.

Atm, I'm working around this by turning off the compression options that seem to cause this for only this code.

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
Closes #11612

### CODE REVIEW

File: crates/swc/tests/fixture/issues-11xxx/11612/output/index.js [hunk 1]
```diff
@@ -0,0 +1,3 @@
+r = new (XE?.default)({
```
Comment (coalman) [inline crates/swc/tests/fixture/issues-11xxx/11612/output/index.js:1]: I'm not familiar with the codebase, but you may want to have a test case where this code is the input and output. To ensure that we don't end up going from:


```js
r = new (XE?.default)({ ...e });
```

back to:

```js
r = new XE?.default({ ...e });
```

**Review by kdy1 — APPROVED** [review]
Thanks!
