### PR TITLE
fix(es/resolver): Correctly check strict mode

### LINKED ISSUE #8842: minifier: invalid handling of function scope
### Describe the bug

According to the [MDN: function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function#description)
> Like let, in strict mode, [function declarations are scoped to the most closely containing block](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function#block-level_function_declaration).

However, It seems that swc handle function scope incorrectly.

### Input code

```typescript
const k = (() => {
  function x() { console.log("hi") }
  {
    function x() { console.log("merong") }
  }
  return x;
})();
k();
```

### Config

_No response_

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.4.13&code=H4sIAAAAAAAAA0utKMgvKlFIK81LLsnMz1PI1tBUUKjmUkCIVABFqhWS8%2FOK83NS9XLy0zWUMjKVNBVquSAK8SvNTS3Kz0uHKgfhotSS0iKgUmuuWi6gZdYAlBBbpoEAAAA%3D&config=H4sIAAAAAAAAA32UO3LjMAyG%2B5zCozrFjostcoDtcgYOTYIyvXxoCNCxJuO7L0TJj40hdRI%2B%2FAAJgPh%2B2%2B26E5ruY%2FfNn%2Fwz6IJQ7v9swTGRvrClAxM1muIH6t5v9IQTcjogNNN1Jh3p0gM1Fe5%2F7feLogs5I9wUiy365N34nNPkOBRAfLKxlUPWCInwf%2F3CSv6aAJX6bD%2FkHECnDaI0Kp8IeihSYJND0AOCOusiRJlOqovHLKWYYCWwaih5EHmynnxOnPOVWtBWmWxBQL6AIX8GSca5WJaQryfcp2ELh9r3rc8%2F1HDWoWoScsKltYRPK0Q9Zo%2BkXE1SCWe4UoMZLsX9qfROFaBa0qvulH1a6clfAK5A0IhJR5DiNg%2FH87SmdptKnxyPLI0C5%2FmWbpmg56Iq751Q2akyUMhL3Sxgq4GpskY6zoJXyofeggLneFaE0PjlyRylpDQOkJ0AuL%2FaSVM1A3V%2FhSt8ehAb%2BA%2FfkuQBWzyipuM6xTEecthIEIGO2W44cCsor%2BPCW%2BIyrPOaLPBogBVdKjbwugT4AVBWoe3Ll9ng58ERVR%2Fy4bEmFofrfQ9HnfrHe59X8dvi0MVsa4PLkp%2F6O6%2Fm393D6baF7wfvPH7elC3p9R%2BoYzQdMAYAAA%3D%3D

### SWC Info output

_No response_

### Expected behavior

```javascript
let k = (()=>{
    function x() {
        console.log("hi");
    }
    return x;
})();
k();
```
stdout: "hi"

### Actual behavior

```javascript
let k = (()=>{
    function x() {
        console.log("hi");
    }
    function x() {
        console.log("merong");
    }
    return x;
})();
k();
```
stdout: "merong"

### Version

1.4.13

### Additional context

I don't know how swc handles strict mode script internally, but inserting pragma inside the body of the anonymous function resolves this. (sadly, prepending pragma in a first line of the script file or changing source type to "module" and mark k as a exported variable or function doesn't work)

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
Closes #8842

### CODE REVIEW

File: crates/swc_ecma_transforms_base/tests/fixture.rs [hunk 1]
```diff
@@ -47,15 +47,15 @@ where
         let lexer = Lexer::new(syntax, EsVersion::latest(), StringInput::from(&*fm), None);
         let mut parser = Parser::new_from(lexer);
 
-        let module = parser
-            .parse_module()
+        let program = parser
```
Comment (Austaras) [inline crates/swc_ecma_transforms_base/tests/fixture.rs:50]: Unrelated test file changes come from this.

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_ecma_transforms_base
 - swc_core

**Comment by kdy1** [comment]
CI failed and it does not look like a random failure.

```
Diff < left / right > :
 "use strict";
 function f() {
<    var x, g1;
>    var x, g;
     g();
     x = 10;
     throw Error("foo");
 }
 f();
 
```

**Comment by Austaras** [comment]
Consider the terser output, I believe the new output is desired.
```js
"use strict";
function f() {
    g();
    x = 10;
    throw new Error("foo");
    var x;
}
f();
```

**Review by kdy1 — APPROVED** [review]
