### PR TITLE
fix(es/parser): Don't be greedy in the end of jsx open el

### LINKED ISSUE #10635: @swc/core >= 1.12.2 seems problematic when compiling following tsx
### Describe the bug

where as v1.12.1 works

### Input code

```typescript
import styles from './foo.module.css';

function Foo() {
    return <div className={styles.foo}>=</div>
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2021",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true
}
```

### Link to the code that reproduces this issue

https://play.swc.rs/?version=1.12.3&code=H4sIAAAAAAAAAyXMTQqAIBBA4b2nmJ21sQOkLlt2B%2FEHBHXC0SDCuyf0tg%2B%2BmC%2BsDag9yROEihm42AKiyOh68sIS8Z2x0IttEQsciMsKL4NZ9a3XAtLFG2wyRKfJXr0%2FJiYytJLbvJqNDxYABRhpAAAA&config=H4sIAAAAAAAAA1VPSQ7DIAy85xXI5x7aHPOHPgJRJyJiE3akoih%2FLxBC25s9i2e8D0LASgomsecxL0FGwtj3jFByLN8ZAU4BSUUdGG4Xy1QojhtW5DgJYBkX5GJCGu%2FjoxnAeE%2BY4VkawoZZ7fScfiOVtyEi0b%2BwSKVbTPefiUNLBetfWyXbK6VuaZCvWe9Wgq%2FySuzXQdPzstdnjg9PtfOIGwEAAA%3D%3D

### SWC Info output

_No response_

### Expected behavior

```js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
const _foomodulecss = /*#__PURE__*/ _interop_require_default(require("./foo.module.css"));
function _interop_require_default(obj) {
    return obj && obj.__esModule ? obj : {
        default: obj
    };
}
function Foo() {
    return React.createElement("div", {
        className: _foomodulecss.default.foo
    }, "=");
}
```

### Actual behavior

```
  x Expression expected
   ,-[input.tsx:4:1]
 1 | import styles from './foo.module.css';
 2 | 
 3 | function Foo() {
 4 |     return <div className={styles.foo}>=</div>
   :                                       ^^
 5 | }
   `----
  x Expression expected
   ,-[input.tsx:4:1]
 1 | import styles from './foo.module.css';
 2 | 
 3 | function Foo() {
 4 |     return <div className={styles.foo}>=</div>
   :                                         ^
 5 | }
   `----
```

Caused by:
    0: failed to process js file
    1: Syntax Error

### Version

1.12.3

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by bvanjoi**
Fixes #10635

### CODE REVIEW

File: crates/swc_ecma_parser/src/lexer/state.rs [hunk 1]
```diff
@@ -177,6 +178,13 @@ impl crate::input::Tokens for Lexer<'_> {
         Tokens::scan_jsx_token(self, allow_multiline_jsx_text)
     }
 
+    fn rescan_jsx_open_ele_terminal_token(&mut self, reset: BytePos) -> Option<TokenAndSpan> {
```
Comment (kdy1) [inline crates/swc_ecma_parser/src/lexer/state.rs]: Can you use `el` instead of `ele` (over all places)?

**Review by kdy1 — APPROVED** [review]
