### PR TITLE
FIX: Fails to parse array spread in TSX props <Foo x={...arr}/>

### LINKED ISSUE #6977: Fails to parse array spread in TSX props `<Foo x={...arr}/>`
### Describe the bug

`swc` fails to parse array spread when it is directly in the prop assignment. Biggest issue is the error message not pointing to the prop, but rather complaining about the whole tag (the outer tag even when the issue is in some nested tag).

### Input code

```typescript
function Component(props: any) {
}

<Component x={...[1,2,3]} />
```

### Config

_No response_

### Playground link

https://play.swc.rs/?version=1.3.36&code=H4sIAAAAAAAAA0srzUsuyczPU3DOzy3Iz0vNK9EoKMovKLZSSMyr1FSo5uWq5eXi5bKBSytU2Fbr6elFG%2BoY6RjH1iro2%2FFyAQB53xVZRQAAAA%3D%3D&config=H4sIAAAAAAAAA0WOSwrDMAxE76J1FsWLLnyHHsK4SnDxD0mBGuO7VzYp2Q0zo6fp8GEPtkN1xEhTccvivmBBWkX2FKrABsJqCZ04VDs6ULSBbB7GaBpLYQS7u8i4QQo57G2yfEmVkPmOXD7ivzmUlcr7nEZf7xbzCeNmXHeBX1dxbfgBaADhoLcAAAA%3D

### Expected behavior

transpilation without errors:
```
function Component(props) {
}
React.createElement(Component, { x: [1, 2, 3] });
```

### Actual behavior

```
  x Unexpected token `Component`. Expected jsx identifier
   ,-[input.tsx:1:1]
 1 | function Component(props: any) {
 2 | }
 3 | 
 4 | <Component x={...[1,2,3]} />
   :  ^^^^^^^^^
   `----


Caused by:
    0: failed to process js file
    1: Syntax Error
```

### Version

1.3.36

### Additional context

The issue can be worked around by using `<Component x={[...[1,2,3]]}`

TS playground link: https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABAYTgWwA4IKZigCgwCc4MBnALkQEMwBPASkQG8AoAX1dYB5VMc8iAB4BeZgDpJAbQCMAGgBMcgMwBddogD0APlZA

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
**Description:**
You could refer to https://github.com/microsoft/TypeScript/blob/43cc362cef72e5fa1372f59736a9c4b55d85def0/src/compiler/parser.ts#L6107-L6133

**BREAKING CHANGE:**

**Related issue (if exists):**
Fixed #6977

### CODE REVIEW

File: crates/swc_ecma_parser/src/parser/jsx.rs [hunk 1]
```diff
@@ -143,6 +143,9 @@ impl<I: Tokens> Parser<I> {
         let expr = if is!(self, '}') {
             self.parse_jsx_empty_expr().map(JSXExpr::JSXEmptyExpr)?
         } else {
+            if is!(self, "...") {
```
Comment (IWANABETHATGUY) [inline crates/swc_ecma_parser/src/parser/jsx.rs:146]: Typescript parse this `dotdotdotToken` as an optional token but they parse still as a `JSXExpression`, I found that this token seems not to have effects on code generation, so I just skip it in the parsing phase.

**Review by Brooooooklyn — APPROVED** [review]

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_ecma_parser
