### PR TITLE
fix(ecmascript/transforms/classes/super_fields): Fix broken code when transpile super member access

### LINKED ISSUE #1959: Access super member in nested expr transform incorrect
## Describe the bug
transform `super.foo() + 1` will become `_get(_getPrototypeOf(Extended.prototype), 'getNext', this)() + 1` 
**Input code**
class Base {
	getNext() {
		return this.value++
	}
}

class Extended extends Base {
	getNext() {
		return super.getNext() + 1
	}
}

const ins = new Extended();
ins.getNext();
## Config

```json
{
  "module": {
    "type": "commonjs"
  }
}
```

## Expected behavior
should invoke super class member's function with call
``` js
 _get(_getPrototypeOf(Extended.prototype), "getNext", this).call(this) + 1;
```

**Version**
The version of @swc/core: 1.2.66

## Additional context
the code above will emit an error:
```
TypeError: Cannot read property 'value' of undefined
```

### PR DESCRIPTION
**Pull request by IronLu233**
close #1959

### CODE REVIEW

**Comment by IronLu233** [comment]
@kdy1 Not sure this fix is the best way, I need your help for best fix approach.

**Review by kdy1 — APPROVED** [review]
I think clone can be removed, but I'll try it by myself. Thanks!

**Comment by kdy1** [comment]
Postponing merge as tests fail.

**Comment by kdy1** [comment]
Oh sorry I missed your comment.

`_get(_getPrototypeOf(Extended.prototype), "getNext", this).call(this) + 1;` is ideal, which is also emitted by babel.

**Comment by IronLu233** [comment]
the CI test failed tells me this fix will cause a bug. I need more time to find a better way for fixing it. @kdy1

File: ecmascript/transforms/classes/src/super_field.rs [hunk 1]
```diff
@@ -193,6 +193,36 @@ impl<'a> Fold for SuperCalleeFolder<'a> {
...
+                    Expr::Call(CallExpr {
+                        span: DUMMY_SP,
+                        callee: MemberExpr {
+                            span: DUMMY_SP,
+                            obj: ExprOrSuper::Expr(expr.clone()),
+                            prop: Box::new(Expr::Ident(quote_ident!("call"))),
+                            computed: false,
+                        }
+                        .as_callee(),
+                        args: iter::once(this_arg).chain(args.clone()).collect(),
```
Comment (kdy1) [inline ecmascript/transforms/classes/src/super_field.rs:220]: Is cloing required?

File: ecmascript/transforms/classes/src/super_field.rs [hunk 2]
```diff
@@ -193,6 +193,36 @@ impl<'a> Fold for SuperCalleeFolder<'a> {
...
+                callee: ExprOrSuper::Expr(ref expr),
+                ref args,
+                ref type_args,
+                ..
+            }) => match &**expr {
+                Expr::Member(MemberExpr {
+                    obj: ExprOrSuper::Super(Super { span: super_token }),
+                    ..
+                }) => {
+                    let this_arg = ThisExpr {
```
Comment (kdy1) [inline ecmascript/transforms/classes/src/super_field.rs:207]: I looked at the diffs from test and this seems to be the cause. Maybe you need to use aliased variable instead.

Comment (IronLu233) [reply ecmascript/transforms/classes/src/super_field.rs:207]: Although I use 
``` rust
let this_arg = ThisExpr { span: DUMMY_SPAN };
```
the `this` still be transformed into `_this`

Comment (kdy1) [reply ecmascript/transforms/classes/src/super_field.rs:207]: I mean the reverse. Instead of using `ThisExpr`, you may try injecting `var _this = this`.

**Comment by IronLu233** [comment]
@kdy1 I need some help. When `_this` will be replaced with `_this1` or other ident?

**Comment by kdy1** [comment]
It depends on the context, but in this case `SuperCalleeFolder` ( https://github.com/swc-project/swc/blob/e916b35dd2ee3a191fee487ac61e64d9410b72ed/ecmascript/transforms/classes/src/super_field.rs )
This struct is used by all class transforms, including `decorators` which is used for tests for  #846

**Comment by IronLu233** [comment]
> It depends on the context, but in this case `SuperCalleeFolder` ( https://github.com/swc-project/swc/blob/e916b35dd2ee3a191fee487ac61e64d9410b72ed/ecmascript/transforms/classes/src/super_field.rs )
> This struct is used by all class transforms, including `decorators` which is used for tests for #846

So you mean adding `var _this = this` is not the best way for this? And I need find a better way for fixing it?

**Comment by kdy1** [comment]
I was confused by diff, sorry.
And this seems to require a different approach. Fixing `SuperCalleeFolder` seems good, but it's not a simple struct so it would take some time for debugging.

**Comment by IronLu233** [comment]
I have a new idea for fixing it.
Now, when we fold code like `super() + 114514`, the fold order in  `SuperFieldAccessFolder#fold_expr` is:
1. fold self with SuperCalleeFolder
2. transform super field call if necessary
3. fold children with self(`SuperFiledAccessFolder`)
My idea is change the order to
1. fold children with self`SuperFieldAccessFolder`
2. transform super call to `super.foo.call(this)` or `super.foo.apply(this)`
3. fold transformed expr with `SuperCalleeFolder`;
Soon I will check whether it is available

**Comment by IronLu233** [comment]
Hi, @kdy1 I meet another problem. When I ran the test `get_set_memoized_assign` using
``` bash
export RUST_BACKTRACE=full
export PATH="$PATH:$PWD/ecmascript/transforms/node_modules/.bin"
cargo test --package swc_ecma_transforms_compat --test es2015_classes --all-features -- get_set_memoized_assign --exact --nocapture
```

the unit test fails.
image
But when I run all unit test using
``` bash
    cargo test --all --all-features
```
it passes.
Why? seems unit test is not isolated.

And I want know how Mark works in span.
Please give me some help🙏

**Comment by kdy1** [comment]
> And I want know how Mark works in span.

https://rustdoc.swc.rs/swc_ecma_transforms_base/resolver/fn.resolver_with_mark.html decribes how resolver works. Resolver attach`Mark`s to the identifiers, so it will help.

I'm not sure about the unit test. It's isolated. And diff says the decision to inject a variable is different between the expected one and the actual one. No test suite does such a thing.

File: ecmascript/transforms/classes/src/super_field.rs [hunk 3]
```diff
@@ -101,7 +82,120 @@ impl<'a> Fold for SuperCalleeFolder<'a> {
...
+                    prop,
+                    computed,
+                    ..
+                }) => {
+                    let this = match self.constructor_this_mark {
+                        Some(mark) => quote_ident!(DUMMY_SP.apply_mark(mark), "_this").as_arg(),
+                        _ => ThisExpr { span: DUMMY_SP }.as_arg(),
+                    };
+
+                    let callee = self.super_to_get_call(*super_token, prop.clone(), *computed);
```
Comment (IronLu233) [inline ecmascript/transforms/classes/src/super_field.rs:146]: I don't know how to prevent `clone` in this match branch. I try to use *prop, but the compiler does not allow to do this.

File: ecmascript/transforms/proposal/src/decorators.rs [hunk 4]
```diff
@@ -355,7 +355,7 @@ impl Decorators {
                     vars: &mut vars,
                     constructor_this_mark: None,
                     is_static: method.is_static,
-                    folding_constructor: true,
+                    folding_constructor: false,
```
Comment (IronLu233) [inline ecmascript/transforms/proposal/src/decorators.rs:358]: Folding decorator seems not in constructor function, they are in the second parameter of `_decorate`, which is factory function for decorator.

File: ecmascript/transforms/compat/tests/es2020_class_properties.rs [hunk 5]
```diff
@@ -1791,7 +1791,7 @@ function (A1) {
 
     _foo.set(_assertThisInitialized(_this), {
       writable: true,
-      value: _get(_getPrototypeOf(B.prototype), "foo", _assertThisInitialized(_this))()
+      value: _get(_getPrototypeOf(B.prototype), "foo", _assertThisInitialized(_this)).call(_this)
```
Comment (IronLu233) [inline ecmascript/transforms/compat/tests/es2020_class_properties.rs:1794]: Here, in my opinion, if without `call`, the `this` may not point to the instance.

File: ecmascript/transforms/classes/src/super_field.rs (hunk 3 above)
Comment (kdy1) [reply ecmascript/transforms/classes/src/super_field.rs:146]: You can remove clone by changing `callee: ExprOrSuper::Expr(ref callee_expr), ` to `callee: ExprOrSuper::Expr(callee_expr)`, but I don't think it worth.
It requires reconstructing when `callee_expr` is not a member expression we wanted, and it means dirty code, and `memmove`.

I think clone is ok in this case, as `expr` in super[expr]` is very simple in most cases.

**Review by kdy1 — APPROVED** [review]
Thank you a lot!
Code becomes much more understandable. Thanks!
