### PR TITLE
fix(es/minifier): Do not add vars if `eval` exists

### LINKED ISSUE #8886: Minify: multiple same temp symbols declarations
### Describe the bug

code like: `const bar = ((v) => v)(1);`
will generate a temp value as function inline parameters like this:

```js
let v;
const bar = (v = 1, 1);
```

However if there are 2 same declarations with same parameter symbols:

```js
let v, v;
const bar = (v = 1, 1), foo = (v = 2, 2);
```

There will be 2 same declarations

### Input code

```typescript
const bar = ((v) => v)(1);
const foo = ((v) => v)(2);

eval(bar);
eval(foo);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es2022",
    "externalHelpers": true,
    "transform": {
      "react": {
        "development": true,
        "runtime": "automatic"
      }
    },
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": true,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true,
        "const_to_let": false,
        "pristine_globals": true,
        "passes": 99
      },
      "mangle": {
        "toplevel": false,
        "keep_classnames": false,
        "keep_fnames": false,
        "keep_private_props": false,
        "ie8": false,
        "safari10": false
      },
      "inlineSourcesContent": false
    },
    "loose": false
  },
  "minify": false,
  "isModule": true,
  "module": {
    "type": "es6"
  },
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.4.16&code=H4sIAAAAAAAAA0vOzysuUUhKLFKwVdDQKNNUsLVTKNPUMNS05koGS6Xl56NKGQGluFLLEnM0gLqAbDATqArIBACKP7PKTQAAAA%3D%3D&config=H4sIAAAAAAAAA42VvY7bMAyA9z5F4PmGa4ai17VA0aVTH8BQJMpRKouCSOUSHPLupe0kdRI66GbzE0nxVx%2BfVqtmR7b5tvqQT%2FnJphCU679I6JjYHETSgO0N2RIyNy8XuqMBeRMJRtFpIg2b0gGPWrR%2BXa%2FPGg0cGEoy8SfEDIXkAJcKF6ViEnks%2Fdx%2FAWN5JhCRgz1EzD0kvjEwna%2BJQw%2BDa1MZe8PBNmd8urljH1Lwx7kvi30uQHTrTkKpgy%2B6RPoyZwXf6fEWG8QIEs0yaQ21ITF0UxruDVuM0WSCdm%2BKYmW4qSmBUHMxwMrg2lwwqzy5wAGlDgp1YFxr0YGCQgHLYQ%2BamvgStUQSnhLPiB1sateN%2FXWnDXsTq2HFJxzGkshtFatbDMStr0lL4QQXcjDBc3LvNYNvC3At6VFvhyEt1OQPgGQgGqJketDsjie89NOStn%2BqGZKXluWjwiOqUSboJKltCF7J7JAZKBy0ahZw1cKQWatd54wX0kfBQQveS68opuk9sN1qTvmYAb0CpL7Ga101gfY6hQt8GIgn%2BIdEyXqDnU%2FIFtkuUzr2G4xPHPTAW3RPDkgpGJdxkS1xyMu8JgfSGuDUI5VG8LgEZAAY2zju6Xu1LMuFxWTbRdyoeyJLo49VfHu7rNfrs9Cb1I1rYLZGGXMcFvdSd%2F%2FH5DylcuP90OyXgX8Yaviq9aqReQyfX29esXkoIUVJw2%2BsxQJ9R9nYiRvtyZMRJJiRUf7vkbk6bgL9QlfjfCKb%2FiI5v8PDKEyv55dmsnX6C1nhPmStBwAA

### SWC Info output

_No response_

### Expected behavior

The temporary parameters need to be deconflicted.

### Actual behavior

_No response_

### Version

1.4.16

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kdy1**
**Related issue:**

 - Closes #8886

### CODE REVIEW

**Comment by kdy1** [comment]
Actually name mangler **cannot** work properly in presence of `eval`, because it cannot modify/add/remove a name even theoretically

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_minifier
 - swc_core

**Comment by Austaras** [comment]
I see. But there's still lots of changes in absence of `eval`, why?

**Comment by kdy1** [comment]
@Austaras Nice catch! Thank you. I was confused about the changes.

File: crates/swc_ecma_minifier/src/compress/optimize/iife.rs [hunk 1]
```diff
@@ -582,6 +592,10 @@ impl Optimizer<'_> {
                 trace_op!("iife: Expr::Fn(..)");
 
                 if !self.may_add_ident() {
```
Comment (kdy1) [inline crates/swc_ecma_minifier/src/compress/optimize/iife.rs:594]: @Austaras This condition can be `!false` if it's a top-level, but the previous code added variables to the top-level scope because we didn't check for parameter count

**Review by Austaras — APPROVED** [review]

**Comment by Austaras** [comment]
Wait, I see the problem now.

**Comment by Austaras** [comment]
This code maybe not of best quality, but I hope you get what I mean.

**Comment by kdy1** [comment]
Thank you so much 👍
