### PR TITLE
fix(es/compat): Remove wrong logic for object patterns in `object_rest`

### LINKED ISSUE #7776: Destructuring function array arg with 2 object destructuring entries causes clashing variable names
### Describe the bug

Given the input code below (Function Parameter of an Array Destructure with multiple Object Destructures) ends up causing clashed variable names in output. 

The transpile results in a variable `_param` or `_param#` getting reused for every object destructure entry in the array. 

### Input code

```typescript
function fn([
    { foo, ...flags },
    { bar }
  ]) {
      console.log(flags.rangeChanged);
  }
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": true,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.3.74&code=H4sIAAAAAAAAA0srzUsuyczPU0jL04jmUgCCaoW0%2FHwdBT09vbScxPRihVodqHBSYpFCLZAdq6lQDRZSUEjOzyvOz0nVy8lP1wCr1itKzEtPdc4AkSma1kBltQAG2t6%2FYgAAAA%3D%3D&config=H4sIAAAAAAAAA1WPPQ7DIAxGd06BPHdth94hh7CoExHxJ0ykoih3LyFA2w2%2Fz%2FYzu5ASVlbwlHt5liJgZIqjLoSzS%2FguBEhZZBV1SHDr6cpnNKNhqui4EkgYF0p1iu%2BtHYz3TIWluFFDVjs951%2Bf8jZEYu5rh8qiWwz920QzgvWvrYbtHykHuuwP%2BDZ12VgMmqc%2BeV4ljg%2F3WmjeEwEAAA%3D%3D

### Expected behavior

The destructure variable should be unique for each object in the array.

### Actual behavior

Duplicate variable name assignment for multiple destructure entries.

### Version

1.3.74

### Additional context

It seems similar or related to this issue: https://github.com/swc-project/swc/issues/1948

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

**Related issue:**

 - Closes #7776

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_transforms_compat

File: crates/swc_ecma_transforms_compat/tests/es2018_object_rest_spread.rs [hunk 1]
```diff
@@ -828,78 +830,60 @@ function b2(a, ...b) {}
...
+      var { a3 } = _param, c3 = _object_without_properties(_param, [
+          "a3"
+      ]), { a5 } = _param1, c5 = _object_without_properties(_param1, [
+          "a5"
+      ]);
+  }
+  function a5(_param) {
+      var { a3, b2: { ba1 } } = _param, ba2 = _object_without_properties(_param.b2, [
+          "ba1"
+      ]), c3 = _object_without_properties(_param, [
```
Comment (kdy1) [inline crates/swc_ecma_transforms_compat/tests/es2018_object_rest_spread.rs:857]: This is a regression
