### PR TITLE
Fix #2461: Update decorator design:type so the outputted metadata for union types is consistent with Typescript

### LINKED ISSUE #2461: Decorator design:type for union types
**Describe the bug**
When you have a union type on a decorated property the design:type is set to `void 0`.
TSC would set the type to `Object` instead.

**Input code**
```

class Xpto {
  @Decorator()
  prop!: string | number;
}

function Decorator() {
  return function (...args) {};
}

```
**Config**
```json
{
  "module": {
    "type": "commonjs"
  },
  "jsc": {
    "target": "es2018",
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "dynamicImport": false
    },
    "transform": {
      "legacyDecorator": false,
      "decoratorMetadata": true
    }
  }
}

```

**Current behavior**

TSC: 
```
__decorate([
    Decorator(),
   __metadata("design:type", Object)
], Xpto.prototype, "prop", void 0);
```

SWC: 
```
Reflect.metadata("design:type", void 0)
```

**Expected behavior**
SWC: 
```
Reflect.metadata("design:type", Object)
```

### PR DESCRIPTION
**Pull request by jameslnewell**
Fixes #2461.

Updates the decorator `design:type` so the outputted metadata for union types is consistent with Typescript

This is my first time using `rust` so 🤞 the code isn't too horrible 😬 

**BREAKING CHANGE:**

Nothing.

**Related issue (if exists):**

#2461

### CODE REVIEW

File: crates/swc_ecma_transforms/tests/decorators.rs [hunk 1]
```diff
@@ -5043,18 +5043,18 @@ let Sample = _class = _dec11(_class = _dec10(_class = _dec9(((_class = class Sam
 }, _dec1 = typeof Reflect !== "undefined" && typeof Reflect.metadata === "function" && Reflect.metadata("design:type", Function), _dec2 = typeof Reflect !== "undefined" && typeof Reflect.metadata === "function" && Reflect.metadata("design:paramtypes", [
     typeof Symbol === "undefined" ? Object : Symbol,
     Object,
+    Object,
     void 0,
-    void 0,
-    void 0,
-    void 0,
```
Comment (jameslnewell) [inline crates/swc_ecma_transforms/tests/decorators.rs:5049]: Updated the expected values to be what TS outputs.

File: crates/swc_ecma_transforms_proposal/src/decorators/legacy/metadata.rs [hunk 2]
```diff
@@ -428,7 +424,7 @@ fn serialize_type(class_name: Option<&Ident>, param: Option<&TsTypeAnn>) -> Expr
                     kind: TsKeywordTypeKind::TsUndefinedKeyword,
                     ..
                 }) => {
-                    continue;
+                    return quote_ident!("Object").into();
```
Comment (jameslnewell) [inline crates/swc_ecma_transforms_proposal/src/decorators/legacy/metadata.rs:427]: `string | null` => `Object` and `string | undefined` => `Object` according to TS

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAKgCwJZgOYBECmoBOBDKEHALhgAUcQAHTHKATy1wKJgF4YAKASnYD4YAbwC+AWABQEmDGAAbPBAjxkaIVOkwAAohQZsRFjnXSoK1Jyp58AWwCMpaDl0wAPjDABXWbIA0MSzYATA5QTqpuHmAAJpgAZiiYUX68IurCQA

File: crates/swc_ecma_transforms_proposal/src/decorators/legacy/metadata.rs [hunk 3]
```diff
@@ -469,7 +465,10 @@ fn serialize_type(class_name: Option<&Ident>, param: Option<&TsTypeAnn>) -> Expr
             }
         }
 
-        *undefined(DUMMY_SP)
+        match u {
+            Some(i) => i,
```
Comment (jameslnewell) [inline crates/swc_ecma_transforms_proposal/src/decorators/legacy/metadata.rs:469]: I think this fixes an issue where `string | never` => `void 0` instead of `String`

https://www.typescriptlang.org/play?#code/MYewdgzgLgBAKgCwJZgOYBECmoBOBDKEHALhgAUcQAHTHKATy1wKJgF4YAKASnYD4YAbwC+AWABQEmDGAAbPBAjxkaIVOkwAAohQZsRFjnXSoK1Jyp58AWwCMpaDl0wAPjDCYAbrV4j1woA

**Review by kdy1 — APPROVED** [review]
LGTM. Thanks!
