### PR TITLE
fix(es/typescript): support declaration merging of exported enums and namespaces in namespaces

### LINKED ISSUE #2954: Enum and namespace declaration merging in namespace does not work
### Describe the bug

We need to handle declaration merging of enums and namespace declarations within a namespace.

### Input code

```typescript
namespace Test {
    export enum MyEnum {
        A = 1,
    }
}
namespace Test {
    export enum MyEnum {
        B = 1,
    }
}
// another example
namespace Test {
    // this one should not be merged
    enum MyEnum {
        C = 1,
    }
}
```

### Config

_No response_

### Playground link

_No response_

### Expected behavior

Should output similar to TypeScript.

```ts
var Test;
(function (Test) {
    let MyEnum;
    (function (MyEnum) {
        MyEnum[MyEnum["A"] = 1] = "A";
    })(MyEnum = Test.MyEnum || (Test.MyEnum = {}));
})(Test || (Test = {}));
(function (Test) {
    let MyEnum;
    (function (MyEnum) {
        MyEnum[MyEnum["B"] = 1] = "B";
    })(MyEnum = Test.MyEnum || (Test.MyEnum = {}));
})(Test || (Test = {}));
(function (Test) {
    // this one should not be merged
    let MyEnum;
    (function (MyEnum) {
        MyEnum[MyEnum["C"] = 1] = "C";
    })(MyEnum || (MyEnum = {}));
})(Test || (Test = {}));
```

### Version

1.2.117

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dsherret**
Closes #2954

### CODE REVIEW

File: crates/swc_ecma_transforms_typescript/src/strip.rs [hunk 1]
```diff
@@ -1248,145 +1232,419 @@ where
...
+                            ModuleItem::Stmt(stmt) => Some(stmt),
+                            _ => None, // do not emit these as they are not valid in a module block
+                        }
+                    })
+                    .collect(),
+            )
         }
+    }
 
+    fn handle_module_items(
```
Comment (dsherret) [inline crates/swc_ecma_transforms_typescript/src/strip.rs:1257]: A lot of this was moved out of `visit_mut_module_items` and put here for reuse.

File: crates/swc_ecma_transforms_typescript/src/strip.rs [hunk 2]
```diff
@@ -1726,27 +2070,6 @@ where
...
-        s.alt.map_with_mut(|alt| {
-            alt.map(|s| match *s {
-                Stmt::Decl(Decl::TsEnum(e)) => {
-                    let mut stmts = vec![];
-                    self.handle_enum(e, &mut stmts);
-                    Box::new(Stmt::Block(BlockStmt { span, stmts }))
-                }
-                _ => s,
-            })
-        })
```
Comment (dsherret) [inline crates/swc_ecma_transforms_typescript/src/strip.rs:1749]: This code was removed because I don't ever think these would have happened because there is an `s.visit_mut_children_with(self)` as the first statement in this method. Also, I'm not sure what this code was trying to do.

File: crates/swc_ecma_transforms_typescript/src/strip.rs [hunk 3]
```diff
@@ -1248,145 +1232,419 @@ where
...
+        mut items: Vec<ModuleItem>,
+        parent_module_name: Option<&Ident>,
+    ) -> Vec<ModuleItem> {
         let mut delayed_vars = vec![];
-        let mut init_stmts = vec![];
 
-        for item in block.body {
-            // Drop
+        self.visit_mut_stmt_like(&mut items);
+        items.visit_with(&Invalid { span: DUMMY_SP }, self);
```
Comment (kdy1) [inline crates/swc_ecma_transforms_typescript/src/strip.rs:1265]: Can you rebase this?

**Review by kdy1 — CHANGES_REQUESTED** [review]
Code changes LGTM, thanks!
Can you rebase?

File: crates/swc_ecma_transforms_typescript/src/strip.rs (hunk 3 above)
Comment (dsherret) [reply crates/swc_ecma_transforms_typescript/src/strip.rs]: Done.

**Review by kdy1 — APPROVED** [review]
Thanks!
