### PR TITLE
fix(strip): Fix Config::import_not_used_as_values

### LINKED ISSUE #1065: TypeScript type imports are only stripped when they are used as a type at least once
**Describe the bug**

TypeScript type imports are only stripped when they are used as a type at least once, even if they are not used as a value.

**Input code**

Working correctly:

```ts
// test2.ts
export interface MyType {
  my_property: string;
}
```
```ts
// test1.ts
import { MyType } from "./test2.ts";

interface MySecondaryType extends MyType {
  
}
```

Not working correctly:

```ts
// test2.ts
export interface MyType {
  my_property: string;
}
```
```ts
// test1.ts
import { MyType } from "./test2.ts";
```

Also not working correctly:

```ts
// test2.ts
export interface MyType {
  my_property: string;
}
```
```ts
// test1.ts
import { MyType } from "./test2.ts";
export type { MyType };
```

**Expected behavior**
I expect that `import { MyType } from "./test2.ts";` is stripped away in both examples.

### LINKED ISSUE #1094: importsNotUsedAsValues is wrong
@kdy1 This is not the behaviour of `tsc` under `"importsNotUsedAsValues": "preserve"`. The correct behaviour is to _never_ preserve completely unused import identifiers. The above branch should always be used.

I think `ImportNotUsedAsValues` should be removed since it's a misunderstanding of the equivalent `tsc` option.

_Originally posted by @nayeemrmn in https://github.com/swc-project/swc/pull/1060#discussion_r491990064_

It's a breaking change.

### PR DESCRIPTION
**Pull request by nayeemrmn**
Closes #1065.
Closes #1094.

@kdy1 Could you cut a release after this?

### CODE REVIEW

File: ecmascript/transforms/src/typescript/strip.rs [hunk 1]
```diff
@@ -16,17 +16,19 @@ type EnumValues = FxHashMap<Id, TsLit>;
...
     #[serde(rename = "preserve")]
     Preserve,
 }
 
-/// This value defaults to `Preserve`
+/// This value defaults to `Remove`
 impl Default for ImportNotUsedAsValues {
     fn default() -> Self {
-        Self::Preserve
+        Self::Remove
```
Comment (kdy1) [inline ecmascript/transforms/src/typescript/strip.rs:31]: Is this safe?
Even if the default of tsc is remove, `swc` preserved those.

Comment (kdy1) [reply ecmascript/transforms/src/typescript/strip.rs:31]: I meant `breaking change` for rust side.
I'll not make a breaking change for js apis. Sorry if you are confused.

File: ecmascript/transforms/src/typescript/strip.rs [hunk 2]
```diff
@@ -713,26 +714,23 @@ impl VisitMut for Strip {
...
-                    },
-                    ImportNotUsedAsValues::Preserve => match entry {
-                        Some(&DeclInfo {
-                            has_type: true,
-                            has_concrete: false,
-                            ..
-                        }) => false,
-                        _ => true,
-                    },
+                match entry {
```
Comment (kdy1) [inline ecmascript/transforms/src/typescript/strip.rs:717]: Is this safe? 
It seems like semantic is changed from current behavior to `remove`

**Review by kdy1 — CHANGES_REQUESTED** [review]
Of course, I will publish a new version after this.

File: ecmascript/transforms/src/typescript/strip.rs (hunk 2 above)
Comment (nayeemrmn) [reply ecmascript/transforms/src/typescript/strip.rs:717]: This is the actual fix. The semantics for this bit should always be "remove". The meaning of `importsNotUsedAsValues` in `tsc` is to do with whether to keep an only-type import as a side-effect import, or remove it.

Comment (nayeemrmn) [reply ecmascript/transforms/src/typescript/strip.rs:717]: > Is this safe?

Always removing completely unused import identifiers won't cause any breakages, it's safe.

File: ecmascript/transforms/src/typescript/strip.rs (hunk 1 above)
Comment (nayeemrmn) [reply ecmascript/transforms/src/typescript/strip.rs]: Reverted 👍

File: ecmascript/transforms/src/typescript/strip.rs (hunk 2 above)
Comment (kdy1) [reply ecmascript/transforms/src/typescript/strip.rs:717]: You are right. Thanks!

**Comment by kdy1** [comment]
@nayeemrmn Test fails

**Comment by nayeemrmn** [comment]
Yeah I forgot to adapt the tests for the reverted default. Also I imagine a lot of other tests are dependent on the previous incorrect behaviour.

File: ecmascript/transforms/src/typescript/strip.rs (hunk 1 above)
Comment (nayeemrmn) [reply ecmascript/transforms/src/typescript/strip.rs]: Wait @kdy1 the effect of `ImportNotUsedAsValues` is completely different from before. Defaulting it to remove would actually align with the current behaviour. Do you mind if I change the default to "remove"? It would be safe after all.

Comment (kdy1) [reply ecmascript/transforms/src/typescript/strip.rs]: No, I don't mind it.
I think it's safe anyway as they are not used.

Comment (kdy1) [reply ecmascript/transforms/src/typescript/strip.rs:31]: Sorry, I was confused about it.

**Review by kdy1 — APPROVED** [review]
Thanks! I'll merge it and publish a new version if the tests pass.

**Comment by nayeemrmn** [comment]
@kdy1 Do you have an idea why this test is failing? It doesn't appear related to this change.
image
It happened in the other PR, too.

**Comment by kdy1** [comment]
Currently output of spack is not deterministic if it's invoked in concurrent mode.
(Semantics are preserved, though)

**Comment by kdy1** [comment]
I'll test locally
