### PR TITLE
Handle input source map correctly

### LINKED ISSUE #828: Sourcemaps not generated/usable
**Describe the bug**
Sourcemaps are not generated when `inputSourceMap` is specified.

**Input code**
```tsx
// index.tsx
import React from 'react';
import ReactDOM from 'react-dom';

const container = window.document.createElement('div');
window.document.body.appendChild(container);

ReactDOM.render(<div>App</div>, container);
```

**Config**
webpack+swc config
```js
// webpack.config.js
const HtmlWebpackPlugin = require('html-webpack-plugin');
const SriPlugin = require('webpack-subresource-integrity');

module.exports = {
  mode: 'development',
  entry: './src/index.tsx',
  resolve: {
    modules: [__dirname, '../../node_modules'],
    extensions: ['.tsx', '.js'],
  },
  output: {
    crossOriginLoading: 'anonymous',
  },
  module: {
    rules: [
      {
        test: /\.tsx$/,
        use: {
          loader: 'swc-loader',
          options: {
            inputSourceMap: true,
            jsc: {
              parser: {
                syntax: 'typescript',
                tsx: 'true',
              },
            },
          },
        },
      },
    ],
  },
  plugins: [
    new HtmlWebpackPlugin(),
    new SriPlugin({ hashFuncNames: ['sha256', 'sha384', 'sha512']}),
  ],
};
```

**Expected behavior**
Sourcemaps should allow debugging the original source. Instead, only the transformed source is visible.
2020-06-08 at 7 36 PM

**Version**
```
    "@swc/cli": "0.1.24",
    "@swc/core": "1.1.54",
    "swc-loader": "0.1.12",
```

**Additional context**

### PR DESCRIPTION
**Pull request by kdy1**
Closes #828

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -81,6 +81,65 @@ impl Compiler {
...
+                            return Ok(None);
+                        }
+                    }
+                }
+                InputSourceMap::Str(ref s) => {
+                    if s == "inline" {
+                        // Load inline source map by simple string
+                        // operations
+                        let s = "sourceMappingURL=data:application/json;base64,";
+                        let idx = s.rfind(s);
```
Comment (95th) [inline src/lib.rs:115]: This doesn't look right. Typo?

Comment (kdy1) [reply src/lib.rs:115]: @95th Oh... I'll fix it soon. Thank you very much.
