### PR TITLE
 fix(ecma/transform/compat): private getter/setter

### LINKED ISSUE #3618: Pirvate getter setter are wrongly transformed
### Describe the bug

swc would treat getter and setter as normal method, and generate two seperate weakset

### Input code

```typescript
class MyClass {
  get #a() {}
  set #a(x) {}
}
```

### Config

_No response_

### Playground link

https://play.swc.rs/?version=1.2.141&code=H4sIAAAAAAAAA0vOSSwuVvCtdAbT1VwKCumpJQrKiRqaCtW1QF4xhFcB5tYCAAb9JAAuAAAA&config=H4sIAAAAAAAAA0WOuw6DMAxFf6XyzEA7UIm5Kx9hBUOpyEO2qRqh%2FHsTHmKzrs899gofMdCuEJCFuEwSneIPWiBjUQxPQaHKWI6UF0oVKKOTwbMt%2BEwjmvgi4xnV8w5V0J9BR4o9KkI74CxbHXkkLQfkUd%2BbLJ%2B9FzqACuzkpiEWt%2FE2MIlcK3TjfJIpu6zvlxKsoDHQ5mwgXY6jN0l3gPt35L5bZ%2Fsk68G82Vu6PWtI6Q%2BymPZHFAEAAA%3D%3D

### Expected behavior

Only generate one WeakMap

### Actual behavior

_No response_

### Version

1.2.141

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

**BREAKING CHANGE:**
would require a new version of `@swc/helpers`

**Related issue (if exists):**
closes #3618

### CODE REVIEW

**Comment by Austaras** [comment]
I copied blindly from babel, which implementation is inefficient and [wrong](https://babeljs.io/repl#?browsers=chrome%2070&build=&builtIns=false&corejs=false&spec=false&loose=false&code_lz=MYGwhgzhAECC0G8BQ1oQKYBdoGIwAoAPASkRVWmAHsA7CKkdAOhCoHMjjyBfc6NrLgKlkqXqnI4ARtAC80AIwAmAMw0k5AGZUq-EX2iYAFgEsITPAGpLB68bMWpBg9ToNmrDvfPSuYpLxINOgA7nB6TNq6xEA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env&prettier=true&targets=&version=7.17.6&externalPlugins=&assumptions=%7B%7D), I will start all over again.

**Comment by Austaras** [comment]
This would be the final blockade before loose mode for class properties

**Review by kdy1 — COMMENTED** [review]
Note: I didn't review it fully yet. Just to ensure that I don't accidentally break downstream crates.

---

swc-bump:
 - swc_ecma_parser --breaking

File: crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs [hunk 1]
```diff
@@ -516,33 +523,10 @@ impl ClassProperties {
...
-                                args: vec![
-                                    class_ident.clone().as_arg(),
-                                    key.as_arg(),
-                                    value.as_arg(),
-                                ],
-                                type_args: Default::default(),
-                            }
-                            .into_stmt(),
-                        )
+                        extra_inits.insert(key, MemberInit::Prop(prop_span, value));
```
Comment (kdy1) [inline crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs:527]: Is the type of `key` `Expr?

Comment (kdy1) [reply crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs:527]: I think it's generally not safe to use it as a hash key.

File: crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs [hunk 2]
```diff
@@ -384,20 +394,17 @@ impl ClassProperties {
 
         let has_super = class.super_class.is_some();
 
-        let mut typescript_constructor_properties = vec![];
-
-        let mut constructor_exprs = vec![];
+        let mut constructor_inits = MemberInitMap::default();
         let mut vars = vec![];
-        let mut extra_stmts = vec![];
+        let mut extra_inits = MemberInitMap::default();
```
Comment (kdy1) [inline crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs:399]: Can you add some comment about the reason we use an indexed hashmap here? Is a vector not enough?

**Review by kdy1 — CHANGES_REQUESTED** [review]

File: crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs (hunk 1 above)
Comment (Austaras) [reply crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs:527]: This is indeed problemtic, but since public proerties name could be str/num/bigint, I don't find better way.

Comment (kdy1) [reply crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs:527]: Yeah, I had thought about it and I concluded that it's fine because we parse `NaN` as `Expr::Ident`.
So this is not relevant at the moment of this transform is applied.

Comment (Austaras) [reply crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs:527]: We also need to preserve evaluation order of member init

File: crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs (hunk 2 above)
Comment (Austaras) [reply crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs:400]: added

Comment (kdy1) [reply crates/swc_ecma_transforms_compat/src/es2022/class_properties/mod.rs:400]: Thanks!

**Review by kdy1 — APPROVED** [review]
Thank you so much!

**Comment by Austaras** [comment]
@kdy1 you seems like to public `@swc/helper` before this pr merge

**Comment by kdy1** [comment]
I published twice, once due to https://github.com/swc-project/swc/commit/72c9e6ca2b8186c4b297658bec1ce37912898d9f and once due to this PR
