### PR TITLE
fix(es/minifier): Apply new `SyntaxContext` to inlined `Arrow`

### LINKED ISSUE #8288: minify with mangle create incorrect code
### Describe the bug

it generates a code `(r?r=>r(e(r))` which should be `state=>selectorTransformer(selector(state))` (in unmangled mode).

the `r` is conflicting here, where the `r` in `r(e(r))` is referring to both `r` in the arrow function scope, (`state`) and `r` in the outer scope, `selectTransformer`.

the mangled code should keep track of the variable names in the scope

### Input code

```typescript
function memoizeWithArgs(
  fnWithArgs,
  options
) {
  const fn = proxyMemoize((args) => fnWithArgs(...args), options);
  return (...args) => fn(args);
}


function makeSelector(
  selector,
  selectorTransformer
) {
  return (state) => selectorTransformer(selector(state));
}

export function createSelectorHook(
  selector
) {
  const useSelectorHook = (
    selectorTransformer,
    deps
  ) => {
    const memoSelector = useMemo(
      () =>
        selectorTransformer && deps
          ? makeSelector(selector, memoizeWithArgs(selectorTransformer))
          : undefined,
      deps
    );
    const finalSelector = memoSelector
      ? memoSelector
      : selectorTransformer
      ? makeSelector(selector, selectorTransformer)
      : selector;
    return useSelector(finalSelector);
  };
  return useSelectorHook
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": true,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true,
        "const_to_let": true,
        "pristine_globals": true
      },
      "mangle": {
        "toplevel": false,
        "keep_classnames": false,
        "keep_fnames": false,
        "keep_private_props": false,
        "ie8": false,
        "safari10": false
      }
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": true,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.94-nightly-20231016.1&code=H4sIAAAAAAAAA4WSz2rDMAzG734KnYoDIQ%2FQ0o3ddtmpg51DomyhjR1sB7qVvPvkvziLYT7J8uefP0keFtGZUQqYcJLjD36M5utFfWrOAAYRdzXt5Gx1mlXwoF1HoSEFnGFW8v795q9z3pK8gvNTdps3TePSdYRUJ0IoNIsSkE79JQ84sZUxNiRz7RUveMPOSGWd6RDXWfyuWqEHqSZUwWN8QJvWoMMXtDzmgsw%2FjfdZKqovGugU0mG08CrlNbex6cmiNzpqkJUWfdbuoMdZU%2BAMPlzGg%2BxEIokoxLVN9jAAbvUhLsLhcIjouJ63jUxd3A2%2FgKuqDHSERfQ4jAL7OqTTU2626YOMor1lReQ1sWRqnzwWx%2FpPFSXXO553F75GNiu%2BseqKWLNf%2BmeqbP0FxQEFEzkDAAA%3D&config=H4sIAAAAAAAAA41VQY7bMAy87ysCn3vY5lAUfUBvfYOgWJSjVBYNkfImWOTvpRU7m93QRi9BzNGQIjmk3l92u%2BZEbfNr9y5%2F5WOwmSDfv8VCl8T2LJYG2t5Sm8PAzbcFPdEEeRsJqul6Qxq2uQOuLNq%2F7vczo4mIBAtjtvUhBX95jNliP2QgerCJVVyWHhLTZ%2F6MZXybAM7l0X5AjGDTBmIsmZAYOsia4xZjtAOBGW1WvEw3tTkQaiEmsDA4M2QcVDy5wAGTxHxGHVhnWnSgQCFDy2EEjSaxhJZI0lPyqbCDQ%2Bm62ucvbBhtLJaVmHCuLZHbKl6PGIiNL0kr4Q1cqcENnIv7lRm8ycAlp2feCUNa6clfAKlAtETJ9qD5rSe86GmN7TeZIXmRLF8UXPStZZmgk6KaELxS2akykDlo3czgSgtTZVvtOjO8Uj4KDgx4L1pRXNNb4PaoBeXLAOgVQPprvaaqG2DuU7iCTwOxAf%2BWLFkX2Hyit3xcR%2BnSHzBuBOiBj%2Bg2DkgrGNfhLFviPKzjJTkQaYBTjxSqwPMSkAFgNLHuyydtyHiIR9NFPHysifnA9b6He5u6Ou8P%2B5JxiDBCXJPxf4zIJip3GydVL5P9NL3wUxOllcEL318%2FPRuSysvyW5NqenTlIaGqydtz8qP5OLS8HEvVmkB%2FFmKt0%2FUfj5GfKOMGAAA%3D

### SWC Info output

_No response_

### Expected behavior

should minify into correct code

### Actual behavior

_No response_

### Version

1.3.94-nightly-20231016.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Austaras**
**Related issue:**

 - Closes #8288

### CODE REVIEW

File: crates/swc_ecma_minifier/src/compress/optimize/inline.rs [hunk 1]
```diff
@@ -827,6 +828,41 @@ impl Optimizer<'_> {
                         return;
                     }
 
+                    // currently renamer relies on the fact no distinct var has same ctxt, we need
+                    // to remap arrow params.
+                    let arrow = match &mut *value {
```
Comment (Austaras) [inline crates/swc_ecma_minifier/src/compress/optimize/inline.rs:833]: Maybe just run `resolver` agian? Wouldn't that be a bit overkill?

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_ecma_minifier
