### PR TITLE
fix(es/utils): check arguments ctxt

### LINKED ISSUE #5096: Arguments Parsing Failed
### Describe the bug

The origin code run by node print
```shell
[ 2, 3, 6, 5, 6 ]
```
While the transpiled code print 
```shell
[
  '[object Arguments]1',
  '[object Arguments]1',
  '[object Arguments]1',
  '[object Arguments]1',
  '[object Arguments]1'
]
```

### Input code

```typescript
function f0() {
    return Array.from(arguments, arguments => arguments + 1);
}
let v0 = f0(1, 2, 5, 4, 5);
console.log(v0);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6",
    "strict": false,
    "strictMode": false,
    "lazy": false,
    "noInterop": false
  },
  "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.2.208&code=H4sIAAAAAAAAA0srzUsuyczPU0gz0NBUqOZSAIKi1JLSojwFx6KixEq9tKL8XI3EovTS3NS8kmIdBThTwdYOiaOtYKhpzVXLlZNaolBmoGALMs9QR8FIR8FUR8EESAJlk%2FPzivNzUvVy8tM1ygw0rQEF%2B5y2fAAAAA%3D%3D&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1t93kDj2EcJXg4B8eB2KM716ZumQlMe%2FNdDphaeuUuUDK%2FNBi5Zs2EhsYtrhcyaim0c4eMgxVLofUqeClzKcEWdRQcNHtbS7ZFHIR4EEcD%2F83hw6F9Llm0Km2rHdWQoonaDxDq%2BzwXvav%2FgXU82csuwAAAA%3D%3D

### Expected behavior

The transpiled code can get the same print with the original code.

### Actual behavior

_No response_

### Version

1.2.208

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

It's not of much value to support non strict mode, it's not much effort either.

**BREAKING CHANGE:**

**Related issue (if exists):**
closes #5096

### CODE REVIEW

File: crates/swc_ecma_parser/src/parser/ident.rs [hunk 1]
```diff
@@ -133,6 +133,8 @@ impl<I: Tokens> Parser<I> {
             // It is a Syntax Error if StringValue of IdentifierName is the same String
             // value as the StringValue of any ReservedWord except for yield or await.
 
+            println!("{:#?}", w);
```
Comment (kdy1) [inline crates/swc_ecma_parser/src/parser/ident.rs:136]: I think this is a mistake?

File: crates/swc_ecma_utils/src/function/fn_env_hoister.rs [hunk 2]
```diff
@@ -17,6 +19,7 @@ struct SuperField {
 
 #[derive(Default)]
 pub struct FnEnvHoister {
+    pub unresolved_ctxt: SyntaxContext,
```
Comment (kdy1) [inline crates/swc_ecma_utils/src/function/fn_env_hoister.rs:22]: Why is this field public?

**Review by kdy1 — COMMENTED** [review]
I'm just curious

**Review by kdy1 — APPROVED** [review]
Thanks!


---

swc-bump:
 - swc_ecma_parser
 - swc_ecma_transforms_compat --breaking
