### PR TITLE
fix(es/minifier): Improve alias analyzer

### LINKED ISSUE #4587: minifier: Improve alias analyzer
This is regression by https://github.com/swc-project/swc/pull/4583

In https://github.com/swc-project/swc/pull/4583/files#diff-81cfaa3fb925d534428fc82d7cd1f37da9bfc510dec07cada416ff212e73f954

minifier thinks it's not safe to optimize

```js

var _name = getComponentName(type);
                error1("Component %s declared `PropTypes` instead of `propTypes`. Did you misspell the property assignment?", _name || "Unknown");
```

as 

```js
error1("Component %s declared `PropTypes` instead of `propTypes`. Did you misspell the property assignment?", getComponentName(type) || "Unknown"));
```

`getComponentName` call can modify `error1`.

This is correct, but we can improve alias analyzer so minifier can prove it's not the case

I'm writing it in a new issue because I'm going to merge #4583 

# Tasks

 - [ ] Reduce aliases detected by analyzer.

We can use `collect_infects` for analyzer, too.

 - [ ] Exclude pure calls like `Math.sin` from alias list

### LINKED ISSUE #5391: minifier: Fix `typescript`
https://github.com/privatenumber/minification-benchmarks

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

# Performance

## main

<details>

<summary>main</summary>

```
Benchmarking es/minify/libraries/antd
Benchmarking es/minify/libraries/antd: Warming up for 3.0000 s

Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 6.9s.
Benchmarking es/minify/libraries/antd: Collecting 10 samples in estimated 6.8577 s (10 iterations)
Benchmarking es/minify/libraries/antd: Analyzing
es/minify/libraries/antd
                        time:   [673.42 ms 676.76 ms 680.12 ms]
Benchmarking es/minify/libraries/d3
Benchmarking es/minify/libraries/d3: Warming up for 3.0000 s

Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 8.5s or enable flat sampling.
Benchmarking es/minify/libraries/d3: Collecting 10 samples in estimated 8.5318 s (55 iterations)
Benchmarking es/minify/libraries/d3: Analyzing
es/minify/libraries/d3  time:   [146.97 ms 148.69 ms 150.67 ms]
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high mild
Benchmarking es/minify/libraries/echarts
Benchmarking es/minify/libraries/echarts: Warming up for 3.0000 s

Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 6.0s.
Benchmarking es/minify/libraries/echarts: Collecting 10 samples in estimated 5.9839 s (10 iterations)
Benchmarking es/minify/libraries/echarts: Analyzing
es/minify/libraries/echarts
                        time:   [590.13 ms 593.14 ms 596.13 ms]
Found 2 outliers among 10 measurements (20.00%)
  1 (10.00%) low severe
  1 (10.00%) high severe
Benchmarking es/minify/libraries/jquery
Benchmarking es/minify/libraries/jquery: Warming up for 3.0000 s
Benchmarking es/minify/libraries/jquery: Collecting 10 samples in estimated 6.7473 s (165 iterations)
Benchmarking es/minify/libraries/jquery: Analyzing
es/minify/libraries/jquery
                        time:   [40.434 ms 40.776 ms 41.157 ms]
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) low mild
Benchmarking es/minify/libraries/lodash
Benchmarking es/minify/libraries/lodash: Warming up for 3.0000 s
Benchmarking es/minify/libraries/lodash: Collecting 10 samples in estimated 6.0030 s (110 iterations)
Benchmarking es/minify/libraries/lodash: Analyzing
es/minify/libraries/lodash
                        time:   [53.925 ms 55.179 ms 55.994 ms]
Benchmarking es/minify/libraries/moment
Benchmarking es/minify/libraries/moment: Warming up for 3.0000 s
Benchmarking es/minify/libraries/moment: Collecting 10 samples in estimated 5.3249 s (220 iterations)
Benchmarking es/minify/libraries/moment: Analyzing
es/minify/libraries/moment
                        time:   [23.854 ms 24.090 ms 24.261 ms]
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high mild
Benchmarking es/minify/libraries/react
Benchmarking es/minify/libraries/react: Warming up for 3.0000 s
Benchmarking es/minify/libraries/react: Collecting 10 samples in estimated 5.3658 s (660 iterations)
Benchmarking es/minify/libraries/react: Analyzing
es/minify/libraries/react
                        time:   [8.0642 ms 8.1151 ms 8.1569 ms]
Benchmarking es/minify/libraries/terser
Benchmarking es/minify/libraries/terser: Warming up for 3.0000 s

Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 6.5s or enable flat sampling.
Benchmarking es/minify/libraries/terser: Collecting 10 samples in estimated 6.5314 s (55 iterations)
Benchmarking es/minify/libraries/terser: Analyzing
es/minify/libraries/terser
                        time:   [117.58 ms 118.23 ms 118.95 ms]
Benchmarking es/minify/libraries/three
Benchmarking es/minify/libraries/three: Warming up for 3.0000 s
Benchmarking es/minify/libraries/three: Collecting 10 samples in estimated 6.3940 s (30 iterations)
Benchmarking es/minify/libraries/three: Analyzing
es/minify/libraries/three
                        time:   [210.69 ms 212.22 ms 213.79 ms]
Benchmarking es/minify/libraries/typescript
Benchmarking es/minify/libraries/typescript: Warming up for 3.0000 s

Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 14.3s.
Benchmarking es/minify/libraries/typescript: Collecting 10 samples in estimated 14.320 s (10 iterations)
Benchmarking es/minify/libraries/typescript: Analyzing
es/minify/libraries/typescript
                        time:   [1.4258 s 1.4439 s 1.4757 s]
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high severe
Benchmarking es/minify/libraries/victory
Benchmarking es/minify/libraries/victory: Warming up for 3.0000 s
Benchmarking es/minify/libraries/victory: Collecting 10 samples in estimated 5.9876 s (20 iterations)
Benchmarking es/minify/libraries/victory: Analyzing
es/minify/libraries/victory
                        time:   [294.19 ms 296.10 ms 298.28 ms]
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high mild
Benchmarking es/minify/libraries/vue
Benchmarking es/minify/libraries/vue: Warming up for 3.0000 s
Benchmarking es/minify/libraries/vue: Collecting 10 samples in estimated 6.4142 s (110 iterations)
Benchmarking es/minify/libraries/vue: Analyzing
es/minify/libraries/vue time:   [57.400 ms 58.538 ms 60.466 ms]
Found 2 outliers among 10 measurements (20.00%)
  2 (20.00%) high severe
```

</details>

## new

<details>

<summary>new</summary>

```
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 6.5s.
Benchmarking es/minify/libraries/antd: Collecting 10 samples in estimated 6.4608 s (10 iterations)
Benchmarking es/minify/libraries/antd: Analyzing
es/minify/libraries/antd
                        time:   [641.55 ms 643.30 ms 645.63 ms]
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high severe
Benchmarking es/minify/libraries/d3
Benchmarking es/minify/libraries/d3: Warming up for 3.0000 s

Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 8.0s or enable flat sampling.
Benchmarking es/minify/libraries/d3: Collecting 10 samples in estimated 8.0084 s (55 iterations)
Benchmarking es/minify/libraries/d3: Analyzing
es/minify/libraries/d3  time:   [141.42 ms 141.87 ms 142.33 ms]
Found 4 outliers among 10 measurements (40.00%)
  2 (20.00%) low severe
  1 (10.00%) high mild
  1 (10.00%) high severe
Benchmarking es/minify/libraries/echarts
Benchmarking es/minify/libraries/echarts: Warming up for 3.0000 s

Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 5.8s.
Benchmarking es/minify/libraries/echarts: Collecting 10 samples in estimated 5.7948 s (10 iterations)
Benchmarking es/minify/libraries/echarts: Analyzing
es/minify/libraries/echarts
                        time:   [579.72 ms 588.47 ms 600.90 ms]
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high severe
Benchmarking es/minify/libraries/jquery
Benchmarking es/minify/libraries/jquery: Warming up for 3.0000 s
Benchmarking es/minify/libraries/jquery: Collecting 10 samples in estimated 6.3958 s (165 iterations)
Benchmarking es/minify/libraries/jquery: Analyzing
es/minify/libraries/jquery
                        time:   [38.513 ms 38.703 ms 38.948 ms]
Benchmarking es/minify/libraries/lodash
Benchmarking es/minify/libraries/lodash: Warming up for 3.0000 s
Benchmarking es/minify/libraries/lodash: Collecting 10 samples in estimated 5.6216 s (110 iterations)
Benchmarking es/minify/libraries/lodash: Analyzing
es/minify/libraries/lodash
                        time:   [50.697 ms 50.898 ms 51.078 ms]
Found 2 outliers among 10 measurements (20.00%)
  1 (10.00%) low mild
  1 (10.00%) high mild
Benchmarking es/minify/libraries/moment
Benchmarking es/minify/libraries/moment: Warming up for 3.0000 s
Benchmarking es/minify/libraries/moment: Collecting 10 samples in estimated 5.1323 s (220 iterations)
Benchmarking es/minify/libraries/moment: Analyzing
es/minify/libraries/moment
                        time:   [23.215 ms 23.332 ms 23.499 ms]
Found 2 outliers among 10 measurements (20.00%)
  2 (20.00%) high mild
Benchmarking es/minify/libraries/react
Benchmarking es/minify/libraries/react: Warming up for 3.0000 s
Benchmarking es/minify/libraries/react: Collecting 10 samples in estimated 5.2294 s (660 iterations)
Benchmarking es/minify/libraries/react: Analyzing
es/minify/libraries/react
                        time:   [7.7903 ms 7.8067 ms 7.8340 ms]
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high mild
Benchmarking es/minify/libraries/terser
Benchmarking es/minify/libraries/terser: Warming up for 3.0000 s

Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 6.4s or enable flat sampling.
Benchmarking es/minify/libraries/terser: Collecting 10 samples in estimated 6.3729 s (55 iterations)
Benchmarking es/minify/libraries/terser: Analyzing
es/minify/libraries/terser
                        time:   [114.76 ms 115.06 ms 115.31 ms]
Benchmarking es/minify/libraries/three
Benchmarking es/minify/libraries/three: Warming up for 3.0000 s
Benchmarking es/minify/libraries/three: Collecting 10 samples in estimated 6.0615 s (30 iterations)
Benchmarking es/minify/libraries/three: Analyzing
es/minify/libraries/three
                        time:   [200.92 ms 202.20 ms 204.37 ms]
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high severe
Benchmarking es/minify/libraries/typescript
Benchmarking es/minify/libraries/typescript: Warming up for 3.0000 s

Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 13.9s.
Benchmarking es/minify/libraries/typescript: Collecting 10 samples in estimated 13.914 s (10 iterations)
Benchmarking es/minify/libraries/typescript: Analyzing
es/minify/libraries/typescript
                        time:   [1.3896 s 1.3925 s 1.3960 s]
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high mild
Benchmarking es/minify/libraries/victory
Benchmarking es/minify/libraries/victory: Warming up for 3.0000 s
Benchmarking es/minify/libraries/victory: Collecting 10 samples in estimated 5.8216 s (20 iterations)
Benchmarking es/minify/libraries/victory: Analyzing
es/minify/libraries/victory
                        time:   [290.12 ms 291.03 ms 291.93 ms]
Benchmarking es/minify/libraries/vue
Benchmarking es/minify/libraries/vue: Warming up for 3.0000 s
Benchmarking es/minify/libraries/vue: Collecting 10 samples in estimated 6.0376 s (110 iterations)
Benchmarking es/minify/libraries/vue: Analyzing
es/minify/libraries/vue time:   [54.595 ms 54.723 ms 54.878 ms]

```

</details>

# Investigation

```js
        return ts.chainBundle(context, transformSourceFile);
        /**
         * Transforms the module aspects of a SourceFile.
         *
         * @param node The SourceFile node.
         */
        function transformSourceFile(node) {
            if (node.isDeclarationFile ||
                !(ts.isEffectiveExternalModule(node, compilerOptions) ||
                    node.transformFlags & 4194304 /* ContainsDynamicImport */ ||
                    (ts.isJsonSourceFile(node) && ts.hasJsonModuleEmitEnabled(compilerOptions) && ts.outFile(compilerOptions)))) {
                return node;
            }
            currentSourceFile = node;
            currentModuleInfo = ts.collectExternalModuleInfo(context, node, resolver, compilerOptions);
            moduleInfoMap[ts.getOriginalNodeId(node)] = currentModuleInfo;
            // Perform the transformation.
            var transformModule = getTransformModuleDelegate(moduleKind);
            var updated = transformModule(node);
            currentSourceFile = undefined;
            currentModuleInfo = undefined;
            needUMDDynamicImportHelper = false;
            return updated;
        }
```

is miscompiled as

```js
        return ts.chainBundle(context, function(node) {
            var transformModule, updated;
            if (node.isDeclarationFile || !(ts.isEffectiveExternalModule(node, compilerOptions) || 4194304 & node.transformFlags || ts.isJsonSourceFile(node) && ts.hasJsonModuleEmitEnabled(compilerOptions) && ts.outFile(compilerOptions))) return node;
            return currentSourceFile = node, currentModuleInfo = ts.collectExternalModuleInfo(context, node, resolver, compilerOptions), moduleInfoMap[ts.getOriginalNodeId(node)] = currentModuleInfo, currentSourceFile = void 0, currentModuleInfo = void 0, needUMDDynamicImportHelper = !1, (function(moduleKind) {
                switch(moduleKind){
                    case ts.ModuleKind.AMD:
                        return transformAMDModule;
                    case ts.ModuleKind.UMD:
                        return transformUMDModule;
                    default:
                        return transformCommonJSModule;
                }
            })(moduleKind)(node);
        });
```

This is wrong because of the execution order

## Narrowing

image

 - `transformModule#7178` is inlined using sequential inliner

image

 - `updated#7178` is inlined using sequential inliner (**this is wrong**)

image

**Related issue (if exists):**
 - Closes #4587
 - Closes #5391

### CODE REVIEW

File: crates/swc_ecma_minifier/tests/terser/compress/collapse_vars/issue_1631_1/output.js [hunk 1]
```diff
@@ -1,9 +1,8 @@
 function f(x) {
-    return (pc = 200), 100;
```
Comment (kdy1) [inline crates/swc_ecma_minifier/tests/terser/compress/collapse_vars/issue_1631_1/output.js:2]: This is a bug

File: crates/swc_ecma_minifier/tests/terser/compress/collapse_vars/issue_1631_1/output.js [hunk 2]
```diff
@@ -1,9 +1,8 @@
...
+    return pc = 200, 100;
 }
 function x() {
-    var t = f();
-    return (pc += t);
```
Comment (kdy1) [inline crates/swc_ecma_minifier/tests/terser/compress/collapse_vars/issue_1631_1/output.js:6]: This is a bug

File: crates/swc_ecma_minifier/tests/fixture/next/react-ace/chunks/8a28b14e.d8fbda268ed281a1/output.js [hunk 3]
```diff
@@ -9496,29 +9496,29 @@
...
+                        for(var m, re = /(\t)|( +)|([\x00-\x1f\x80-\xa0\xad\u1680\u180E\u2000-\u200f\u2028\u2029\u202F\u205F\uFEFF\uFFF9-\uFFFC]+)|(\u3000)|([\u1100-\u115F\u11A3-\u11A7\u11FA-\u11FF\u2329-\u232A\u2E80-\u2E99\u2E9B-\u2EF3\u2F00-\u2FD5\u2FF0-\u2FFB\u3001-\u303E\u3041-\u3096\u3099-\u30FF\u3105-\u312D\u3131-\u318E\u3190-\u31BA\u31C0-\u31E3\u31F0-\u321E\u3220-\u3247\u3250-\u32FE\u3300-\u4DBF\u4E00-\uA48C\uA490-\uA4C6\uA960-\uA97C\uAC00-\uD7A3\uD7B0-\uD7C6\uD7CB-\uD7FB\uF900-\uFAFF\uFE10-\uFE19\uFE30-\uFE52\uFE54-\uFE66\uFE68-\uFE6B\uFF01-\uFF60\uFFE0-\uFFE6]|[\uD800-\uDBFF][\uDC00-\uDFFF])/g, valueFragment = this.dom.createFragment(this.element), i = 0; m = re.exec(value);){
                             var tab = m[1], simpleSpace = m[2], controlCharacter = m[3], cjkSpace = m[4], cjk = m[5];
-                            if (self1.showSpaces || !simpleSpace) {
+                            if (this.showSpaces || !simpleSpace) {
```
Comment (kdy1) [inline crates/swc_ecma_minifier/tests/fixture/next/react-ace/chunks/8a28b14e.d8fbda268ed281a1/output.js:9501]: This seems like a regression

File: crates/swc/tests/tsc-references/privateNameAndObjectRestSpread_es5.2.minified.js [hunk 4]
```diff
@@ -13,14 +13,7 @@ var _prop = new WeakMap(), C = function() {
...
     return C.prototype.method = function(other) {
-        var obj = _object_spread({}, other);
-        _class_private_field_get(obj, _prop);
-        var rest = _extends({}, other);
-        _class_private_field_get(rest, _prop);
-        var statics = _object_spread({}, C);
-        _class_static_private_field_spec_get(statics, C, _propStatic);
-        var sRest = _extends({}, C);
-        _class_static_private_field_spec_get(sRest, C, _propStatic);
+        _class_private_field_get(_object_spread({}, other), _prop), _class_private_field_get(_extends({}, other), _prop), _class_static_private_field_spec_get(_object_spread({}, C), C, _propStatic), _class_static_private_field_spec_get(_extends({}, C), C, _propStatic);
```
Comment (sokra) [inline crates/swc/tests/tsc-references/privateNameAndObjectRestSpread_es5.2.minified.js:16]: This is incorrect, since e.g. calling `_class_private_field_get` might change the exported value of  `_class_private_field_get`. Now the read and the call are switched.

**Review by sokra — CHANGES_REQUESTED** [review]

File: crates/swc/tests/tsc-references/privateNameAndObjectRestSpread_es5.2.minified.js (hunk 4 above)
Comment (kdy1) [reply crates/swc/tests/tsc-references/privateNameAndObjectRestSpread_es5.2.minified.js:16]: Yeah, I need to make it abort on imports, as we can't analyze those files.
Thank you!

**Review by kdy1 — COMMENTED** [review]
reset ci

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_minifier
