### PR TITLE
fix(es/compat): Fix generator transform for compound assignments, for-in, and labeled break

### LINKED ISSUE #5433: RangeError: Maximum call stack size exceeded
### Describe the bug

The original code can be run by the node, but after the translation, when the node is used again, the error is as follows:
```shell
RangeError: Maximum call stack size exceeded
```

### Input code

```typescript
function* v0(){
    try{
        var v1 = yield v2();
    }catch(v9){
    }
}
var v1 = ({foo : 10});
const v3 = JSON.stringify(v1, v0);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6",
    "strict": false,
    "strictMode": false,
    "lazy": false,
    "noInterop": false
  },
  "minify": false
}
```

### Playground link

https://play.swc.rs/?version=1.2.224&code=H4sIAAAAAAAAA0srzUsuyczP01IoM9DQrOZSAIKSokoIAwTKEosUygwVbBUqM1NzUhTKjDQ0rcGStcmJJckZGmWWUF21XLVccMUa1Wn5%2BQpWCoYGtUDlyfl5xSUKZcZACa9gfz%2B94pKizLz0zLRKjTJDHaDFmtYAlv7mnocAAAA%3D&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1t93kDj2EcJXg4B8eB2KM716ZumQlMe%2FNdDphaeuUuUDK%2FNBi5Zs2EhsYtrhcyaim0c4eMgxVLofUqeClzKcEWdRQcNHtbS7ZFHIR4EEcD%2F83hw6F9Llm0Km2rHdWQoonaDxDq%2BzwXvav%2FgXU82csuwAAAA%3D%3D

### Expected behavior

It can run normally after transpling.

### Actual behavior

_No response_

### Version

1.2.224

### Additional context

_No response_

### LINKED ISSUE #11046: ES5 generator transform produces extra function values when yielding nested object
### Describe the bug

When transpiling generator functions with recursion to ES5, SWC emits additional function values in the iteration result. Node.js and Babel correctly yield only the primitive values, but SWC’s output incorrectly includes anonymous functions.

### Input code

```typescript
function* traverse(obj) {
    for (let key of Object.keys(obj)) {
        if (typeof obj[key] === 'object') yield* traverse(obj[key]);
        else yield obj[key];
    }
}

const obj = {
    data: [1, 2, 3],
    nested: {
        fieldName: 'Nested',
        fieldData: 'Data'
    },
    get dataGenerator() {
        return traverse(this);
    }
}; 

function func1() {
    const generator = (function() {
        return obj.dataGenerator;
    })();
    
    const res = [];
    for (let value of generator) {
        res.push(value);
    }
    
    return res;
}

function main() {
    const res = func1();
    console.log(res);
}

main();
```

### Config

```json

```

### Link to the code that reproduces this issue

https://play.swc.rs/?version=1.13.5&code=H4sIAAAAAAAAA21Ry26DMBC8%2Byv2hl0hpLQ3ELdKvaUfgHJwYCGkxI5sEwlV%2Bff6hQtVffFjZmd2vP0sWjNK8QJG8QcqjVSerwy%2BCdjVSwV0QgNfuIDs4fN8xdYU9qY9beW5NfZAzXJHS7NQYzknqOsaMumLMgbLiFO3N%2FI0ViURnDQGXhIJ4JM8CWml0MYBUEfjjhteQnPI4TWHt1PuHwVqg1256a13ikd%2BwxKyo0ezfA%2B%2Be6HMbVkwDITBhncmHyhQcSMV3WZWaGYlfhOZy6hZargCQvr4v%2BAOh1QckgyrqM1DV%2BZ%2FBjZysesiejAa3TaiCrWVa%2BK%2FpQk%2B%2BDSjm2Ey3fvo4j7rC%2FW0FCFJxz4srXKDSKlufBR%2FQgX%2FGLdKgJywmORALcy8RiitfgBEkr05gQIAAA%3D%3D&config=H4sIAAAAAAAAA1WPSQ6DMAxF95wi8pptu%2BgdOIQVDArKpDiVGiHu3pCBll38%2F7Ofsg9CwMYSXmLPzzx4DEzhmnPCyUb85ARIGmQZlI8w9nbjs1pQM5XoqA1EDCvFssWPhoN2jqnjLTPKqiX9C6UzPhDzHTxRtKumu25oSjBufpeyfSQmT1X%2FhB%2FUZddhUDz1zXr2%2BAIDhbm2FQEAAA%3D%3D

### SWC Info output

_No response_

### Expected behavior

SWC's ES5 should print: `[ 1, 2, 3, 'Nested', 'Data' ]`

### Actual behavior

It prints: `[ 1, 2, 3, 'Nested', 'Data', [Function (anonymous)], [Function (anonymous)], [Function (anonymous)] ]`

### Version

1.13.5

### Additional context

_No response_

### LINKED ISSUE #11047: ES5 destructuring transform drops array hole and shifts default value assignment
### Describe the bug

When transpiling array destructuring with holes and default values inside async functions, SWC’s ES5 output fails to preserve the hole. As a result, the default value is skipped and the wrong element is bound. Node.js and Babel output the expected result, but SWC assigns the next array element instead.

### Input code

```typescript
const timeoutPromise = (timeout) => new Promise(resolve => setTimeout(resolve, timeout));

const processArray = async (array) => {
    const [first, , third = 'default', ...rest] = array;
    
    if (!first || !third) {
        return; 
    }
    await timeoutPromise(10);
    return {first, third, rest};
}

const func1 = async () => {
    return await processArray(['value1', 'value2', , 'value4', 'value5', 'value6', 'value7']);
}

const main = async () => {
    const res = await func1();
    console.log(res);
}

main();
```

### Config

```json

```

### Link to the code that reproduces this issue

https://play.swc.rs/?version=1.13.5&code=H4sIAAAAAAAAA22Rz2rDMAzG73kK9RQbQljG%2FhxCB3uDHXorPZhU2QyOXWynpbR591q2k4UxH4ws6ftJX9IZ7Tx4OaAZ%2FZc1g3QIW2A5w2H7ARovkEvMojPqjJR26Hepa85WM4jztii6iD5Z06Fzn9aKawALd9UdMEHPCL8VEE7q3ffSOl9B4PxIewzt5RF7MSpfVlDXdRjjDwQhdRuF8ZI9sE3Uwv0OmyjmmUzHoh%2BtblPzFG9xEfKvb9Y88URNArjlfSKwAho%2FtcU0W%2BtH3TW%2FnlZ2sj4NWX8Bti%2FPQo3YBEMpei7Jb4pfluzrEr0t0Xt54Kvpg5D63%2BGpHJalatwgLsqyNyobhbUy3%2FTfEpJgoeEBgTp5Lg4CAAA%3D&config=H4sIAAAAAAAAA1WPSQ6DMAxF95wi8pptu%2BgdOIQVDArKpDiVGiHu3pCBll38%2F7Ofsg9CwMYSXmLPzzx4DEzhmnPCyUb85ARIGmQZlI8w9nbjs1pQM5XoqA1EDCvFssWPhoN2jqnjLTPKqiX9C6UzPhDzHTxRtKumu25oSjBufpeyfSQmT1X%2FhB%2FUZddhUDz1zXr2%2BAIDhbm2FQEAAA%3D%3D

### SWC Info output

_No response_

### Expected behavior

SWC's ES5 output should print this:

`{
  first: 'value1',
  third: 'default',
  rest: [ 'value4', 'value5', 'value6', 'value7' ]
}`

### Actual behavior

But, it prints: `{
  first: 'value1',
  third: 'value4',
  rest: [ 'value5', 'value6', 'value7' ]
}`

### Version

1.13.5

### Additional context

_No response_

### LINKED ISSUE #11048: Default values in async function array destructuring miscompiled in ES5 target
### Describe the bug

When using array destructuring with skipped elements and default values inside an async function, SWC’s ES5 output shifts elements instead of applying the default. This causes wrong bindings for subsequent variables. Node.js and Babel handle this correctly.

### Input code

```typescript
async function fetchResource() {
  let data = ["John", , 25, "Developer", "California"]; 
  await new Promise(resolve => setTimeout(resolve, 500));
  return data;
}

function func1() {
  return new Promise(async (resolve, reject) => {
    let resource = await fetchResource();
    const [firstName, middleName = "N/A", age, ...rest] = resource;
    
    const result = (function() {
      if(firstName) {
        return {firstName, middleName, age, occupation: rest[0], location: rest[1]};
      } else {
        return {error: "Failed to fetch resource"};
      }
    })();
    
    resolve(result);
  });
}

async function main() {
  const res = await func1();
  console.log(res);
}

main();
```

### Config

```json

```

### Link to the code that reproduces this issue

https://play.swc.rs/?version=1.13.5&code=H4sIAAAAAAAAA22SPWvDMBCGd%2F%2BKQ5MNxnUKWWJSKC0dOoRSugUPQj4nKrIU5HNCCf7vlSx%2FpCVeJO7jee89mbc%2FWkDdaUHSaKiRxPETW9NZgXEC1whAIUHFicMW9uzdHDVLIYXHdQrsFc%2BozAmtC7EXrmRtrJaclQW4Rn7hkkDjBT6saWSLsXVkdUbYPkGL9CUbNB1N0RTWeZ4kheu0SJ3Vg2oR9VG0zOcuq3GuseiWzwc3C9DiNwpKvJ7vCF7saM%2F5CRP%2BM10MlcLolmBfS9vSjjcO1siqUujvrpPtHp6daX5wiSzLHJNKF57YgXEDcolOkauIJy%2BjC%2F%2FJOp51lujs8Hp3iFHcCNGduAduvAjt8zIFZcRtaFX2xQjtAVWLdzTQWmM3wN64VFgBmbCW2RFbEMPZJ9OmooAZVh4Hn0OmT4a343%2F%2FsIbLyfq8meUlwvMWY9IozJQ5eGhghebiF4o7q3a1AgAA&config=H4sIAAAAAAAAA1WPSQ6DMAxF95wi8pptu%2BgdOIQVDArKpDiVGiHu3pCBll38%2F7Ofsg9CwMYSXmLPzzx4DEzhmnPCyUb85ARIGmQZlI8w9nbjs1pQM5XoqA1EDCvFssWPhoN2jqnjLTPKqiX9C6UzPhDzHTxRtKumu25oSjBufpeyfSQmT1X%2FhB%2FUZddhUDz1zXr2%2BAIDhbm2FQEAAA%3D%3D

### SWC Info output

_No response_

### Expected behavior

SWC's ES5 output should print: 

```
{
  firstName: 'John',
  middleName: 'N/A',
  age: 25,
  occupation: 'Developer',
  location: 'California'
}
```

### Actual behavior

But, it actually prints:

```
{
  firstName: 'John',
  middleName: 25,
  age: 'Developer',
  occupation: 'California',
  location: undefined
}
```

### Version

1.13.5

### Additional context

_No response_

### LINKED ISSUE #11049: ES5 async array destructuring awaited value replaced with pending Promise
### Describe the bug

When using nested array destructuring with holes inside an async function, SWC’s ES5 output mishandles the destructuring. The transform drops the hole and shifts values, causing one of the awaited results to be replaced with a raw, unresolved Promise. Node.js and Babel transpilation both yield the correct values.

### Input code

```typescript
class MyClass {
    constructor(data) {
        if (!(data instanceof Array))
            throw new Error('Invalid instance');
        this.data = data;
    }
}

function fetchPromise(idx) {
    return new Promise((resolve, reject) => {
        setTimeout(() => resolve(idx), 10)
    })
}

async function func1() {
    const arr = [1, [2, 3], , 4];
    let [a, [ , b], ,d] = arr;

    const instance = new MyClass([a, b, d])

    a = await fetchPromise(instance.data[0]) || fetchPromise(0);
    b = await fetchPromise(instance.data[1]) || fetchPromise(0);
    d = await fetchPromise(instance.data[2]) || fetchPromise(0);
    
    return [a, b, d];
}

function main() {
    const res = func1();
    res.then(value => console.log(value));
}

main();
```

### Config

```json

```

### Link to the code that reproduces this issue

https://play.swc.rs/?version=1.13.5&code=H4sIAAAAAAAAA41SsW7CMBDd8xXXCVuyEKHdIipVVYcOlTp0izIY51JcBVuyHSgq%2FHvPToDAgLjF0b137%2B7eRbXSe%2FjYvab3LwMKZY0PrlPBOlbLIPmQj6EbYA8pC5pY0ii0Dbw4J3ecn1gxwsrZLRjcwptzpDR5NxvZ6vpUN%2BFFdiZrP02qC4hPjxyyQ5Y1nVFBWwMNBrX6dHatPTJd%2Fx7Hchg6Z1KnI8ocettuUBD4gypwWDyPlvAYvvQabRcYS9BAT6oC8lm%2FyYHH%2FtLvjILzFPSRMz62CqRzNHeZCyjnAh4rAQKeqn6HFgOUkhDKLSNSV8SliiIbKRw9ISjuMdyDxcKlgLriPTnaI7dShyszhurkYDmrOOz3l4zZ4PXyHoH8hkB9j8D8hsD4ZKf1iotDr6U2Vw7Tgajx4H0xaPhpWKFh9Fd1GK8YqbbFaWu%2F%2ByTnSbjXK%2F4BwB%2BqNusCAAA%3D&config=H4sIAAAAAAAAA1WPSQ6DMAxF95wi8pptu%2BgdOIQVDArKpDiVGiHu3pCBll38%2F7Ofsg9CwMYSXmLPzzx4DEzhmnPCyUb85ARIGmQZlI8w9nbjs1pQM5XoqA1EDCvFssWPhoN2jqnjLTPKqiX9C6UzPhDzHTxRtKumu25oSjBufpeyfSQmT1X%2FhB%2FUZddhUDz1zXr2%2BAIDhbm2FQEAAA%3D%3D

### SWC Info output

_No response_

### Expected behavior

SWC's ES5 output should print: `[ 1, 3, 4 ]`

### Actual behavior

But, it prints: `[ 1, 3, Promise { <pending> } ]`

### Version

1.13.5

### Additional context

_No response_

### LINKED ISSUE #11050: ES5 async short-circuit assignment and labeled break miscompiled causing wrong control flow
### Describe the bug

In an async function, `val = val || await complexCompute(5)` inside a labeled block with break outer_block and a switch should keep `val === 1` and take the case 1 branch. SWC’s ES5 transform changes the control flow so the labeled break path isn’t honored and falls through to the final assignment.

### Input code

```typescript
async function complexCompute(num) {
  return new Promise(resolve => {
    setTimeout(() => {
      resolve(num * 2);
    }, 2000);
  });
}

async function func1() {
  let result;
  let val = 1; // initial assignment
  val = val || await complexCompute(5);

  outer_block: {
    if (!val) {
      result = "No Value";
      break outer_block;
    }

    if (val < 10) {
      switch(val) {
        case 1:
          result = "One";
          break outer_block;
        case 2:
          let temp = await complexCompute(2);
          if (temp > val) {
            result = "Two Modified";
            break outer_block;
          }
          result = "Two";
          break outer_block;
      }
    }

    result = "Out of scope";
  }

  return result;
}

async function main() {
  let res = await func1();
  console.log(res);
}

main();
```

### Config

```json

```

### Link to the code that reproduces this issue

https://play.swc.rs/?version=1.13.5&code=H4sIAAAAAAAAA41Sy07DMBC85yuWnhyEaFKJS0N74czjUHFFrrspVv2oYrsB0fw7dpLmUaAiB8frjGdnJ0PNp2KQO8Us1wqYlnuBHw%2F%2B5SwS5WQMXxFAgdYVChSW8FJoyQ2SAo0WB4TFskYAGLQrLlE7S0jcH4fLNTKwwTXM4qw%2Br25gliRJXVV%2BraKIjsWETUoaAQJt4HHCZm11oAIWkGYwnQJX3HJfU2P4VklU1oMaQFiPR6Al5fZ8vDvf1gO9Yize1kKz3bwVzXMgV%2F5qPBzCN%2FeEkycNr1Q4nGTtp3WBdDdkaQeMOqog4h7SpKczJbfsnYxaADBqENJ5Vw%2FbPqu%2B44WuHc1sSBMMsyj3nuhXJ04%2FpXmC5Bq9hDOBY0mrUsOj3vCc42ak7aK64MwfbP8bsBraOzDIWdA5GKb3jVM1ok3uKTs%2FUyYpV%2BOQdSa1AQxcTCsfYrwVehuS3%2BS1uZp9A22I9IVEAwAA&config=H4sIAAAAAAAAA1WPSQ6DMAxF95wi8pptu%2BgdOIQVDArKpDiVGiHu3pCBll38%2F7Ofsg9CwMYSXmLPzzx4DEzhmnPCyUb85ARIGmQZlI8w9nbjs1pQM5XoqA1EDCvFssWPhoN2jqnjLTPKqiX9C6UzPhDzHTxRtKumu25oSjBufpeyfSQmT1X%2FhB%2FUZddhUDz1zXr2%2BAIDhbm2FQEAAA%3D%3D

### SWC Info output

_No response_

### Expected behavior

SWC's ES5 output should print: `One`

### Actual behavior

But, it prints: `Out of scope`

### Version

1.13.5

### Additional context

_No response_

### LINKED ISSUE #11052: ES5 async method transform drops write-back for compound assignment to this property across await
### Describe the bug

Inside an async class method, `this._value += ' ' + await this.fetchMoreData()` is compiled into temporaries `_2 = _1._value; _2 += ...` without assigning the result back to `this._value`. The write-back is lost, so only the first assignment is observed. Node.js and Babel preserve the compound assignment correctly.

### Input code

```js
class MyClass {
    constructor() {
        this._value = null;
    }

    async fetchData() {
        return new Promise(resolve => {
            setTimeout(() => {
                resolve('Data fetched');
            }, 10);
        });
    }

    async fetchMoreData() {
        return new Promise(resolve => {
            setTimeout(() => {
                resolve('More data fetched');
            }, 10);
        });
    }
    async initializeData() {
        this._value = await this.fetchData();
        this._value += ' ' + await this.fetchMoreData();
    }
    get value() {
        return this._value;
    }
    set value(newValue) {
        this._value = newValue;
    }
}
async function func1() {
    let myClass = new MyClass();
    await myClass.initializeData();
    return myClass.value;
}
async function main() {
    let res = await func1();
    console.log(res);
}
main();
```

### Config

```json

```

### Link to the code that reproduces this issue

https://play.swc.rs/?version=1.13.5&code=H4sIAAAAAAAAA71TPWvDMBDd8ytus02KaWaTLu0ayFC6FqFcE4EsgXRKSIv%2Fe%2FVl16rTLoWeBwnpvXdPd2cumbWwuz7G9WMFPrhWlozjpE3d5LMQdBK2fT0z6RC2oJyUXbwbVnFh9qo4vCHx0xMjVlANkjMKFF5gb3QvLNYGrZZnr%2FQww4WwSM%2BiR%2B2o9hqL6yQXuXUVEqWUeKiargAOd7C5n50NzU92d9rgv1kOyeDwV99CCRJMivel8bJN7MIEpbNZa7qb6PUWKv%2BtF6SvAhVWjkgQmbcKNxMuSHYi%2BdK%2BhM0vM5YRo4CXyG1zipPQKm42U3rptfs8y5E9TvZoPD0sQ9rvRUyY7H8E5RcsU%2FdMqCKzb%2FFU8Oyrm34oLbGV%2BhhmqIlqid59AkEytomBAwAA&config=H4sIAAAAAAAAA1WPSQ6DMAxF95wi8pptu%2BgdOIQVDArKpDiVGiHu3pCBll38%2F7Ofsg9CwMYSXmLPzzx4DEzhmnPCyUb85ARIGmQZlI8w9nbjs1pQM5XoqA1EDCvFssWPhoN2jqnjLTPKqiX9C6UzPhDzHTxRtKumu25oSjBufpeyfSQmT1X%2FhB%2FUZddhUDz1zXr2%2BAIDhbm2FQEAAA%3D%3D

### SWC Info output

_No response_

### Expected behavior

SWC's ES5 output should print both assignments: `Data fetched More data fetched`

### Actual behavior

But, it currently prints: `Data fetched`

### Version

1.13.5

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
- Closes #5433
- Closes #11046
- Closes #11047
- Closes #11048
- Closes #11049
- Closes #11050
- Closes #11052

### CODE REVIEW

**Comment by kdy1** [comment]
Wow... I'll review your PRs after the trip. Sorry for the delay.

File: packages/helpers/esm/_ts_generator.js [hunk 1]
```diff
@@ -1 +1,29 @@
-export { __generator as _ } from "tslib";
+function _ts_generator(thisArg, body) {
```
Comment (kdy1) [inline packages/helpers/esm/_ts_generator.js:1]: Is this change intentional? Why did you change this?
Also, can you path the one in `swc_ecma_transforms_base`, too?

Comment (magic-akari) [reply packages/helpers/esm/_ts_generator.js:1]: Yes, this change is intentional and necessary to fix issue #11046 (similar to #5433). 

The core issue requires modifying the `_ts_generator` helper implementation. Specifically, we need to use `Object.defineProperty` instead of direct property assignment when defining the generator methods (`next`, `throw`, `return`, and `Symbol.iterator`). 
This is similar to the situation we encountered with issue #5433. We reported this to the TypeScript team (see [microsoft/TypeScript#50263](https://github.com/microsoft/TypeScript/issues/50263)), but they declined to fix it in tslib. 

Therefore, we had to fork the `_ts_generator` helper and maintain our own version with the necessary fix. 

Regarding your second question: I've already updated the one in swc_ecma_transforms_base as well (you can see it in swc_ecma_transforms_base/src/helpers/_ts_generator.js.)
https://github.com/swc-project/swc/blob/5a16770449bdf80338eb32c192e60c9ef99c7010/crates/swc_ecma_transforms_base/src/helpers/_ts_generator.js#L1-L27

 Both versions now use `Object.defineProperty` for proper property definition.

**Review by kdy1 — APPROVED** [review]
