### PR TITLE
fix(es/minifier): Abort seq inliner if a same var is defined in outer scope

### LINKED ISSUE #7749: Minify changes the order of statements
### Describe the bug

The input code below, visit function accesses variable depth, however after minified, the depth becomes 0 when visit gets invoked

### Input code

```typescript
let depth = 0;

function foo(n) {
  depth += 1;
  let k = visit(n);
  depth -= 1;
  return k;
}

blackbox(foo)
```

### Config

```json
{
  "jsc": {
    "externalHelpers": true,
    "parser": {
      "tsx": true,
      "syntax": "typescript",
    },
    "target": "es2020",
    "minify": {
      "compress": {}
    },
  },
}
```

### Playground link

https://play.swc.rs/?version=1.3.72&code=H4sIAAAAAAAAA8tJLVFISS0oyVCwVTCw5uJKK81LLsnMz1NIy8%2FXyNNUqOZSgMpr2yoYWgN5OUAd2UDVZZnFmSVAJdZwFbpQFUWpJaVFeQrZ1ly1XFxJOYnJ2Un5FRpAAzUBjCI5XG4AAAA%3D&config=H4sIAAAAAAAAA32US27jMAxA93OKwOsuii7nAEVvISgW5agji4JIJTGK3L2UbaSdhPYmcPj4Eb9ffw6H7pP67u%2FhSz7lD1wZSrLxA2KGQgK4VHhZYLaFoNyVRcJ0%2FU9FRDQltk3a8ZSB%2BhIydwu9rX7YlgG4qQC9vb69rrgbQwp%2B%2Bu2%2FxzEXIPolE6mY1xESN7G3ke7BZ1bwQg%2BPEvkRMYJNO8RYMiExDEvej457jNFmAnO2RfHSXmpLINRCNFgZnMkFs8qTCxxQCq9QB9aZHh0oKBToOZxBM5NYYpZI0lPymbGDYx2GuacP1nC2sVpWYsJ1bom8VvF6wkBsfE1aCRe4UYMFrsV9tAzeFOBa0rPdJ4a00ZN%2FAFKBaImSHUHzO2t4macta79rGZKXkeVJ4RHVLBMMUlQTglcq2yoDhYPWzQKu9tAq22vPWfFG%2BSg4MOC9zIrimi6B%2B5MWtG0wegVIf63XpmoB5r6FG7wtxA5%2BlyxZH7BVY7R82qY0jUeMOwFG4BO6HQVpBeM2LnIlrnmb1%2BRARgOcqlJpBs9HQBaA0cT5Nj7NhqyHeDRDxOPPmVgVbj%2F3VX5u3%2Bzl52fYBQAA

### Expected behavior

depth += 1;
let k = visit(n);
depth -= 1;
return k

### Actual behavior

return depth += 1, depth -= 1, visit(n);

### Version

1.3.72

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

The algorithm here is directly copied from terser, I don't if it's correct or can be improved, but it does fixes the issue.

**Related issue:**

 - Closes #7749

### CODE REVIEW

File: crates/swc_ecma_minifier/src/compress/optimize/iife.rs [hunk 1]
```diff
@@ -869,9 +869,21 @@ impl Optimizer<'_> {
...
+                            if let Some(usage) = self.data.vars.get(&id) {
+                                let mut usage = usage.clone();
+                                usage.in_fn_scope = self.ctx.fn_scope;
+                                // as we turn var declaration into assignment
+                                // we need to maintain correct var usage
+                                if decl.init.is_some() {
+                                    usage.ref_count += 1;
+                                }
+                                self.data.vars.insert((id.0, *ctx), usage);
+                            }
```
Comment (Austaras) [inline crates/swc_ecma_minifier/src/compress/optimize/iife.rs:886]: The improvement of output come from here.

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_utils

**Review by jridgewell — APPROVED** [review]

**Review by kdy1 — COMMENTED** [review]
reset ci
