### PR TITLE
fix(es/transforms/cjs): bind reassign scope to default export fn

### LINKED ISSUE #2678: does not allow reassign ref to default exported fn
### Describe the bug

- Followup edge cases for https://github.com/swc-project/swc/issues/2549, https://github.com/swc-project/swc/issues/2606

When an function is async, default exported it does not reassign its ref to export as similar to original #2549 does.

### Input code

```typescript
export default function someCall() {
  region();
}

export const text = {};
Object.defineProperty(test, 'someCall', {
  set: (v) => {
    someCall = v;
  }
})
```

### Config

```json
{
  "jsc": {
    "target": "es2017"
  },
  "module": {
    "type": "commonjs",
    "noInterop": false
  },
  "env": {
    "targets": {
      "node": 14
    },
    "include": ["transform-async-to-generator"]
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.106&code=H4sIAAAAAAAAAz2NQQrCMBBF94Hc4e%2BaQPEAlrrxAHqFGqdSiUlJpqVScndHgm7f579H2xwT407jsHjGuATHUwzI8UXnwXtjsWsFJHoINrbTqmilFdWfiyEzmDZGj73Ierk9yfFBhFOga4ozJX4bpswtmp%2B1aas1Ex9hVov%2BVAH%2BYfGt3RdJrtgP6sRtQKcAAAA%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1Fm2hXeQOPYRxleDgHxoFGozvXju4ZCfNPD0V2mBpLpSNgKVPOKKaL82kR2ZYcVlpIkWLFuPBtS1GVtaGMB63%2B7PVPiXwACYKLrrl6DKbQhYGrsrE1f%2FJ2lwhffYelPPf6XxRvRzjzuE9QJWd6w%2ByirtzuAAAAA%3D%3D

### Expected behavior

Same as #2549, #2606, expect to get reassign like 

```
  set: (v) => {
	exports.someCall = someCall = v;
  }

```

### Version

1.2.106 (and potentially master TOT)

### Additional context

- Looks like potentially related to https://github.com/swc-project/swc/issues/2677 , but for now separating issue until we can triage if it shares same root cause.

### PR DESCRIPTION
**Pull request by kwonoj**
- closes #2678 

This PR attempt to fix #2678, one of the edge cases of #2549.

As same as fix for #2549, this PR sets scope to the exported. The only difference is it doesn't set scope to name of the declaration (or FnExpr's) as default export uses fixed name `default` for the export. Given current fold already creates default export member expr, reuses created one to assign into scope.

### CODE REVIEW

File: ecmascript/transforms/module/src/common_js.rs [hunk 1]
```diff
@@ -372,6 +372,28 @@ where
                                     // init_export!("default");
                                     let ident = ident.unwrap_or_else(|| private_ident!("_default"));
 
+                                    let member_expr = member_expr!(DUMMY_SP, exports.default);
+                                    match &*member_expr {
```
Comment (kdy1) [inline ecmascript/transforms/module/src/common_js.rs:376]: As value of `member_expr` is known, I think this can be improved for better readability.

File: ecmascript/transforms/module/src/common_js.rs [hunk 2]
```diff
@@ -372,6 +372,28 @@ where
...
+                                                        default_ident.span.ctxt(),
+                                                    ));
+
+                                                drop(scope);
+                                            }
+                                            _ => (),
+                                        },
+                                        _ => (),
+                                    }
+
```
Comment (kdy1) [inline ecmascript/transforms/module/src/common_js.rs:396]:
```rust
{
        let mut scope = self.scope.borrow_mut();

        scope
            .exported_bindings
            .entry((ident.sym.clone(), ident.span.ctxt()))
            .or_default()
            .push((js_word!("default"), Default::default()));
    }
}
```

will work.

Note that it's wrapped in `{` and `}` to make `scope` dropped.

**Review by kdy1 — CHANGES_REQUESTED** [review]
Thanks!

File: ecmascript/transforms/module/src/common_js.rs (hunk 1 above)
Comment (kwonoj) [reply ecmascript/transforms/module/src/common_js.rs]: Good point, thanks. maybe this works? https://github.com/swc-project/swc/pull/2705/files#diff-506530d02689c3c49a06cbec6fb8c9ffd7b1df4c551dcac29d8bd08d0248590fR380

**Review by kdy1 — APPROVED** [review]
Thanks!

File: ecmascript/transforms/module/src/common_js.rs (hunk 1 above)
Comment (kdy1) [reply ecmascript/transforms/module/src/common_js.rs]: Yes, thanks!
