### PR TITLE
fix(es/async_to_generator): Do not bind `this` to generator for prototype

### LINKED ISSUE #2305: async function error
**Describe the bug**
async/await error

**Input code**
```js
function MyClass () {}

MyClass.prototype.handle = function () {
    console.log('this is MyClass handle')
}

MyClass.prototype.init = async function(param1) {
    const a = 1;

    if (!param1) {
        console.log(this)
        this.handle()
    }

    if (param1 === a) {
        return false
    }

    return true
}

const myclass = new MyClass()
myclass.handle()
myclass.init()
```

**Config**
none

```json
{
    "env": {
        "targets": {
            "chrome": "42"
        }
    }
}
```

**Expected behavior**
```
// log is:
this is MyClass handle
MyClass {}
this is MyClass handle
```

**Version**
The version of @swc/core:
v1.2.91

**Additional context**
no

### LINKED ISSUE #2402: Async functions cause loss of scope
**Describe the bug**

Seems like when an async function in a class, the runtime loses its scope because it creates a new scoped function with the code on transpilation. Also a problem when I use a ES6+ `class` declaration.

Link to [REPL](https://swc.rs/repl/#%7B%22rawCode%22%3A%22function%20MyClass(item)%20%7B%5Cn%20%20this.item%20%3D%20item%3B%5Cn%20%20console.log(%5C%22Constructor%20%7C%20this.item%5C%22%2C%20this.item)%3B%5Cn%7D%5Cn%5CnMyClass.prototype.fun%20%3D%20async%20function%20fun()%20%7B%5Cn%20%20console.log(%5C%22fun%20%7C%20this.item%5C%22%2C%20this.item)%3B%5Cn%20%20return%20this.item%3B%5Cn%7D%3B%5Cn%5Cn%2F%2F%20const%20tmp%20%3D%20new%20MyClass(%7B%20foo%3A%20%5C%22bar%5C%22%20%7D)%3B%5Cn%5Cn%2F%2F%20tmp.fun().then((res)%20%3D%3E%20%7B%5Cn%2F%2F%20%20%20console.log(%5C%22fun%20result%20%7C%20item%5C%22%2C%20res)%3B%5Cn%2F%2F%20%7D)%3B%5Cn%5Cnclass%20MyNewClass%20%7B%5Cn%20%20constructor(item)%20%7B%5Cn%20%20%20%20this.item%20%3D%20item%3B%5Cn%20%20%20%20console.log(%5C%22Constructor%20%7C%20this.item%5C%22%2C%20this.item)%3B%5Cn%20%20%7D%5Cn%5Cn%20%20async%20fun()%20%7B%5Cn%20%20%20%20console.log(%5C%22fun%20%7C%20this.item%5C%22%2C%20this.item)%3B%5Cn%20%20%20%20return%20this.item%3B%5Cn%20%20%7D%5Cn%7D%5Cn%5Cnconst%20tmp2%20%3D%20new%20MyClass(%7B%20foo%3A%20%5C%22bar%5C%22%20%7D)%3B%5Cn%5Cntmp2.fun().then((res)%20%3D%3E%20%7B%5Cn%20%20console.log(%5C%22fun%20result%20%7C%20item%5C%22%2C%20res)%3B%5Cn%7D)%3B%5Cn%22%2C%22rawConfig%22%3A%22%7B%5C%22jsc%5C%22%3A%20%7B%5C%22target%5C%22%3A%20%5C%22es2016%5C%22%7D%7D%22%7D)

**Input code**

```js
function MyClass(item) {
  this.item = item;
  console.log("Constructor | this.item", this.item);
}

MyClass.prototype.fun = async function fun() {
  console.log("fun | this.item", this.item);
  return this.item;
};

const tmp = new MyClass({ foo: "bar" });

tmp.fun().then((res) => {
  console.log("fun result | item", res);
});
```

**Config**

```json
{ "jsc": { "target": "es2016" } }
```

**Expected behavior**

I expect the value to be returned/logged throughout the program.

Here's the output of the source

```
❯ node modern.js
Constructor | this.item { foo: 'bar' }
fun | this.item { foo: 'bar' }
fun result | item { foo: 'bar' }
```

Here's the output of the transpiled version

```
❯ node swc.js                                    
Constructor | this.item { foo: 'bar' }
fun | this.item undefined
fun result | item undefined
```

**Version**
The version of @swc/core: `1.2.95` (but I am mainly using the REPL to replicate this issue)

**Additional context**

### PR DESCRIPTION
**Pull request by kwonoj**
Attempt to close
- Closes #2402 
- Closes #2305 

This PR attempts to amend behavior around generator for the async fn to avoid bind to `this` context if given async fn is assignment to prototype. There was some other approach suggestion like https://github.com/swc-project/swc/issues/2305#issuecomment-927588761 , but doesn't seem to work as issue is prototype doesn't have proper context to attach from beginning.

As similar to existing flag `in_object_prop`, this PR introduces new flag `in_prototype_assignment` to indicate if given assign expr is for the prototype.

### CODE REVIEW

File: ecmascript/transforms/compat/src/es2017/async_to_generator.rs [hunk 1]
```diff
@@ -211,6 +213,35 @@ impl Fold for Actual {
...
 
+            Expr::Assign(assign_expr) => {
+                // flag if expression is assignment to prototype chain should not try to bind
+                // this context
+                match &assign_expr.left {
+                    PatOrExpr::Pat(pat) => match &**pat {
+                        Pat::Expr(pat_expr) => match &**pat_expr {
+                            Expr::Member(MemberExpr {
+                                obj: ExprOrSuper::Expr(ex),
+                                ..
```
Comment (kdy1) [inline ecmascript/transforms/compat/src/es2017/async_to_generator.rs:224]: I think `computed: false` is required.

File: ecmascript/transforms/compat/src/es2017/async_to_generator.rs [hunk 2]
```diff
@@ -211,6 +213,35 @@ impl Fold for Actual {
...
+                            }) => match &**ex {
+                                Expr::Member(MemberExpr { prop, .. }) => match &**prop {
```
Comment (kdy1) [inline ecmascript/transforms/compat/src/es2017/async_to_generator.rs:226]: Same here, as `a.f[prototype]` is different from `a.f.prototype`.
(I don't think someone to write such code, but it's not correct anyway.

**Review by kdy1 — APPROVED** [review]
Thanks!
Btw, how did you remove trailing whitespaces?
I'm asking it because I want to apply it to the whole repository.

**Review by kdy1 — CHANGES_REQUESTED** [review]
Thanks!
Btw, how did you remove trailing whitespaces?
I'm asking it because I want to apply it to the whole repository.


Sorry, I mistakenly clicked approve.

**Comment by kwonoj** [comment]
> Btw, how did you remove trailing whitespaces?

Afaik it's from my editor's config which explains why it applies only for the files I touched. I think there maybe way to apply this into all of the files, let me try to peek.

File: ecmascript/transforms/compat/src/es2017/async_to_generator.rs (hunk 1 above)
Comment (kwonoj) [reply ecmascript/transforms/compat/src/es2017/async_to_generator.rs:225]: added check for the property (https://github.com/swc-project/swc/pull/2667/files#diff-3e3528801f0642de9a7612e339d4ba8958e38dac96a90d6c972aa8f49769a363R226), is this correct understanding?

Comment (kdy1) [reply ecmascript/transforms/compat/src/es2017/async_to_generator.rs:225]: You can use like 

```rust

match &**pat_expr {
     Expr::Member(MemberExpr {
         obj: ExprOrSuper::Expr(ex),
         computed: false,
         ..
     }) => {}
}
```

instead

File: ecmascript/transforms/compat/src/es2017/async_to_generator.rs [hunk 3]
```diff
@@ -211,6 +213,39 @@ impl Fold for Actual {
...
+                match &assign_expr.left {
+                    PatOrExpr::Pat(pat) => match &**pat {
+                        Pat::Expr(pat_expr) => match &**pat_expr {
+                            Expr::Member(MemberExpr {
+                                obj: ExprOrSuper::Expr(ex),
+                                computed,
+                                ..
+                            }) if !computed => match &**ex {
+                                Expr::Member(MemberExpr { prop, computed, .. }) if !computed => {
+                                    match &**prop {
```
Comment (kdy1) [inline ecmascript/transforms/compat/src/es2017/async_to_generator.rs:228]: Same here.

**Review by kdy1 — CHANGES_REQUESTED** [review]
Thanks! I think if guards are not required at here.

File: ecmascript/transforms/compat/src/es2017/async_to_generator.rs (hunk 1 above)
Comment (kwonoj) [reply ecmascript/transforms/compat/src/es2017/async_to_generator.rs:225]: oh thansk. :facepalm: updated!

**Review by kdy1 — APPROVED** [review]
Thanks!
