### PR TITLE
fix: accept both keep_fnames and keep_classnames in jsc minify options

### LINKED ISSUE #6996: JsMinifyOptions.keep_fnames throws unknown field
### Describe the bug

```
Error: unknown field `keep_fnames`, expected one of `compress`, `mangle`, `format`, `ecma`, `keepClassnames`, `keepFnames`, `module`, `safari10`, `toplevel`, `sourceMap`, `outputPath`, `inlineSourcesContent`, `emitSourceMapColumns` at line 1 column 794
```

### Input code

_No response_

### Config

```json
{ "minify": { "keep_fnames": true } }
```

### Playground link

_No response_

### Expected behavior

recognizes JsMinifyOptions.keep_fnames to be compatible with TerserOptions, or correct the property name in https://github.com/swc-project/swc/blob/main/node-swc/src/types.ts#L17 perhaps

### Actual behavior

_No response_

### Version

1.3.36

### Additional context

payground prompts `keepFnames`, hence it's working properly

### PR DESCRIPTION
**Pull request by cyjake**
**Description:**

att, closes #6996

**BREAKING CHANGE:**

this change is backward compatible

**Related issue (if exists):**

https://github.com/swc-project/swc/issues/6996

### CODE REVIEW

File: node-swc/__tests__/minify/issue_6996_test.mjs [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+            jsc: {
+                minify: {
+                    keep_fnames: true,
+                },
+            },
+        });
+        return code;
+    }
+    await expect(minify()).resolves.toEqual('function Foo() {}\n');
+});
```
Comment (cyjake) [inline node-swc/__tests__/minify/issue_6996_test.mjs:15]: it seems binding tests is done with published swc_core. I've changed local bindings/binding_core_node/Cargo.toml to have this test case covered, but the CI might fail because of this. Should the Cargo.toml be updated as well?

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc
