### PR TITLE
fix(es/parser): Fix parsing of `>` in typescript mode

### LINKED ISSUE #7403: TypeScript: `x < y >>>= z` is incorrectly interpreted as a type argument list
### Describe the bug

SWC's interpretation of type arguments in TypeScript code is different than the TypeScript compiler, which can cause SWC to generate incorrect JavaScript.

This is a follow-up to https://github.com/swc-project/swc/issues/7387, which was not fixed correctly.

### Input code

```typescript
declare let fn: any, x: any, y: any
declare function z<A, B>(_: any): any
fn(z < Number, Object > (y))
fn(z < Number, Object > = y)
fn(x < y, x > y)
fn(x < y, x >= y)
fn(x < y, x >> y)
fn(x < y, x >>= y)
fn(x < y, x >>>= y)
fn(x < y, x < y, x >>= y)
fn(x < y, x < y, x >>> y)
fn(x < y, x < y, x >>>= y)
```

### Config

```json
(I only ran SWC via the playground)
```

### Playground link

https://play.swc.rs/?version=1.3.58&code=H4sIAAAAAAAAA0tJTc5JLEpVyEktUUjLs1JIzKvUUaiA0pVgmisFqiatNC%2B5JDM%2FT6HKxlFHwclOIx4srwlRlZanUaVgo%2BBXmpuUWqSj4J%2BUlZpcomCnoFGpqYlT0lahEixZAZQEWQwUQhfAVIKpBpsiTDHcqhGacMuANQEAPpF21y8BAAA%3D&config=H4sIAAAAAAAAA1VPOw7DIAzdOQXy3CHK0KF36CEQdSIqfsKOVBTl7oUE0maz38fveRVSwps0PORaxrJElQjTuReEsmf1KQhwjkg6mchw6yxTpSZlCXdoOxhglWbk6kIah3FoDrAhEHZHw5zxZsr%2FmTq4mJDoKqxS5WeL10TRUsGF17KT7Zfa92hwh5%2Boh52HwdCzOzktKLYvIO%2B2AhcBAAA%3D

### Expected behavior

SWC should generate the same output as [the TypeScript compiler does](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEEQBd4DMB2AueUME8AaeADxzyPn3IIChRJYE0BXDMZASwHsN4AvADwBBYgCEAfAAoA+jXwBKebUxT+8QfAByLALYAjEDGIB5fQCtwqCfCmKFKjGo3a9h4-DOWO8GwF4qB1USF0oQm0VHKRDNMN8AyODQ4nCIoKcYqhTfCQT06OTSHNzAqMy42OyJEsSMwvKq6tKkyqLW1JqHIA):

```js
fn(z(y));
fn((z) = y);
fn(x < y, x > y);
fn(x < y, x >= y);
fn(x < y, x >> y);
fn(x < y, x >>= y);
fn(x < y, x >>>= y);
fn(x < y, x < y, x >>= y);
fn(x < y, x < y, x >>> y);
fn(x < y, x < y, x >>>= y);
```

### Actual behavior

Starting with version 1.3.58, SWC fails to parse this code with a syntax error (due to the incorrect fix for https://github.com/swc-project/swc/issues/7387):

```
  x Expression expected
   ,-[input.ts:1:1]
 4 | fn(z < Number, Object > = y)
   :                         ^
```

This syntax error is a regression from 1.3.57.

And if that line is commented out, SWC still incorrectly transforms `fn(x < y, x >>>= y)` into `fn(x >>= y)` and `fn(x < y, x < y, x >>>= y)` into `fn(x < y, x >>= y)`.

### Version

1.3.58

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

**Related issue:**

 - Closes #7403.

### CODE REVIEW

File: crates/swc_ecma_parser/tests/typescript/issue-7403/10/input.ts.json [hunk 1]
```diff
@@ -0,0 +1,160 @@
+{
```
Comment (kdy1) [inline crates/swc_ecma_parser/tests/typescript/issue-7403/10/input.ts.json:1]: This is wrong

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_parser
