### PR TITLE
fix(es/compat): Fix loose mode of the `spread` pass

### LINKED ISSUE #7354: spread syntax differs between swc loose mode and babel loose mode
### Describe the bug

I'm migrating my code's compiler from babel to swc, and my code crashed because the generated code with loose config is kind of different from babel.
Code contains es spread syntax. While babel with loose config removes all TypeError and other stuff, swc with loose config remains the same as non-loose config. TypeError is the key reason of my code crash.

### Input code

```typescript
const data = {}
const temp  = [...data.demo, ...data.demo2]
```

### Config

_No response_

### Playground link

**babel**
https://babeljs.io/repl#?browsers=&build=&builtIns=false&corejs=3.21&spec=false&loose=true&code_lz=MYewdgzgLgBAJgQygmBeGBvAvgKFJWKAUwFsAHGNGAbQDp7Fla5SQAaGe5pBZ1gJgC6QA&debug=false&forceAllTransforms=false&modules=commonjs&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.21.8&externalPlugins=&assumptions=%7B%7D 
**swc**
 https://play.swc.rs/?version=1.3.56&code=H4sIAAAAAAAAA0vOzysuUUhJLElUsFWoruVKBvNLUnMLFIAC0Xp6eiA5vZTU3HwdBWSeUSwALJOS2TsAAAA%3D&config=H4sIAAAAAAAAA1WPPQ7DIAxGd06BPHdth94hh7CoExHxJ0ykoih3LyFA2w2%2Fz%2FYzu5ASVlbwlHt5liJgZIqjLoSzS%2FguBEhZZBV1SHDr6cpnNKNhqui4EkgYF0p1iu%2BtHYz3TIWluFFDVjs951%2Bf8jZEYu5rh8qiWwz920QzgvWvrYbtHykHuuwP%2BDZ12VgMmqc%2BeV4ljg%2F3WmjeEwEAAA%3D%3D

### Expected behavior

Using es spread syntax in loose config, swc behaves the same as babel.

### Actual behavior

_No response_

### Version

@swc/core: 1.3.56 @babel/core: 7.21.8

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by lsdyi**
**Description:**

**Related issue:** 
- Closes #7354

### CODE REVIEW

**Comment by lsdyi** [comment]
@Kaciras Sorry to push code without tests. I'm new to this repo🥹, kind of confused where I can complete whole testing process. I noticed we can write `input/index.js` and `inpuit/.swcrc` which I think are input example, but I'm confused how I can generate output, which is `output/index.js`

**Comment by kdy1** [comment]
You can do `UPDATE=1 cargo test`

**Comment by kdy1** [comment]
Also, can you sign the CLA?

**Comment by kdy1** [comment]
CI is failing. You can update snapshots with `UPDATE=1 cargo test`

**Comment by lsdyi** [comment]
>

**Comment by lsdyi** [comment]
@kdy1 Thank you for the reminder. I'm

**Comment by lsdyi** [comment]
Hello @kdy1 , I update the testing file and snapshots. Could you please help me check the code?

File: crates/swc_ecma_transforms_compat/src/es2015/spread.rs [hunk 1]
```diff
@@ -251,9 +251,11 @@ impl Spread {
             };
         }
 
+        let mut arg_list = vec![];
         for arg in args {
             if let Some(arg) = arg {
                 let ExprOrSpread { expr, spread } = arg;
+                arg_list.push(expr.clone().as_arg());
```
Comment (kdy1) [inline crates/swc_ecma_transforms_compat/src/es2015/spread.rs:258]: This clone seems redundant.

**Review by kdy1 — CHANGES_REQUESTED** [review]

File: crates/swc_ecma_transforms_compat/src/es2015/spread.rs (hunk 1 above)
Comment (lsdyi) [reply crates/swc_ecma_transforms_compat/src/es2015/spread.rs:258]: `expr`used without `clone`method will cause `use of moved value` error in next `*expr` location.

--- 
Error  stack  is as follows.
```shell
error[E0382]: use of moved value: `*expr`
   --> crates/swc_ecma_transforms_compat/src/es2015/spread.rs:286:34
    |
258 |                 arg_list.push(expr.as_arg());
    |                                    -------- `*expr` moved due to this method call
...
286 |                         buf.push(match *expr {
    |                                  ^^^^^^^^^^^ value used here after move
    |
    = note: move occurs because `*expr` has type `swc_ecma_ast::Expr`, which does not implement the `Copy` trait
help: you can `clone` the value and consume it, but this might not be your desired behavior
    |
258 |                 arg_list.push(expr.clone().as_arg());
    |                                    ++++++++

For more information about this error, try `rustc --explain E0382`.
error: could not compile `swc_ecma_transforms_compat` (lib) due to previous error
```
---
```shell
$ rustc --version
rustc 1.70.0-nightly (da7c50c08 2023-03-19)
```

**Comment by lsdyi** [comment]
Thanks for the CR yesterday @kdy1 , is there anything I can do with this PR?

**Comment by kdy1** [comment]
Please remove the redundant clone. It's removable

**Comment by lsdyi** [comment]
Good afternoon ☕️ @kdy1  I've removed the redundant `clone()` method and collected list elements in a specific new `for loop`. Could you please help me check whether the code meets expectation?

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_ecma_transforms_compat
