### PR TITLE
fix(es/module): Private context for `export from`

### LINKED ISSUE #5260: Imports with the same name exported with different names map to incorrect modules
### Describe the bug

Wasn't able to find an existing issue, lmk if it's a duplicate: 

If two imports have the same export (e.g. A) and it gets renamed during the export (`export { A as Aa }`) then the compiled code incorrectly maps all the requires to one of the modules. See playground and below!

Note that this doesn't seem to happen for the export `default` - only named exports.

### Input code

```typescript
export { A as Aa } from 'a';
export { A as Ab } from 'b';
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2020",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.218&code=H4sIAAAAAAAAA0utKMgvKlGoVnBUSCxWcExUqFVIK8rPVVBPVLfmSkWVTIJLJqlbAwAkJ3d%2BOQAAAA%3D%3D&config=H4sIAAAAAAAAA0WNSwrDMAxE76J1FiHL3KGHMK4SHPxD40CN8d0rF5fsJM2bp0YXLO2NshGwjAk1FvOhnUrNDCsuF1qoQE%2BH8eCui5GTiyKMbd1WjX1K4AksFFx0Rx0ym0IWBp7IxNP%2Fya6ukN73OLTfP3VqJaR4gfojmmWH16SL3Ny%2F3SauU70AAAA%3D

### Expected behavior

```js
_export(exports, {
    Aa: ()=>_a.A,
    Ab: ()=>_b.A
});
const _a = require("a");
const _b = require("b");
```

### Actual behavior

```js
_export(exports, {
    Aa: ()=>_b.A,
    Ab: ()=>_b.A
});
const _a = require("a");
const _b = require("b");
```

### Version

1.2.218

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
- fix #5260

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_common
 - swc_ecma_transforms_module

File: crates/swc_ecma_transforms_module/src/module_decl_strip.rs [hunk 1]
```diff
@@ -455,14 +455,14 @@ impl From<ExportSpecifier> for LinkSpecifier {
...
-                    }) => (sym, span),
+                    }) => (sym, span.private()),
                 };
 
                 let exported = exported.map(|exported| match exported {
                     ModuleExportName::Ident(Ident { span, sym, .. })
                     | ModuleExportName::Str(Str {
                         span, value: sym, ..
-                    }) => (sym, span),
+                    }) => (sym, span.private()),
```
Comment (magic-akari) [inline crates/swc_ecma_transforms_module/src/module_decl_strip.rs:465]: I think it's safe not to make `exported` private.

**Comment by abrenneke** [comment]
Thank you for the quick fix @magic-akari! 🚀
