### PR TITLE
feat(es/module): Preserve custom `use` directives

### LINKED ISSUE #7315: Directive not preserved for commonjs
### Describe the bug

```
// input.ts
"use client"

export function ReactClientComponent() {
    return "Hello world"
}
```

`swc input.ts -o output.js -C module.type=commonjs`

```
// output.js
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "ReactClientComponent", {
    enumerable: true,
    get: function() {
        return ReactClientComponent;
    }
});
"use client";
function ReactClientComponent() {
    return "Hello world";
}
```

Notice how `"use client"` is underneath the helpers generated by swc, which doesn't work with Next.js, which expects `"use client"` to come before any expressions.

Related to https://github.com/swc-project/swc/issues/6508

### Input code

_No response_

### Config

_No response_

### Playground link

_No response_

### Expected behavior

`"use client"` should be either 1 line above or below `"use strict"`. I believe either is acceptable for Next.js.

```
// output.js
"use client";
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "ReactClientComponent", {
    enumerable: true,
    get: function() {
        return ReactClientComponent;
    }
});
function ReactClientComponent() {
    return "Hello world";
}
```

### Actual behavior

_No response_

### Version

@swc/cli: 0.1.62 @swc/core: 1.3.53

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

**Related issue:**

 - Closes #7315.

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_utils

File: crates/swc/tests/fixture/issues-7xxx/7315/1/output/index.js [hunk 1]
```diff
@@ -0,0 +1,14 @@
+// input.ts
+"use client";
```
Comment (magic-akari) [inline crates/swc/tests/fixture/issues-7xxx/7315/1/output/index.js:2]: I believe that `"use strict"` is also necessary.

Comment (kdy1) [reply crates/swc/tests/fixture/issues-7xxx/7315/1/output/index.js:2]: Does it have any effect? Hmm

Comment (kdy1) [reply crates/swc/tests/fixture/issues-7xxx/7315/1/output/index.js:2]: AFAIK, The only first directive has an effect.

Comment (magic-akari) [reply crates/swc/tests/fixture/issues-7xxx/7315/1/output/index.js:2]: continuous directives will be recognized in Babel.

https://github.com/babel/babel/blob/980b63c829de369ace21461d3268d04bb80fc380/packages/babel-parser/test/fixtures/estree/directives/program-order/input.js

Comment (magic-akari) [reply crates/swc/tests/fixture/issues-7xxx/7315/1/output/index.js:2]: And all valid directive will be parsed as directive before first `non directive`.

https://github.com/babel/babel/blob/980b63c829de369ace21461d3268d04bb80fc380/packages/babel-parser/src/parser/statement.ts#L1403-L1430

File: crates/swc_ecma_transforms_module/src/amd.rs [hunk 2]
```diff
@@ -145,7 +145,7 @@ where
 
         // "use strict";
         if self.config.strict_mode {
-            stmts.push(clone_first_use_strict(n).unwrap_or_else(use_strict));
+            stmts.push(clone_first_use_directive(n).unwrap_or_else(use_strict));
         }
```
Comment (ammmze) [inline crates/swc_ecma_transforms_module/src/amd.rs:149]: Maybe I'm not understanding what this is doing, but at first glance, does this mean that if an input file has a directive, it would only get hoisted to the top of the file if `strictMode` is enabled? I'm using strict mode, so it doesn't really affect me, but I imagine this would be a bug that may present itself in the future.

Comment (ammmze) [reply crates/swc_ecma_transforms_module/src/amd.rs:149]: I guess I must be mis-understanding. I just finished upgrading and tried it out setting strictMode to false and the directive still makes its way to the top. So you can ignore me...it is working as it should.
