### PR TITLE
refact(ecma/utils): merge super field visitor with FnEnvHoister

### LINKED ISSUE #2716: Async to regenerator explicitly binds this context when created
### Describe the bug

I'm hitting some series of https://github.com/swc-project/swc/issues/2305, with various edge cases. We've fixed by not binding to context for some known cases. While, comparing emitted output between swc / babel, both do the similar like

```
function tt() {
  return _tt.apply(this, arguments);
}

function _tt() {
  _tt = _asyncToGenerator(function* () {
    ...
  }); // if swc, do the explicit .bind(this) here
  return _tt.apply(this, arguments);
}
```

which returns wrapped fn calls .apply(this) to bind this context when fn is being called

### Input code

_No response_

### Config

_No response_

### Playground link

_No response_

### Expected behavior

this context would be preserved for each fn per call time.

### Version

master

### Additional context

discord discussion thread: https://discord.com/channels/889779439272075314/889785438938726441/908256585313312819

### LINKED ISSUE #2895: Reference to `arguments` is invalid inside an async function and a class
### Describe the bug

If an async method of a class is using the `arguments` object, the reference to the object is lost.

I have a reproduction here https://github.com/egilsster/swc-jest-issue/blob/main/src/args.test.ts

This starts to work with `target` set to `es2018`

Related to https://github.com/swc-project/swc/issues/2786

### Input code

```typescript
export class Quirk {
  async doStuff() {
    const args = arguments;
    console.log(args);
    return { foo: null, ...args[0] };
  }
}
```

```typescript
const args = { one: 1, two: 2 };
const quirk = new Quirk();
// @ts-ignore using old js syntax
const res = await quirk.doStuff(args);
```

### Config

```json
{
  "jsc": {
    "target": "es2015",
    "parser": {
      "syntax": "typescript"
    }
  },
  "sourceMaps": true,
  "inlineSourcesContent": true
}
```

### Playground link

_No response_

### Expected behavior

I expect the `arguments` object to be `{ '0': { one: 1, two: 2 } }` in my case.

### Version

1.2.112

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**
`FnEnvHoister` should transform super field access too
**BREAKING CHANGE:**
rename `FnEnvState` into `FnEnvHoister`. The origin API design doesn't make any sense
**Related issue (if exists):**
closes #2895 closes #2716

This is still not enough: for browsers like chrome 46 that supports class but not arrow, super field access cannot be transfomed into arrow calls, but I don't believe anyone is actually using them.

### CODE REVIEW

**Comment by Austaras** [comment]
Some snapshot tests are failing, why that happens?

**Comment by Austaras** [comment]
> Some snapshot tests are failing, why that happens?

Seems like default hashmap has a random iter order

File: crates/swc_ecma_utils/src/function/fn_env_hoister.rs [hunk 1]
```diff
@@ -126,57 +145,285 @@ impl FnEnvState {
...
                 kind: MetaPropKind::NewTarget,
                 ..
             }) => {
                 let target = self
-                    .state
                     .new_target
                     .get_or_insert_with(|| private_ident!("_newtarget"));
                 *e = Expr::Ident(target.clone());
             }
+            // super.foo = 123 => super_get_foo = (value) => super.foo = value
```
Comment (kdy1) [inline crates/swc_ecma_utils/src/function/fn_env_hoister.rs:203]: Doesn't we need special handling for `super.foo++`?

File: crates/swc_ecma_utils/src/factory.rs [hunk 2]
```diff
@@ -60,6 +60,18 @@ pub trait ExprFactory: Into<Expr> {
         })
     }
 
+    #[inline]
+    fn call_fn(self, args: Vec<ExprOrSpread>, span: Span) -> Expr {
```
Comment (kdy1) [inline crates/swc_ecma_utils/src/factory.rs:64]: Can you change the order of arguments?
I think span should come first for consistency.

**Review by kdy1 — CHANGES_REQUESTED** [review]
Thanks! Mostly LGTM!

File: crates/swc_ecma_utils/src/function/fn_env_hoister.rs (hunk 1 above)
Comment (Austaras) [reply crates/swc_ecma_utils/src/function/fn_env_hoister.rs:220]: Yes, I somehow forget that

File: crates/swc_ecma_utils/src/function/fn_env_hoister.rs [hunk 3]
```diff
@@ -126,57 +145,378 @@ impl FnEnvState {
...
+
+                            let op = op.to_update();
+
+                            let args = if let Some(op) = op {
+                                let tmp = private_ident!("tmp");
+                                self.extra_ident.push(tmp.clone());
+                                vec![
+                                    Expr::Assign(AssignExpr {
+                                        span: DUMMY_SP,
+                                        left: PatOrExpr::Pat(Box::new(Pat::Ident(
```
Comment (kdy1) [inline crates/swc_ecma_utils/src/function/fn_env_hoister.rs:252]: Can you change this to `PatOrExpr::Pat(tmp.clone().into())`?

Recently I did some work to ease creation of AST and core transforms are the things which plugin authors will look if they are blocked.

File: crates/swc_ecma_utils/src/function/fn_env_hoister.rs [hunk 4]
```diff
@@ -126,57 +145,378 @@ impl FnEnvState {
...
+                                        ))),
+                                        op: op!("="),
+                                        right: c.expr.take(),
+                                    })
+                                    .as_arg(),
+                                    Expr::Bin(BinExpr {
+                                        span: DUMMY_SP,
+                                        left: Box::new(Expr::Call(CallExpr {
+                                            span: DUMMY_SP,
+                                            callee: Callee::Expr(Box::new(
```
Comment (kdy1) [inline crates/swc_ecma_utils/src/function/fn_env_hoister.rs:263]: I think `self.super_get_computed(DUMMY_SP).as_callee()` would be better.

File: crates/swc_ecma_utils/src/function/fn_env_hoister.rs [hunk 5]
```diff
@@ -126,57 +145,378 @@ impl FnEnvState {
...
+                                    })
+                                    .as_arg(),
+                                ]
+                            } else {
+                                vec![c.expr.take().as_arg(), right.take().as_arg()]
+                            };
+                            *e = Expr::Call(CallExpr {
+                                span: *span,
+                                args,
+                                callee: Expr::Ident(callee).as_callee(),
```
Comment (kdy1) [inline crates/swc_ecma_utils/src/function/fn_env_hoister.rs:280]: Please use `callee.as_callee()` instead.

File: crates/swc_ecma_utils/src/function/fn_env_hoister.rs [hunk 6]
```diff
@@ -126,57 +145,378 @@ impl FnEnvState {
...
+                ..
+            }) => {
+                if let Expr::SuperProp(super_prop) = &mut **expr {
+                    match &mut super_prop.prop {
+                        SuperProp::Computed(c) => {
+                            let callee = self.super_get_computed(super_prop.span);
+                            let call = Expr::Call(CallExpr {
+                                span: *span,
+                                args: vec![c.expr.take().as_arg()],
+                                callee: Expr::Ident(callee).as_callee(),
```
Comment (kdy1) [inline crates/swc_ecma_utils/src/function/fn_env_hoister.rs:324]: `callee.as_callee()` would be better.

File: crates/swc_ecma_utils/src/function/fn_env_hoister.rs [hunk 7]
```diff
@@ -126,57 +145,378 @@ impl FnEnvState {
...
+
+                    let op = match op {
+                        op!("++") => op!(bin, "+"),
+                        op!("--") => op!(bin, "-"),
+                    };
+
+                    let update_expr = Expr::Bin(BinExpr {
+                        span: DUMMY_SP,
+                        left: Box::new(Expr::Ident(tmp.clone())),
+                        right: Box::new(Expr::Lit(Lit::Num(Number {
```
Comment (kdy1) [inline crates/swc_ecma_utils/src/function/fn_env_hoister.rs:375]: Can you use `right: 1.0.into()` instead?

File: crates/swc_ecma_utils/src/function/fn_env_hoister.rs [hunk 8]
```diff
@@ -126,57 +145,378 @@ impl FnEnvState {
...
+                            value: 1_f64,
+                        }))),
+                        op,
+                    })
+                    .as_arg();
+
+                    let mut exprs = match prop {
+                        SuperProp::Ident(id) => vec![
+                            Box::new(Expr::Assign(AssignExpr {
+                                left: PatOrExpr::Pat(Box::new(tmp.clone().into())),
```
Comment (kdy1) [inline crates/swc_ecma_utils/src/function/fn_env_hoister.rs:386]: Same here. `Box::new` can be removed I think?

File: crates/swc_ecma_utils/src/function/fn_env_hoister.rs [hunk 9]
```diff
@@ -126,57 +145,378 @@ impl FnEnvState {
...
+                                    .as_call(*arg_span, vec![update_expr]),
+                            ),
+                        ],
+                        SuperProp::Computed(c) => {
+                            let prop = private_ident!("prop");
+                            self.extra_ident.push(prop.clone());
+                            vec![
+                                Box::new(Expr::Assign(AssignExpr {
+                                    span: *arg_span,
+                                    left: PatOrExpr::Pat(Box::new(tmp.clone().into())),
```
Comment (kdy1) [inline crates/swc_ecma_utils/src/function/fn_env_hoister.rs:405]: I think `Box::new` can be removed.

File: crates/swc_ecma_utils/src/function/fn_env_hoister.rs [hunk 10]
```diff
@@ -126,57 +145,378 @@ impl FnEnvState {
...
+                                    op: op!("="),
+                                    right: Box::new(self.super_get_computed(*arg_span).as_call(
+                                        *arg_span,
+                                        vec![Expr::Assign(AssignExpr {
+                                            span: c.span,
+                                            left: PatOrExpr::Pat(Box::new(Pat::Ident(
```
Comment (kdy1) [inline crates/swc_ecma_utils/src/function/fn_env_hoister.rs:411]: Please use `prop.clone().into()` instead of `Box::new(Pat::Ident(prop.clone().into()))`.

File: crates/swc_ecma_utils/src/function/fn_env_hoister.rs [hunk 11]
```diff
@@ -126,57 +145,378 @@ impl FnEnvState {
...
+                    e.visit_mut_children_with(self)
+                }
+            }
+            Expr::SuperProp(SuperPropExpr { prop, span, .. }) => match prop {
+                SuperProp::Computed(c) => {
+                    c.expr.visit_mut_children_with(self);
+                    *e = Expr::Call(CallExpr {
+                        span: *span,
+                        args: vec![c.expr.take().as_arg()],
+                        callee: Expr::Ident(self.super_get_computed(*span)).as_callee(),
```
Comment (kdy1) [inline crates/swc_ecma_utils/src/function/fn_env_hoister.rs:441]: `Expr::Ident()` can be omitted.

File: crates/swc_ecma_utils/src/function/fn_env_hoister.rs [hunk 12]
```diff
@@ -126,57 +145,378 @@ impl FnEnvState {
...
+                        type_args: None,
+                    })
+                }
+                SuperProp::Ident(id) => {
+                    *e = Expr::Call(CallExpr {
+                        span: *span,
+                        args: Vec::new(),
+                        callee: Expr::Ident(self.super_get(id, *span)).as_callee(),
```
Comment (kdy1) [inline crates/swc_ecma_utils/src/function/fn_env_hoister.rs:449]: `Expr::Ident()` can be omitted.

File: crates/swc_ecma_utils/src/function/fn_env_hoister.rs [hunk 13]
```diff
@@ -269,3 +609,104 @@ impl<'a> VisitMut for InitThis<'a> {
...
+            }))),
+            definite: false,
+        }
+    }));
+    if let Some(id) = set.computed {
+        let prop = private_ident!("_prop");
+        let value = private_ident!("_value");
+        decls.push(VarDeclarator {
+            span: DUMMY_SP,
+            name: Pat::Ident(id.into()),
```
Comment (kdy1) [inline crates/swc_ecma_utils/src/function/fn_env_hoister.rs:687]: `Pat::Ident()` can be omitted.

File: crates/swc_ecma_utils/src/function/fn_env_hoister.rs [hunk 14]
```diff
@@ -269,3 +609,104 @@ impl<'a> VisitMut for InitThis<'a> {
...
+            return_type: None,
+            type_params: None,
+        }))),
+        definite: false,
+    }));
+    if let Some(id) = get.computed {
+        let param = private_ident!("_prop");
+        decls.push(VarDeclarator {
+            span: DUMMY_SP,
+            name: Pat::Ident(id.into()),
```
Comment (kdy1) [inline crates/swc_ecma_utils/src/function/fn_env_hoister.rs:636]: `Pat::Ident()` can be omitted.

File: crates/swc_ecma_utils/src/function/fn_env_hoister.rs [hunk 15]
```diff
@@ -269,3 +609,104 @@ impl<'a> VisitMut for InitThis<'a> {
...
+                type_params: None,
+            }))),
+            definite: false,
+        });
+    }
+    decls.extend(set.ident.into_iter().map(|(key, ident)| {
+        let value = private_ident!("_value");
+        VarDeclarator {
+            span: DUMMY_SP,
+            name: Pat::Ident(ident.into()),
```
Comment (kdy1) [inline crates/swc_ecma_utils/src/function/fn_env_hoister.rs:660]: This `Pat::Ident` can be omitted.

File: crates/swc_ecma_utils/src/function/fn_env_hoister.rs [hunk 16]
```diff
@@ -269,3 +609,104 @@ impl<'a> VisitMut for InitThis<'a> {
         }
     }
 }
+
+fn extend_super(decls: &mut Vec<VarDeclarator>, get: SuperField, set: SuperField) {
+    decls.extend(get.ident.into_iter().map(|(key, ident)| VarDeclarator {
+        span: DUMMY_SP,
+        name: Pat::Ident(ident.into()),
```
Comment (kdy1) [inline crates/swc_ecma_utils/src/function/fn_env_hoister.rs:616]: `Pat::Ident` can be omitted.

**Review by kdy1 — CHANGES_REQUESTED** [review]
Thank you for the hard work!
I found some code style issues.

**Review by kdy1 — APPROVED** [review]
LGTM. Thank you!
