### PR TITLE
fix(es/lint): ignore type binding in `Duplicate binding`

### LINKED ISSUE #3848: Duplicate binding is incorrectly reported on the type
### Describe the bug

type is incorrectly identified as a duplicate binding in the lint phase.

### Input code

```typescript
import { Context, createContext } from 'react'
export const Context: Context<null> = createContext<null>(null)
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript"
    },
    "target": "es2022"
  },
  "module": {
    "type": "es6"
  },
  "isModule": true
}
```

### Playground link

[REPL](https://play.swc.rs/?version=1.2.148&code=H4sIAAAAAAAAA8vMLcgvKlGoVnDOzytJrSjRUUguSk0sSYVyFWoV0orycxXUgYLJJepcqRVg5cn5ecUlMC1WMIZNXmlOjp2CLaoREFENEKnJBQDnfKWWbwAAAA%3D%3D&config=H4sIAAAAAAAAA6tWyipOVrKqVipILCpOLQKxiivzShIrlKyUSioLUouTizILSpRqdZRKEovSU0uAwqnFRgZGRiCh3PyU0pxUkB6QUrCUGUg8s9gXKlNSVJpaCwCtpKCjZAAAAA%3D%3D)

### Expected behavior

swc should compile correctly

### Actual behavior

```
error: Duplicate binding
 --> input.ts:2:14
  |
2 | export const Context: Context<null> = createContext<null>(null)
  |              ^^^^^^^
  |
note: Context was declared at here
 --> input.ts:1:10
  |
1 | import { Context, createContext } from 'react'
  |          ^^^^^^^
```

### Version

1.2.148

### Additional context

Potential solutions
Move the lint phase to the back of ts strip.

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
- fix #3848

### CODE REVIEW

File: crates/swc_ecma_lints/src/rules/duplicate_bindings.rs [hunk 1]
```diff
@@ -14,6 +14,7 @@ pub fn duplicate_bindings() -> Box<dyn Rule> {
 #[derive(Debug, Default)]
 struct DuplicateBindings {
     bindings: AHashMap<Id, Span>,
+    type_bindings: AHashMap<Id, Span>,
```
Comment (kdy1) [inline crates/swc_ecma_lints/src/rules/duplicate_bindings.rs]: Is Span used?

**Review by kdy1 — DISMISSED** [review]
LGTM. Thank you!

---

swc-bump:
 - swc_ecma_lints

**Review by kdy1 — APPROVED** [review]
