### PR TITLE
fix(transform): calculate class member fn args identifier collision

### LINKED ISSUE #1948: Multiple argument destructuring on a method definition inside object initializer causes clashed argument names
**Describe the bug**

Multiple argument destructuring on a method definition inside object initializer causes clashed argument names.

**Input code**

```js
function fn1(arg1, {opt1, opt2}, ...arg2) {
    console.log(arg1, opt1, opt2, arg2);
}

function fn2(arg1, {opt1, opt2}, arg2, {opt3, opt4}, ...arg3) {
    console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
}

const fn3 = (arg1, {opt1, opt2}, arg2, {opt3, opt4}, ...arg3) => {
    console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
};

class cls {
    constructor(arg1, {opt1, opt2}, arg2, {opt3, opt4}, ...arg3) {
        console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
    }

    fn4(arg1, {opt1, opt2}, arg2, {opt3, opt4}, ...arg3) {
        console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
    }
}

export default {
    fn5(arg1, {opt1, opt2}, arg2, {opt3, opt4}, ...arg3) {
        console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
    },
    fn7: function*(arg1, {opt1, opt2}, arg2, {opt3, opt4}, ...arg3) {
        console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
        yield null;
    },
    *fn6(arg1, {opt1, opt2}, arg2, {opt3, opt4}, ...arg3) {
        console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
        yield null;
    },
};
```

**Config**

```json
{
  "env": {
    "targets": {
      "chrome": "49",
      "firefox": "45",
      "safari": "10",
      "edge": "13"
    },
    "mode": "entry",
    "coreJs": 2
  },
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true,
      "dynamicImport": true,
      "privateMethod": true,
      "functionBind": true,
      "classPrivateProperty": true,
      "exportDefaultFrom": true,
      "exportNamespaceFrom": true,
      "decorators": true,
      "decoratorsBeforeExport": true,
      "importMeta": true
    }
  },
  "minify": false,
  "sourceMaps": false
}
```

**Result**

```js
import   "core-js/modules/web.timers";
import   "core-js/modules/web.immediate";
import   "core-js/modules/web.dom.iterable";
import   "regenerator-runtime/runtime";
import regeneratorRuntime from "regenerator-runtime";
function fn1(arg1, param) {
    var opt1 = param.opt1, opt2 = param.opt2;
    for(var _len = arguments.length, arg2 = new Array(_len > 2 ? _len - 2 : 0), _key = 2; _key < _len; _key++){
        arg2[_key - 2] = arguments[_key];
    }
    console.log(arg1, opt1, opt2, arg2);
}
function fn2(arg1, param, arg2, param1) {
    var opt1 = param.opt1, opt2 = param.opt2, opt3 = param1.opt3, opt4 = param1.opt4;
    for(var _len = arguments.length, arg3 = new Array(_len > 4 ? _len - 4 : 0), _key = 4; _key < _len; _key++){
        arg3[_key - 4] = arguments[_key];
    }
    console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
}
var fn3 = function(arg1, param, arg2, param1) {
    var opt1 = param.opt1, opt2 = param.opt2, opt3 = param1.opt3, opt4 = param1.opt4;
    for(var _len = arguments.length, arg3 = new Array(_len > 4 ? _len - 4 : 0), _key = 4; _key < _len; _key++){
        arg3[_key - 4] = arguments[_key];
    }
    console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
};
class cls {
    fn4(arg1, param, arg2, param) {
        var opt1 = param.opt1, opt2 = param.opt2, opt3 = param.opt3, opt4 = param.opt4;
        for(var _len = arguments.length, arg3 = new Array(_len > 4 ? _len - 4 : 0), _key = 4; _key < _len; _key++){
            arg3[_key - 4] = arguments[_key];
        }
        console.log(arg1, opt1, opt2, arg2, opt3, opt4, arg3);
    }
    constructor(arg11, param2, arg21, param1){
        var opt1 = param2.opt1, opt2 = param2.opt2, opt3 = param1.opt3, opt4 = param1.opt4;
        for(var _len = arguments.length, arg3 = new Array(_len > 4 ? _len - 4 : 0), _key = 4; _key < _len; _key++){
            arg3[_key - 4] = arguments[_key];
        }
        console.log(arg11, opt1, opt2, arg21, opt3, opt4, arg3);
    }
}
export default {
    fn5 (arg1, param, arg2, param) {
        var opt11 = param.opt1, opt21 = param.opt2, opt31 = param.opt3, opt41 = param.opt4;
        for(var _len1 = arguments.length, arg31 = new Array(_len1 > 4 ? _len1 - 4 : 0), _key1 = 4; _key1 < _len1; _key1++){
            arg31[_key1 - 4] = arguments[_key1];
        }
        console.log(arg1, opt11, opt21, arg2, opt31, opt41, arg31);
    },
    fn7: regeneratorRuntime.mark(function fn7(arg12, param3, arg22, param4) {
        var opt12, opt22, opt32, opt42, _len2, arg32, _key2, _args = arguments;
        return regeneratorRuntime.wrap(function fn7$(_ctx) {
            while(1)switch(_ctx.prev = _ctx.next){
                case 0:
                    opt12 = param3.opt1, opt22 = param3.opt2, opt32 = param4.opt3, opt42 = param4.opt4;
                    for(_len2 = _args.length, arg32 = new Array(_len2 > 4 ? _len2 - 4 : 0), _key2 = 4; _key2 < _len2; _key2++){
                        arg32[_key2 - 4] = _args[_key2];
                    }
                    console.log(arg12, opt12, opt22, arg22, opt32, opt42, arg32);
                    _ctx.next = 5;
                    return null;
                case 5:
                case "end":
                    return _ctx.stop();
            }
        }, fn7);
    }),
    fn6 () {
        return regeneratorRuntime.mark(function _callee(arg12, param3, arg22, param4) {
            var opt12, opt22, opt32, opt42, _len2, arg32, _key2, _args = arguments;
            return regeneratorRuntime.wrap(function _callee$(_ctx) {
                while(1)switch(_ctx.prev = _ctx.next){
                    case 0:
                        opt12 = param3.opt1, opt22 = param3.opt2, opt32 = param4.opt3, opt42 = param4.opt4;
                        for(_len2 = _args.length, arg32 = new Array(_len2 > 4 ? _len2 - 4 : 0), _key2 = 4; _key2 < _len2; _key2++){
                            arg32[_key2 - 4] = _args[_key2];
                        }
                        console.log(arg12, opt12, opt22, arg22, opt32, opt42, arg32);
                        _ctx.next = 5;
                        return null;
                    case 5:
                    case "end":
                        return _ctx.stop();
                }
            }, _callee);
        })();
    }
};


//#sourceMappingURL=data:application/json;charset=utf-8;base64,IntcInZlcnNpb25cIjozLFwic291cmNlc1wiOltdLFwibmFtZXNcIjpbXSxcIm1hcHBpbmdzXCI6XCJcIixcImZpbGVcIjpcInN0ZG91dFwifSI=
```

**Expected behavior**

The transpile results of `fn4` and `fn5` is wrong, duplicated placeholder argument `param` is generated.

Interestingly, only method definitions in object initializer or class body could reproduce the problem.

**Version**
```
    "@swc/cli": "^0.1.46",
    "@swc/core": "^1.2.66",
```

**Additional context**

`@swc/cli` is utilized to inspect the transpile result of my sample input.

### PR DESCRIPTION
**Pull request by kwonoj**
Another attempt to close #1948 

Originate from PR https://github.com/swc-project/swc/pull/1961, this PR attempt to apply same changes partially for the class method params by creating separate scope since param identifier does not collide to other method / prop declarations. 

This _seems_ working, new test case passes without changing existing fixture update. But suggested recommendation (https://github.com/swc-project/swc/pull/1961#issuecomment-886156602) is updating `_mut_class_method` and `_mut_class_prop` both, while this one only touches class_method this may not be still legit approach. Also bit unsure using new folder is right approach to consider.

### CODE REVIEW

File: ecmascript/transforms/base/src/hygiene/mod.rs [hunk 1]
```diff
@@ -665,6 +665,21 @@ impl<'a> VisitMut for Hygiene<'a> {
...
+            current: Scope::new(ScopeKind::Fn, None),
+            ident_type: IdentType::Ref,
+            var_kind: None,
+        };
+
+        folder.ident_type = IdentType::Binding;
+        n.function.params.visit_mut_children_with(&mut folder);
+        folder.apply_ops(n);
+
+        n.visit_mut_children_with(self);
```
Comment (kdy1) [inline ecmascript/transforms/base/src/hygiene/mod.rs:680]: Doesn't this visit `n.functions.params` again?
Is it intentional?

File: ecmascript/transforms/base/src/hygiene/mod.rs [hunk 2]
```diff
@@ -665,6 +665,21 @@ impl<'a> VisitMut for Hygiene<'a> {
...
+        let mut folder = Hygiene {
+            config: self.config.clone(),
+            current: Scope::new(ScopeKind::Fn, None),
+            ident_type: IdentType::Ref,
+            var_kind: None,
+        };
+
+        folder.ident_type = IdentType::Binding;
+        n.function.params.visit_mut_children_with(&mut folder);
+        folder.apply_ops(n);
```
Comment (kdy1) [inline ecmascript/transforms/base/src/hygiene/mod.rs:678]: I think this can be changed to `folder.apply_ops(&mut n.params)`.

**Review by kdy1 — COMMENTED** [review]
Thanks. I found two possible issues, but I'm not sure about both of those.

File: ecmascript/transforms/base/src/hygiene/mod.rs (hunk 1 above)
Comment (kwonoj) [reply ecmascript/transforms/base/src/hygiene/mod.rs:680]: I guessed similar, but somehow without this some of existing test fails like below

```
// tests\fixture\swc-node-335\case1\output\index.js

function _defineProperty(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, {
            value: value,
            enumerable: true,
            configurable: true,
            writable: true
        });
    } else {
        obj[key] = value;
    }
    return obj;
}
let Foo = class Foo {
    method() {
        class Foo {
        }
    }
};
_defineProperty(Foo, "a", 1);


Diff < left / right > :
 function _defineProperty(obj, key, value) {
     if (key in obj) {
         Object.defineProperty(obj, key, {
             value: value,
             enumerable: true,
             configurable: true,
             writable: true
         });
     } else {
         obj[key] = value;
     }
     return obj;
 }
 let Foo = class Foo {
     method() {
<        let Foo1 = class Foo {
<        };
>        class Foo {
>        }
     }
 };
 _defineProperty(Foo, "a", 1);
```

Trying to recalculate identifier, which makes output incorrect.

Comment (kdy1) [reply ecmascript/transforms/base/src/hygiene/mod.rs:680]: I meant replacing this with manual visit of properties, not removing this line.
Did you tried it?

File: ecmascript/transforms/base/src/hygiene/mod.rs (hunk 2 above)
Comment (kwonoj) [reply ecmascript/transforms/base/src/hygiene/mod.rs]: I tried apply `n.function.params` as node, it makes test fail by identifier reference collision like

```
fn4(arg1, param, arg2, param1) {
        var opt1 = param.opt1, opt2 = param.opt2, opt3 = param.opt3, opt4 = param.opt4;
```

for newly added test cases. Updated to supply `n.function` instead.

File: ecmascript/transforms/base/src/hygiene/mod.rs (hunk 1 above)
Comment (kwonoj) [reply ecmascript/transforms/base/src/hygiene/mod.rs]: Updated PR to manually request traverses like https://github.com/swc-project/swc/pull/1964/files#diff-10d7cd5c048de48351715805d282583190a251ec35e84f7c6a6e7f633387d6bdR681 and seems it makes test correctly passing, wonder if there's missing one or it's ok.

File: ecmascript/transforms/base/src/hygiene/mod.rs (hunk 2 above)
Comment (kdy1) [reply ecmascript/transforms/base/src/hygiene/mod.rs]: I see, thanks!

File: ecmascript/transforms/base/src/hygiene/mod.rs [hunk 3]
```diff
@@ -665,6 +665,25 @@ impl<'a> VisitMut for Hygiene<'a> {
...
+            ident_type: IdentType::Ref,
+            var_kind: None,
+        };
+
+        folder.ident_type = IdentType::Binding;
+        n.function.params.visit_mut_children_with(&mut folder);
+
+        folder.ident_type = IdentType::Ref;
+
+        n.function.body.visit_mut_with(self);
```
Comment (kdy1) [inline ecmascript/transforms/base/src/hygiene/mod.rs:681]: I think `decorators ` should be also visited. Maybe it can be visited at first, before creating `folder`.

File: ecmascript/transforms/base/src/hygiene/mod.rs (hunk 1 above)
Comment (kdy1) [reply ecmascript/transforms/base/src/hygiene/mod.rs]: `decorators` should be also visited as skipping it can break some Deno code.

File: ecmascript/transforms/base/src/hygiene/mod.rs (hunk 3 above)
Comment (kwonoj) [reply ecmascript/transforms/base/src/hygiene/mod.rs:683]: Thanks for the catch. Applied changes as suggested.

**Review by kdy1 — APPROVED** [review]
Thank you a lot!
