### PR TITLE
fix(es/compat): Handle empty destructuring

### LINKED ISSUE #6306: [Bug]: Object destructuring assignment expression in strict mode results in `ReferenceError`
### Describe the bug

 A `TypeError` is expected but I get `ReferenceError` when running the output code.

### Input code

```typescript
"use strict";
x = { } = null ;
```

### Config

_No response_

### Playground link

https://play.swc.rs/?version=1.3.11&code=H4sIAAAAAAAAA1MqLU5VKC4pykwuUbLmqlCwVahWqAWSeaU5OQrWAFVpzJAeAAAA&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

`null` is not iterable so the input code throws `TypeError`:
```console
$ node input.js
input.js:2
x = { } = null ;
          ^

TypeError: Cannot destructure 'null' as it is null.
    at Object.<anonymous> (/Users/p51lee/dev/esmeta-plrg/input.js:2:5)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0
```

### Actual behavior

The output code throws `ReferenceError`:
```console
$ node output.js
output.js:3
x = (ref = null, ref);
  ^

ReferenceError: x is not defined
    at Object.<anonymous> (/Users/p51lee/dev/esmeta-plrg/output.js:3:3)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0
```

### Version

1.3.11 (default SWC playground)

### Additional context

_No response_

### LINKED ISSUE #6330: [Bug]: Object destructuring pattern in function parameter
### Describe the bug

`input.js` is expected to throw `TypeError` but the output code is terminated without error.
```js
// output.js
...
var param = param !== null ? param : _throw(new TypeError("Cannot destructure undefined"));
//                       ^ I think the output program should consider if param !== undefined.
...
```

### Input code

```typescript
new function ( { } ) { } ;
```

### Config

_No response_

### Playground link

https://play.swc.rs/?version=1.3.11&code=H4sIAAAAAAAAA8tLLVdIK81LLsnMz1PQUKhWqFXQBJPWAEra07EaAAAA&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

`input.js` is expected to throw `TypeError`:
```console
$ node input.js
input.js:1
new function ( { } ) { } ;
               ^

TypeError: Cannot destructure 'undefined' as it is undefined.
    at new <anonymous> (/Users/p51lee/dev/esmeta-plrg/input.js:1:16)
    at Object.<anonymous> (/Users/p51lee/dev/esmeta-plrg/input.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0
```

### Actual behavior

Transpiled code terminates without error:
```console
$ node output.js
// terminates without error
```

### Version

https://play.swc.rs/?version=1.3.11&code=H4sIAAAAAAAAA8tLLVdIK81LLsnMz1PQUKhWqFXQBJPWAEra07EaAAAA&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Additional context

_No response_

### LINKED ISSUE #6390: [Bug]: Destructuring `null` or `undefined` with rest
### Describe the bug

The input code is destructuring `null` (or `undefined`) so it should throw `TypeError` exception but the transpiled code does not.

### Input code

```typescript
var { ... x } = null ; // or undefined
```

### Config

_No response_

### Playground link

https://play.swc.rs/?version=1.3.14&code=H4sIAAAAAAAAAytLLFKoVtDT01OoUKhVsFXIK83JUbAGAPSFhPAWAAAA&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

The input code throws `TypeError`:
```console
$ node input.js
input.js:1
var { ... x } = null ;
                ^

TypeError: Cannot destructure 'null' as it is null.
    at Object.<anonymous> (input.js:1:11)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0
```

### Actual behavior

The output code does not throw exception:
```console
$ node output.js # no error
```

### Version

1.3.14 (default SWC playground)

### Additional context

_No response_

### LINKED ISSUE #6392: [Bug]: Empty object destructuring declares an unnecessary variable
### Describe the bug

The input code is destructuring an undefined variable so it should throw `ReferenceError` but the transpiled code does not because it declares a new variable which prevents `ReferenceError`.

### Input code

```typescript
let { } = x ;
```

### Config

_No response_

### Playground link

https://play.swc.rs/?version=1.3.11&code=H4sIAAAAAAAAA8tJLVGoVqhVsFWoULBWAADXQBBZDgAAAA%3D%3D&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

The input code throws `ReferenceError`:
```console
$ node input.js
input.js:1
let { } = x ;
          ^

ReferenceError: x is not defined
    at Object.<anonymous> (input.js:1:11)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

Node.js v18.11.0
```

### Actual behavior

The transpiled code is terminated normally:
```console
$ node output.js # no error
```

### Version

1.3.14 (default SWC playground)

### Additional context

By the way, this can even result in an unexpected behavior in silent manner:

```js
let x = 42;

function f() {
  let { } = x ;
  console.log(x);
}

f();
```
This code is expected to print `42` but the transpiled code prints `undefined`.

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

Add `_objectDestructuringEmpty` helper to check if the field is empty.

**BREAKING CHANGE:**

- swc helpers

**Related issue (if exists):**
- fix #6392 
- fix #6306 
- fix #6390 
- fix #6330

### CODE REVIEW

File: crates/swc_ecma_transforms_compat/tests/es2018_object_rest_spread.rs [hunk 1]
```diff
@@ -523,7 +522,7 @@ const {
   },
   c = ({ ...d } = {}),
 } = {};
-a()
+a({})
```
Comment (magic-akari) [inline crates/swc_ecma_transforms_compat/tests/es2018_object_rest_spread.rs:525]: I think this is a wrong test case. @kdy1 
`a()` should throw  `Cannot destructure undefined`

Comment (kdy1) [reply crates/swc_ecma_transforms_compat/tests/es2018_object_rest_spread.rs:525]: I tested on chrome and I think you are right

**Review by kdy1 — APPROVED** [review]
Thank you!


----

swc-bump:
 - swc_ecma_transforms_compat
