### PR TITLE
fix(es/minifier): Track reassign in parent scope

### LINKED ISSUE #6864: Bug in the minifier in 1.3.29
### Describe the bug

We got integration test failures with a upgrade from 1.3.28 to 1.3.29

I can see that there are minified code differences, but its very hard to see what the problem is:

image

### Input code

```typescript
I can work on a repro if you need it, but it will take some time, please let me know. I'll have a go after filing this issue, but I think you should consider reverting the probable cause commit until the bug is found as anyone upgrading could get bugs in production.
```

### Config

```json
N/A - no swcrc

We use these options


        compress: {
            // all are default values unless commented
            arguments: false,
            arrows: true,
            booleans: true,
            booleans_as_integers: false,
            collapse_vars: true,
            comparisons: true,
            computed_props: true,
            conditionals: true,
            dead_code: true, // defaults to false
            defaults: true,
            directives: true,
            drop_console: false,
            drop_debugger: false, // defaults to true
            ecma: 5,
            evaluate: true,
            global_defs: {},
            hoist_funs: false,
            hoist_props: true,
            hoist_vars: false,
            if_return: true,
            inline: true,
            join_vars: true,
            keep_classnames: true, // defaults to false
            keep_fargs: false,
            keep_infinity: false,
            loops: true,
            negate_iife: true,
            passes: 0,
            properties: true,
            pure_getters: ``,
            pure_funcs: [],
            reduce_funcs: false,
            reduce_vars: true,
            sequences: true,
            side_effects: true,
            switches: true,
            top_retain: ``,
            toplevel: true,
            typeofs: true,
            unsafe: false,
            unsafe_arrows: false,
            unsafe_comps: false,
            unsafe_Function: false,
            unsafe_math: false,
            unsafe_symbols: false,
            unsafe_methods: false,
            unsafe_proto: false,
            unsafe_regexp: false,
            unsafe_undefined: false,
            unused: true,
        },
        mangle: {
            // all defaults except keepClassnames/keepFnames which can be disabled for integration tests
            topLevel: true,
            keepClassNames: true,
            keepFnNames: true,
            keepPrivateProps: false,
            reserved: [],
        },
```
```


### Playground link

_No response_

### Expected behavior

Code to run as it did in 1.3.28

### Actual behavior

_No response_

### Version

1.3.29

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

**Related issue:**

 - Closes https://github.com/swc-project/swc/issues/6864.

### CODE REVIEW

File: crates/swc_ecma_minifier/src/program_data.rs [hunk 1]
```diff
@@ -620,10 +620,10 @@ impl ProgramData {
         if is_first {
             e.ref_count += 1;
             if !inited && e.var_initialized {
+                e.reassigned = true;
```
Comment (Austaras) [inline crates/swc_ecma_minifier/src/program_data.rs:623]: This used to be
```rs
        if is_first {
            e.ref_count += 1;
            if !inited && e.var_initialized {
                e.cond_init = true;
                if !is_modify {
                    e.var_initialized = false;
                    e.assign_count += 1;
                    e.reassigned_with_assignment = true
                }
            }
        }
```
I forgot to patch this in last PR.

File: crates/swc_ecma_minifier/tests/fixture/issues/6864/output.js [hunk 2]
```diff
@@ -0,0 +1,22 @@
+export function removeFromMatrix(matrix, id) {
```
Comment (kdy1) [inline crates/swc_ecma_minifier/tests/fixture/issues/6864/output.js:1]: [The output of `v1.3.28`](https://play.swc.rs/?version=1.3.28&code=H4sIAAAAAAAAA31STWuDQBC9F%2FofpjcFkabHpAZ6aKGHUAi9iQQbx2RBZ8u6RqXxv3fdNbqatJ7c8X3NW7H%2B5kJCWtJeMk4gMOcnfBM838RSsNq5vwP15PqwhC3GCaeseREibp6np0JB6LBee4bCkiWYkRq48GOmp1gAYbXp9f7TWY0MRgnWH%2Bl78sm3OuASqMy%2FUCjMiBK8mifstSCAnZ8qFccs4oGDJEXjGWUXgvUloI6egrPzGe2zMsFigCaua6M0ch5MOenZaooTKEtBoJWsT615bd1hj876QS0ycerZJntPb22GIvgZ0kEeIQgCWEzYQ926hYrJIy%2FlUETnNbhf9AZK%2BBjZwk9XBew5FbL7a2JGqunXbkHlYwvMqrDjhOGUqdCRB%2FPhIoqiG6UBZgX%2BtWjo%2B75Z0aaOsa4uLpq0o1rRFz4vu7%2BJ0el8Hq%2Bl%2FQVQDhftTQMAAA%3D%3D&config=H4sIAAAAAAAAA22TQZLjIAxF78I6i6ksZpEDzK7PQBEQDj0YuZBIx5XK3UfYMcTJ7OD5S5a%2BxF19k1Wnu5pMJsj1RHNic1MnxfMEZHOYWB0UkyDOBR5yNnkAFgXQ8dfxKF8jIoE6eRMJDmoMKfi55rI4ThmI6lmCygiJqelMzvhDa9qDOiNGMOnjrg3pkBgGyD3UYoxmItBXk1tE%2FZvJgTDtUGFweso4vdDkAgdMkmxjDozTFh00EDJYDlfoEskhkkRSWKtkgQ7OZRiqf6sSriYWwy0X3BYb5I8t7oKBWPuS6A3tKl3R2uRTFbzOwCWnTfONIe18%2BAsgdUZDlMwIPXLhXuawV%2Fr%2FqELyMkSeG5UJ96oSDNKcDsG3DmvVkDl0tzK4YqF2aHvyJ9w1RMGBBu%2FF7RZMP4HtpSeru4i%2BXcU14%2FsM1qve9mlP6wp8wD9SFb%2BO48lHw5d3RvN4xviRYgS%2BoPvAYgTjO8yyvbfpnZbkQGwG9%2FKhUL22NZXhM%2BpYX9vmsyyExOgh4rmtrzzK0aShreWjAnSlgvti3vJaf6tHf53bOtHXU7gk%2BgcCGYLtEQQAAA%3D%3D)

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_ecma_minifier

**Review by kdy1 — APPROVED** [review]

**Review by kdy1 — APPROVED** [review]

**Review by jridgewell — APPROVED** [review]
