### PR TITLE
fix(es/minifier): Report `is_fn_local` even if var is hoisted

### LINKED ISSUE #7847: Incorrect minification of rollup commonjs wrapper
### Describe the bug

I am using swc to minify a bundled version of Node.js-powered CLI.

Here is a part of the code (CommonJS wrapper generated by `@rollup/plugin-commonjs`):

```js
var state;
var hasRequiredState;

function requireState () {
	if (hasRequiredState) return state;
	hasRequiredState = 1;

	var ERR_INVALID_OPT_VALUE = requireErrors().codes.ERR_INVALID_OPT_VALUE;
	function highWaterMarkFrom(options, isDuplex, duplexKey) {
	  return options.highWaterMark != null ? options.highWaterMark : isDuplex ? options[duplexKey] : null;
	}
	function getHighWaterMark(state, options, duplexKey, isDuplex) {
	  var hwm = highWaterMarkFrom(options, isDuplex, duplexKey);
	  if (hwm != null) {
	    if (!(isFinite(hwm) && Math.floor(hwm) === hwm) || hwm < 0) {
	      var name = isDuplex ? duplexKey : 'highWaterMark';
	      throw new ERR_INVALID_OPT_VALUE(name, hwm);
	    }
	    return Math.floor(hwm);
	  }

	  // Default value
	  return state.objectMode ? 16 : 16 * 1024;
	}
	state = {
	  getHighWaterMark: getHighWaterMark
	};
	return state;
}
```

After minification, it becomes this:

```js
var fv,fE;
// redacted
function cz(){if(fE)return fv;fE=1;var e=cH().codes.ERR_INVALID_OPT_VALUE;return{getHighWaterMark:function(t,r,n,i){var s=null!=r.highWaterMark?r.highWaterMark:i?r[n]:null;if(null!=s){if(!(isFinite(s)&&Math.floor(s)===s)||s<0){var o=i?n:"highWaterMark";throw new e(o,s)}return Math.floor(s)}return t.objectMode?16:16384}}}
```

Note that after the minification, the `fv` (which originally is the `state`) is no longer assigned.

I couldn't find the minimum reproduction (my guess is that some code somewhere has interfered with the compression), so I have attached the full code in the GitHub Gist.

### Input code

```typescript
// https://gist.github.com/SukkaW/0a02d14521418685c6bc822c043bbe6a
// The playground URL is too long to attach
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": true
    },
    "target": "es2022",
    "minify": {
      "compress": true,
      "mangle": true,
      "module": true
    }
  },
  "minify": true,
  "isModule": true,
  "module": {
    "type": "commonjs"
  }
}
```

### Playground link

_No response_

### Expected behavior

The minified code should not produce any error.

### Actual behavior

```
TypeError can not read property (`getHighWaterMark`) of `undefined`
```

### Version

1.3.78

### Additional context

I am able to reproduce the issue since swc 1.2.166. The issue doesn't happen on 1.2.165.

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
Closes #7847

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thank you! The change looks sooooo simple.

---

swc-bump:
 - swc_ecma_minifier

File: crates/swc_ecma_minifier/tests/fixture/issues/7847/output.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+if (g()) {
+    var state, hasRequiredState;
+    const a = hasRequiredState ? state : (hasRequiredState = 1, state = {
+        getHighWaterMark: function(o) {
+            return o.objectMode ? 16 : 16384;
+        }
+    });
+    console.log(a.getHighWaterMark());
```
Comment (jridgewell) [inline crates/swc_ecma_minifier/tests/fixture/issues/7847/output.js:8]: Nit: Can we add a `console.log(state)` here? The old transform is technically correct, since `state` is never read after the assignment (this could have been eliminated with a lexical analysis)

**Review by jridgewell — APPROVED** [review]

File: crates/swc_ecma_minifier/tests/fixture/issues/7847/output.js (hunk 1 above)
Comment (SukkaW) [reply crates/swc_ecma_minifier/tests/fixture/issues/7847/output.js:8]: @jridgewell I prefer this:

```js
// generated by @rollup/plugin-commonjs
function requireState() {
    if (hasRequiredState) return state;
    hasRequiredState = 1;
    return state = {
        getHighWaterMark: function(o) {
            return o.objectMode ? 16 : 16384;
        }
    };
}
if (g()) {
    var state, hasRequiredState;
    const a = requireState();
	console.log(a.getHighWaterMark());
    // Hidden state reading!
    const b = requireState();
	console.log(b.getHighWaterMark());
}
```

This is from my original issue, where swc incorrectly transform this into:

```js
'use strict';
function requireState() {
    return hasRequiredState ? state : (hasRequiredState = 1, {
        getHighWaterMark: function(o) {
            return o.objectMode ? 16 : 16384;
        }
    });
}
if (g()) {
    var state, hasRequiredState;
    let a = requireState();
    console.log(a.getHighWaterMark());
    let b = requireState();
    console.log(b.getHighWaterMark());
}
```

Comment (Austaras) [reply crates/swc_ecma_minifier/tests/fixture/issues/7847/output.js:11]: Done
