### PR TITLE
fix(es/compat): class has same name method and accessor

### LINKED ISSUE #5029: TypeError: Invalid property descriptor
### Describe the bug

The code run by node report an error as follows transpiled by swc
```shell
TypeError: Invalid property descriptor. Cannot both specify accessors and a value or writable attribute, #<Object>
```

### Input code

```typescript
class A {
    static b() {
    }
    static get b() {
    }
    static set b(b) {
    }
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": false
}
```

### Playground link

https://play.swc.rs/?version=1.2.204&code=H4sIAAAAAAAAA0vOSSwuVnBUqOZSAILiksSSzGSFJA1NqEAtsnB6agkuqWKwVBJCrhYAEcrfU1kAAAA%3D&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1t93kDj2EcJXg4B8eB2KM716ZumQlMe%2FNdDphaeuUuUDK%2FNBi5Zs2EhsYtrhcyaim0c4eMgxVLofUqeClzKcEWdRQcNHtbS7ZFHIR4EEcD%2F83hw6F9Llm0Km2rHdWQoonaDxDq%2BzwXvav%2FgXU82csuwAAAA%3D%3D

### Expected behavior

Code can run without error by nodejs after transpiling.

### Actual behavior

_No response_

### Version

1.2.204

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
closes #5029

### CODE REVIEW

File: crates/swc_ecma_transforms_compat/tests/classes/issue-5029/2/output.js [hunk 1]
```diff
@@ -0,0 +1,18 @@
+let A = /*#__PURE__*/ function() {
+    "use strict";
+    function A() {
+        _classCallCheck(this, A);
+    }
+    _createClass(A, [
+        {
+            key: "b",
```
Comment (Austaras) [inline crates/swc_ecma_transforms_compat/tests/classes/issue-5029/2/output.js:8]: Key merge need to happen earlier

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_ecma_transforms_compat
