### PR TITLE
fix(es/module): binding export for assign expr

### LINKED ISSUE #3898: import/export should obey binding rule
### Describe the bug

[es6 import/export is binding](https://stackoverflow.com/a/46937590/13763537), [babel obey this rule](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.6&spec=false&loose=false&code_lz=KYDwDg9gTgLgBAG2PAygeQKoCUDCBRAWQEEAFEgSQDkBxAfWwBk4BeOAcgGcIBXKAY2AEAhmwDcAKHTZ8xMlTqM4AalZswYAJYA7AOaMx4gPSG4GgGZwA7sFMBbSLDgAiKbkKkKNelgZOrNyw0EBDgdZGcuXgFhdW09HycgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2&prettier=false&targets=&version=7.17.6&externalPlugins=&assumptions=%7B%7D), [but swc does not](https://play.swc.rs/?version=1.2.146&code=H4sIAAAAAAAAA0utKMgvKlHISS1RCPYPDXJ29XUMCPD0c48PDfJRsFVQL84vLUpO9U1Ut%2BbClNcGKigoyMxLB3KACvT1sZhRnpmTo5CUqqAEM0kJALAfEw5zAAAA&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1t93kDj2EcJXg4B8aBWqM714bUrKSmPdmOp3wtHWqrBBdH1o2%2FtJG4hPDa6hGbmoz2jlChiNjPcSWgtdksRTITR2lkMPe1pIvqaoAD%2BJ8xL855lAqn2sFnazVeVcllXyCxjN0lwPet216yfgBCKaI9boAAAA%3D).
code snippet come from rollup https://github.com/rollup/rollup/blob/511e9ae226869606b0a03071787d358901ed968a/src/utils/sourceMappingURL.ts#L3
please see these links

### Input code

```typescript
export let SOURCEMAPPING_URL = 'sourceMa';
SOURCEMAPPING_URL += 'ppingURL';
// SOURCEMAPPING_URL will be "sourceMa"
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "commonjs"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.146&code=H4sIAAAAAAAAA0utKMgvKlHISS1RCPYPDXJ29XUMCPD0c48PDfJRsFVQL84vLUpO9U1Ut%2BbClNcGKigoyMxLB3KACvT1sZhRnpmTo5CUqqAEM0kJALAfEw5zAAAA&config=H4sIAAAAAAAAA0WMSwrDMAxE76K1t93kDj2EcJXg4B8aBWqM714bUrKSmPdmOp3wtHWqrBBdH1o2%2FtJG4hPDa6hGbmoz2jlChiNjPcSWgtdksRTITR2lkMPe1pIvqaoAD%2BJ8xL855lAqn2sFnazVeVcllXyCxjN0lwPet216yfgBCKaI9boAAAA%3D

### Expected behavior

if we import "SOURCEMAPPING_URL" we should get "sourceMappingURL".

### Actual behavior

if we import "SOURCEMAPPING_URL" we get "sourceMa".

### Version

1.2.146

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

Some fun facts:

```javascript
ident = expr;
```
the LHS is parsed as `PatOrExpr::Pat`

```javascript
ident += expr;
```

the LHS is parsed as `PatOrExpr::Expr`

**BREAKING CHANGE:**

**Related issue (if exists):**
- fix #3898

### CODE REVIEW

File: crates/swc_ecma_transforms_module/src/util.rs [hunk 1]
```diff
@@ -759,63 +765,63 @@ impl Scope {
...
-                                    left: PatOrExpr::Pat(i.into()),
-                                    ..expr
-                                });
-                                let e = chain_assign!(entry, Box::new(expr));
-
-                                *e
-                            }
-                            _ => Expr::Assign(AssignExpr {
-                                left: PatOrExpr::Pat(i.into()),
+                if let Some(binding_ident) = match expr.left {
```
Comment (kdy1) [inline crates/swc_ecma_transforms_module/src/util.rs:768]: Please use `expr.left.as_ident()` instead.

**Review by kdy1 — CHANGES_REQUESTED** [review]
Thank you!

**Review by kdy1 — APPROVED** [review]
LGTM. Thanks!

---


swc-bump:
 - swc_ecma_transforms_module
