### PR TITLE
fix(es/parser): Report error for exported reserved name

### LINKED ISSUE #8268: passing `export { default }` to the parser should throw an error
### Describe the bug

Keywords cannot be used in `export` but SWC parser doesn't reject them.

### Input code

```typescript
export { default }
export { if }
export { default as foo }
export { if as bar }
```

### Config

_No response_

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.97&code=H4sIAAAAAAAAA0utKMgvKlGoVkhJTUsszSlRqOXlSoWJZaahcGFKEosV0vLz0VUCRZMSi0CiACqxTW9UAAAA&config=H4sIAAAAAAAAA1VPOw7DIAzdOQXy3KFi6NA79BCIOhERBGQTqSjK3UsIpM3m9%2FOzVyElTGzgKdcyFhA1MdKJC8N5TvpTGEDjNRuyMcGtqxPv0qAdY6W2Q4GkacRUU6zuSrUEuBAYe6Jx3s52yP%2BdJvhIyHw17lY9jw6vjaK1gg%2FvpYrtl5QjHhc84GfqZedisPzqyUQLiu0LtK2NIRcBAAA%3D

### SWC Info output

_No response_

### Expected behavior

Throws an error like `Unexpected keyword "default"`.

### Actual behavior

No error happens.

### Version

1.3.97

### Additional context

This errors with most parsers on https://astexplorer.net/.

### PR DESCRIPTION
**Pull request by magic-akari**
**Related issue:**

- Closes #8268.

### CODE REVIEW

File: crates/swc_ecma_parser/src/error.rs [hunk 1]
```diff
@@ -198,7 +198,7 @@ pub enum SyntaxError {
 
     TrailingCommaInsideImport,
 
-    ExportDefaultWithOutFrom,
```
Comment (kdy1) [inline crates/swc_ecma_parser/src/error.rs:201]: Can we keep this variant? Maybe with `#[deprecated]`. Removing a variant is a breaking change.

File: crates/swc_ecma_parser/src/parser/stmt/module_item.rs [hunk 2]
```diff
@@ -649,17 +645,30 @@ impl<I: Tokens> Parser<I> {
...
+                    expect!(self, "from");
                 }
-                if let Some(span) = string_export_binding_span {
-                    syntax_error!(self, span, SyntaxError::ExportBindingIsString);
+
+                for s in &specifiers {
+                    if let ExportSpecifier::Named(named) = s {
+                        match &named.orig {
+                            ModuleExportName::Ident(id) if id.is_reserved() => {
+                                syntax_error!(
```
Comment (kdy1) [inline crates/swc_ecma_parser/src/parser/stmt/module_item.rs:656]: Let's use `emit_err` instead.

File: crates/swc_ecma_parser/src/parser/stmt/module_item.rs [hunk 3]
```diff
@@ -649,17 +645,30 @@ impl<I: Tokens> Parser<I> {
...
+                                    self,
+                                    id.span,
+                                    SyntaxError::ExportExpectFrom(id.sym.clone())
+                                );
+                            }
+                            ModuleExportName::Str(s) => {
+                                syntax_error!(self, s.span, SyntaxError::ExportBindingIsString);
```
Comment (kdy1) [inline crates/swc_ecma_parser/src/parser/stmt/module_item.rs:663]: Same here. We can recover from the error from here easily.

**Review by kdy1 — CHANGES_REQUESTED** [review]
Thank you!

---


swc-bump: 
 - swc_ecma_parser

**Review by kdy1 — APPROVED** [review]
---

Thank you!
