### PR TITLE
fix(es/transforms/cjs): Preserve order of imports for reexports

### LINKED ISSUE #2594: Existing order of generated requires/defines can be problematic for inter-dependency relationships
**Describe the bug**

When importing from multiple modules, the current version of `swc` generates all of its `require` statements up front, followed by all of its `Object.defineProperty()` calls later.  You'll notice that `babel` does these one at a time, and this is important under certain conditions.  Consider the following input code:

**Input code**

```
export * from "./A";
export * from "./B";
```

The compiled commonjs results in:

```
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
var _exportNames = {
};
var _a = _interopRequireWildcard(require("./A")); // <- all of the requires first
var _b = _interopRequireWildcard(require("./B")); // <- all of the requires first
function _interopRequireWildcard(obj) {
    if (obj && obj.__esModule) {
        return obj;
    } else {
        var newObj = {
        };
        if (obj != null) {
            for(var key in obj){
                if (Object.prototype.hasOwnProperty.call(obj, key)) {
                    var desc = Object.defineProperty && Object.getOwnPropertyDescriptor ? Object.getOwnPropertyDescriptor(obj, key) : {
                    };
                    if (desc.get || desc.set) {
                        Object.defineProperty(newObj, key, desc);
                    } else {
                        newObj[key] = obj[key];
                    }
                }
            }
        }
        newObj.default = obj;
        return newObj;
    }
}
Object.keys(_a).forEach(function(key) {
    if (key === "default" || key === "__esModule") return;
    if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
    if (key in exports && exports[key] === _a[key]) return;
    Object.defineProperty(exports, key, { // <- finally, our defineProperty calls
        enumerable: true,
        get: function() {
            return _a[key];
        }
    });
});
Object.keys(_b).forEach(function(key) {
    if (key === "default" || key === "__esModule") return;
    if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;
    if (key in exports && exports[key] === _b[key]) return;
    Object.defineProperty(exports, key, {. // <- finally, our defineProperty calls
        enumerable: true,
        get: function() {
            return _b[key];
        }
    });
});
```

`babel` produces a pattern that "interweaves" them (`require, defineProperty, require, defineProperty`):

```
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _A = require("./A");

Object.keys(_A).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  if (key in exports && exports[key] === _A[key]) return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _A[key];
    }
  });
});

var _B = require("./B");

Object.keys(_B).forEach(function (key) {
  if (key === "default" || key === "__esModule") return;
  if (key in exports && exports[key] === _B[key]) return;
  Object.defineProperty(exports, key, {
    enumerable: true,
    get: function get() {
      return _B[key];
    }
  });
});
```

**Config**

```json
{
    "test": ".*.js$",
    "module": {
      "type": "commonjs"
    },
    "jsc": {
      "parser": {
        "syntax": "ecmascript",
        "jsx": true
      },
      "transform": {
          "react": {
              "runtime": "automatic"
          }
      },
      "loose": true
    }
  },
```

**Expected behavior**
Everything will compile, and quite often, bundlers such as `webpack` will get the resolutions correctly.  However, I've found `jest` for example, when importing the above example, may encounter a class from `B` that depends on `A`.  This breaks, because `A` hasn't been defined yet because the `defineProperty` hasn't been declared yet, resulting in a class construction with an `undefined` value for `A`.

By taking the `swc` output, and simply moving the requires around, everything runs just fine.

**Version**
The version of @swc/core:

```
@swc/cli: 0.1.51
@swc/core: 1.2.105
```

**Additional context**

### PR DESCRIPTION
**Pull request by kwonoj**
- closes #2594.

This PR attempts to order of the imports / reexports in transpiled runtime codebase. #2594 itself sufficiently explains the issue itself. It could be an implementation detail but so far based on observation tsc / babel works in the same way, which makes think it'd better to align as well. As issue described normally this won't appear but if there's some sort of circular dependencies, or reexports have dependencies across each other it may reveal different behavior.

For the change itself, PR changes the order of injecting handled export_all stmt by putting it after require stmt is created. In result, export_all stmt doesn't use extra_stmt (which appends to stmt at the end). Also changed `exports_alls` to map to stmt itself - when encountering ExportAll stmt it is gauranteed we'll need stmt anyway - hashmap contains generated stmt instead of only keeping name of export. This allowed easier lookup at the end.

Lastly, I noticed there is prior test cases from https://github.com/swc-project/swc/pull/133/ (https://github.com/swc-project/swc/pull/133/files#diff-6d08f604fc5444313bf8d80ca76a84f5abbc95129eb4e1311592637fbb17b089R1075) , looks like it is coming from original transform impl. Test cases are updated without adding new one.

### CODE REVIEW

**Comment by JeremyGrieshop** [comment]
Thank you for tackling this!  I suspect the test cases for my recent merge (`tests/fixture/issue-2548/`) also need to be updated in order for the workflow tests to pass.

**Comment by kwonoj** [comment]
> Thank you for tackling this! I suspect the test cases for my recent merge (tests/fixture/issue-2548/) also need to be updated in order for the workflow tests to pass.

Thanks, I tried to update test cases as well.

File: tests/fixture/issue-2548/case2/output/index.js [hunk 1]
```diff
@@ -8,10 +8,17 @@ Object.defineProperty(exports, "X", {
         return _z.default;
     }
 });
-var _exportNames = {
```
Comment (JeremyGrieshop) [inline tests/fixture/issue-2548/case2/output/index.js:11]: I'm afraid the current PR may actually regress issue #2548 in this state.

Here, _exportNames is removed by this PR in this case.  Which means, later on we will may an `Object.defineProperty()` for `X`, if `X` is exported by `Z` using `export * from "./Z"`.  This will result in multiple calls to `Object.defineProperty` for the same property.

File: tests/fixture/issue-2548/case2/output/index.js [hunk 2]
```diff
@@ -8,10 +8,17 @@ Object.defineProperty(exports, "X", {
...
-    X: true
-};
 var _z = _interopRequireWildcard(require("./Z"));
+Object.keys(_z).forEach(function(key) {
+    if (key === "default" || key === "__esModule") return;
+    if (key in exports && exports[key] === _z[key]) return;
+    Object.defineProperty(exports, key, {
```
Comment (JeremyGrieshop) [inline tests/fixture/issue-2548/case2/output/index.js:15]: Here is where the call to `Object.defineProperty` can throw the error.  Previously, we injected:

`if (Object.prototype.hasOwnProperty.call(_exportNames, key)) return;`

to guard against this.

Comment (kwonoj) [reply tests/fixture/issue-2548/case2/output/index.js:15]: This is something I'm thinking around, there was previously condition to check if there are multiple exports which couldn't be used with changed.

File: ecmascript/transforms/module/src/common_js.rs [hunk 3]
```diff
@@ -84,7 +84,10 @@ where
 
         let mut exports = vec![];
         let mut initialized = IndexSet::default();
-        let mut export_alls = vec![];
+
+        let mut export_alls: AHashMap<JsWord, ModuleItem> = Default::default();
```
Comment (kdy1) [inline ecmascript/transforms/module/src/common_js.rs:88]: I think storing `ModuleItem` in a hash map will be very slow, due to `memmove`.
`ModuleItem` is a big struct, so I think this case be performance issue.

File: ecmascript/transforms/module/src/common_js.rs [hunk 4]
```diff
@@ -174,14 +177,71 @@ where
...
+                                stmts.push(ModuleItem::Stmt(Stmt::Decl(Decl::Var(VarDecl {
+                                    span: DUMMY_SP,
+                                    kind: VarDeclKind::Var,
+                                    decls: vec![VarDeclarator {
+                                        span: DUMMY_SP,
+                                        name: Pat::Ident(exported_names_ident.clone().into()),
+                                        init: Some(Box::new(Expr::Object(ObjectLit {
+                                            span: DUMMY_SP,
+                                            props: exports
+                                                .clone()
```
Comment (kdy1) [inline ecmascript/transforms/module/src/common_js.rs:204]: Is this clone necessary?

**Review by kdy1 — COMMENTED** [review]
Thank you!

I have some concerns about changes.

File: ecmascript/transforms/module/src/common_js.rs (hunk 3 above)
Comment (kwonoj) [reply ecmascript/transforms/module/src/common_js.rs:88]: good point, was thinking that too but wasn't sure about actual implication so didn't try early optimizations. any suggestions?

File: ecmascript/transforms/module/src/common_js.rs (hunk 4 above)
Comment (kwonoj) [reply ecmascript/transforms/module/src/common_js.rs:204]: If I recall corretly yes, there was a move occurred somewhere.

File: ecmascript/transforms/module/src/common_js.rs (hunk 3 above)
Comment (kwonoj) [reply ecmascript/transforms/module/src/common_js.rs:88]: The reason I created moduleitem early is at the moment pushing stmt (https://github.com/swc-project/swc/pull/2598/files#diff-506530d02689c3c49a06cbec6fb8c9ffd7b1df4c551dcac29d8bd08d0248590fR712) there's mutable borrow to scope exists, so can't call `handle_export_all`. Curious if there's easy workaround.

**Comment by JeremyGrieshop** [comment]
This may possibly resolve https://github.com/swc-project/swc/issues/1733, too.

File: ecmascript/transforms/module/src/common_js.rs [hunk 5]
```diff
@@ -699,6 +704,15 @@ where
                     stmts.push(require.into_stmt().into());
                 }
             }
+
+            let exported = export_alls.remove(&src);
+            if let Some(export) = exported {
+                stmts.push(ModuleItem::Stmt(Scope::handle_export_all(
```
Comment (kwonoj) [inline ecmascript/transforms/module/src/common_js.rs:710]: Curious if this approach makes sense? it was not possible to call `handle_export_all` due to move occurrence, I took out part to create Ident (which required &mut self) hold by hashmap, and actual stmt creation occurs in here.

Comment (kdy1) [reply ecmascript/transforms/module/src/common_js.rs:710]: Yes, I think it's correct approach.

**Review by kdy1 — APPROVED** [review]
LGTM.
I found one issue, but it's not related to this PR.
I'll patch it after merging this. Thanks!

File: ecmascript/transforms/module/src/common_js.rs (hunk 3 above)
Comment (kdy1) [reply ecmascript/transforms/module/src/common_js.rs]: What you did is right.
Storing only minimum information to create `ModuleItem` and actually create big structs (`ModuleItem` in this case) works.

**Comment by kwonoj** [comment]
Appreciate for the review for both, @kdy1 and @JeremyGrieshop :bow:
