### PR TITLE
refact(ecma/transform/react): use VisitMut for refresh

### LINKED ISSUE #2261: Missing refresh signature for hook calls outside of assignments
**Describe the bug**

If a React hook call isn't assigned but instead used in an expression, then the refresh transformer doesn't seem to recognize it and create a hash.

(This is a valid hook call, and the React Hooks eslint rule doesn't complain)

**Input code**

```js
import { useState } from "react";

export function App() {
	console.log(useState())

	return null;
}
```

**Config**

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    },
    "transform": {
      "react": {
        "refresh": true,
        "development": true
      }
    }
  }
}

```

**Current behaviour** 

```js
import { useState } from "react";
export function App() {
    console.log(useState());
    return null;
}
_c = App;
var _c;
$RefreshReg$(_c, "App");
```

**Expected behavior**
With the offical `react-refresh/babel` plugin:

```js
var _s = $RefreshSig$();

import { useState } from "react";
export function App() {
  _s();

  console.log(useState());
  return null;
}

_s(App, "VhlnxxH3xh7Qs17KADUJ8wvRSZs=");

_c = App;

var _c;

$RefreshReg$(_c, "App");
```

**Version**
20ce326909670d0e40c9f1bbd804387c2958eae6

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

migrate react refresh transform to `VisitMut`

**BREAKING CHANGE:**

**Related issue (if exists):**
closes #2261 too

### CODE REVIEW

File: crates/swc_ecma_transforms_react/src/refresh/hook.rs [hunk 1]
```diff
@@ -0,0 +1,523 @@
...
+                .collect(),
+            declare: false,
+        }))
+    }
+
+    // The second call is around the function itself. This is used to associate a
+    // type with a signature.
+    // Unlike with $RefreshReg$, this needs to work for nested declarations too.
+    fn wrap_with_register(&self, handle: Ident, func: Expr, hooks: Vec<Hook>) -> Expr {
+        let mut args = vec![func];
```
Comment (kdy1) [inline crates/swc_ecma_transforms_react/src/refresh/hook.rs:81]: I think changing the type of `args` to `Vec<ExprOrSpread>` will be better for performance as it reduces memory operations.

Comment (kdy1) [reply crates/swc_ecma_transforms_react/src/refresh/hook.rs:81]: You can use `let mut args = vec![func.as_arg()];` instead.

File: crates/swc_ecma_transforms_react/src/refresh/hook.rs [hunk 2]
```diff
@@ -0,0 +1,523 @@
...
+        args.push(Expr::Lit(Lit::Str(Str {
+            span: DUMMY_SP,
+            value: sign.into(),
+            has_escape,
+            kind: StrKind::Synthesized,
+        })));
+
+        let mut should_reset = self.should_reset;
+
+        let mut custom_hook_in_scope = Vec::new();
```
Comment (kdy1) [inline crates/swc_ecma_transforms_react/src/refresh/hook.rs:126]: Same here. `Vec<ExprOrSpread>` will avoid memory operations.

File: crates/swc_ecma_transforms_react/src/refresh/hook.rs [hunk 3]
```diff
@@ -0,0 +1,523 @@
...
+
+    fn visit_mut_block_stmt(&mut self, b: &mut BlockStmt) {
+        let mut current_scope = IndexSet::new();
+
+        // TODO: merge with collect_decls
+        for stmt in &b.stmts {
+            stmt.collect_ident(&mut current_scope);
+        }
+        let orig_binding = self.scope_binding.len();
+        self.scope_binding.extend(current_scope.into_iter());
```
Comment (kdy1) [inline crates/swc_ecma_transforms_react/src/refresh/hook.rs:225]: Is `.into_iter()` required?
`.extend` accepts `impl IntoIterator` so this seems redundant.

File: crates/swc_ecma_transforms_react/src/refresh/hook.rs [hunk 4]
```diff
@@ -0,0 +1,523 @@
...
+        }?;
+        let name = if IS_HOOK_LIKE.is_match(&ident.sym) {
+            Some(ident)
+        } else {
+            None
+        }?;
+        let mut key = if let Some(name) = lhs {
+            self.cm
+                .span_to_snippet(name.span())
+                .unwrap_or("".to_string())
```
Comment (kdy1) [inline crates/swc_ecma_transforms_react/src/refresh/hook.rs:438]: I think we should use `unwrap_or_else` or `.unwrap_or(String::new())`.

Maybe specialization used by std may optimize this, but just to be safe.

File: crates/swc_ecma_transforms_react/src/refresh/hook.rs [hunk 5]
```diff
@@ -0,0 +1,523 @@
...
+        } else {
+            "".to_string()
```
Comment (kdy1) [inline crates/swc_ecma_transforms_react/src/refresh/hook.rs:440]: Same here

File: crates/swc_ecma_transforms_react/src/refresh/hook.rs [hunk 6]
```diff
@@ -0,0 +1,523 @@
...
+        };
+        // Some built-in Hooks reset on edits to arguments.
+        if &name.sym == "useState" && expr.args.len() > 0 {
+            // useState first argument is initial state.
+            key += &format!(
+                "({})",
+                self.cm
+                    .span_to_snippet(expr.args[0].span())
+                    .unwrap_or("".to_string())
```
Comment (kdy1) [inline crates/swc_ecma_transforms_react/src/refresh/hook.rs:449]: Same here

File: crates/swc_ecma_transforms_react/src/refresh/hook.rs [hunk 7]
```diff
@@ -0,0 +1,523 @@
...
+            );
+        } else if &name.sym == "useReducer" && expr.args.len() > 1 {
+            // useReducer second argument is initial state.
+            key += &format!(
+                "({})",
+                self.cm
+                    .span_to_snippet(expr.args[1].span())
+                    .unwrap_or("".to_string())
```
Comment (kdy1) [inline crates/swc_ecma_transforms_react/src/refresh/hook.rs:457]: Same here

File: crates/swc_ecma_transforms_react/src/refresh/mod.rs [hunk 8]
```diff
@@ -497,24 +174,24 @@ impl<C: Comments> Refresh<C> {
...
                 reg.push((reg_ident.clone(), reg_str));
                 if let Persist::Hoc(hoc) =
-                    self.get_persistent_id_from_possible_hoc(expr, reg, ignore)
+                    self.get_persistent_id_from_possible_hoc(expr, reg, hook_reg)
                 {
-                    *first_arg = Box::new(make_assign_stmt(reg_ident.clone(), first_arg.take()));
-                    if let Some(hook) = &hoc.hook {
-                        let span = call_expr.span;
-                        let first = ExprOrSpread {
+                    let mut first = first_arg.take();
```
Comment (kdy1) [inline crates/swc_ecma_transforms_react/src/refresh/mod.rs:179]: This will make the output invalid if `hoc.hook` is `None`.

I'm not sure if this is possible, though.

File: crates/swc_ecma_transforms_react/src/refresh/mod.rs [hunk 9]
```diff
@@ -497,24 +174,24 @@ impl<C: Comments> Refresh<C> {
...
+                        let mut args = vec![ExprOrSpread {
                             spread: None,
-                            expr: Box::new(Expr::Call(call_expr.take())),
-                        };
-                        let mut args = vec![first];
-                        args.extend(hook.args.clone());
-                        *call_expr = CallExpr {
+                            expr: first,
+                        }];
+                        args.append(&mut rest_arg.clone());
```
Comment (kdy1) [inline crates/swc_ecma_transforms_react/src/refresh/mod.rs:186]: `args.extend(hook.args.clone());` seems better because of specializations.

File: crates/swc_ecma_transforms_react/src/refresh/mod.rs [hunk 10]
```diff
@@ -869,12 +383,20 @@ impl<C: Comments> Fold for Refresh<C> {
...
+            if let Persist::Hoc(_) = persistent_id {
+                // we need to make hook transform happens after component for
+                // HOC
+                items.push(item);
+            } else {
+                item.visit_mut_children_with(&mut hook_visitor);
+                self.scope_binding.truncate(current_binding);
+
+                items.push(item);
+                let stmts = hook_visitor.extra_stmt.take();
```
Comment (kdy1) [inline crates/swc_ecma_transforms_react/src/refresh/mod.rs:395]: `items.extend(hook_visitor.extra_stmt.take().into_iter().map(ModuleItem::Stmt))` would be better for performance because of `TrustedLen`.

**Review by kdy1 — CHANGES_REQUESTED** [review]
Thank you!

File: crates/swc_ecma_transforms_react/src/refresh/mod.rs (hunk 8 above)
Comment (Austaras) [reply crates/swc_ecma_transforms_react/src/refresh/mod.rs:179]: It won't, see L194

**Review by kdy1 — APPROVED** [review]
LGTM. Thanks!
