### PR TITLE
fix(es/transforms): handle member obj in missing else branch

### LINKED ISSUE #7025: Wrong output for "jsc.transform.constModules" configuration with object const
### Describe the bug

After update from **v1.3.37** to **v1.3.38** we noticed different output for [**jsc.transform.constModules**](https://swc.rs/docs/configuration/compilation#jsctransformconstmodules) for modules that contain non-primitive data.

### Input code

```typescript
import { testMap } from "testModule";
testMap['var'];
```

### Config

```json
{
  "jsc": {
    "target": "es2021",
    "parser": {
      "syntax": "typescript"
    },
    "transform": {
      "constModules": {
        "globals": {
          "testModule": {
            "testMap": "{ 'var': 'value' }"
          }
        }
      }
    }
  }
}
```

### Playground link

https://play.swc.rs/?version=1.3.38&code=H4sIAAAAAAAAA8vMLcgvKlGoVihJLS7xTSxQqFVIK8rPVVAC8%2FNTSnNSlay5oJLR6mWJReqx1gD907e3NQAAAA%3D%3D&config=H4sIAAAAAAAAAz1MOw6DMAy9CvKShYEy5g4cwg0GtUqTyDYVKMrd61Rq3%2FK%2BehWeEsBXKMhC3JVcSfEED3oVksCPotBGUMYkW%2BZX34ScRJe8HpGk%2Bz3mO8avVPo1f4fF3urg3sjOd4oHuaFBM9gx8k5qC5J5mm%2BWfgDY4jojlQAAAA%3D%3D

### Expected behavior

Output has to be like in v1.3.37 and earlier:
```
({
    'var': 'value'
})['var'];
```

### Actual behavior

```
testMap['var'];
```

### Version

v1.3.38

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
- fix #7025

### CODE REVIEW

File: crates/swc_ecma_transforms_optimization/src/const_modules.rs [hunk 1]
```diff
@@ -161,11 +161,11 @@ impl VisitMut for ConstModules {
                 }
             }
             Expr::Member(MemberExpr { obj, prop, .. }) if obj.is_ident() => {
-                let member_obj = obj.as_ident().unwrap();
-
-                if self.scope.namespace.contains(&member_obj.to_id()) {
-                    let module_name = &member_obj.sym;
-
+                if let Some(module_name) = obj
```
Comment (magic-akari) [inline crates/swc_ecma_transforms_optimization/src/const_modules.rs:164]: I did not manage to move this `if` statement to the match arm.

**Review by kdy1 — APPROVED** [review]
Thanks!

---

swc-bump:
 - swc_ecma_transforms_optimization
