### PR TITLE
fix(es/minifier): Allow MultiReplacer to inline multiple times

### LINKED ISSUE #11102: inlining of function calls produces broken code
### Describe the bug

inlined function call still references variables from closures that no longer exist. Failing test in https://github.com/swc-project/swc/pull/11101

### Input code

```typescript
const decideZoomByAccuracy = (range) => {
    const isUnder = (accuracy) => {
        return range <= accuracy;
    };
    if (isUnder(0)) {
        return 15;
    }
    if (isUnder(50)) {
        return 15;
    }
    if (isUnder(100)) {
        return 15;
    }
    return 11;
};
export const zoom = decideZoomByAccuracy(75);
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2024",
    "loose": false,
    "minify": {
      "compress": {
        "arguments": false,
        "arrows": true,
        "booleans": true,
        "booleans_as_integers": false,
        "collapse_vars": true,
        "comparisons": true,
        "computed_props": true,
        "conditionals": true,
        "dead_code": true,
        "directives": true,
        "drop_console": false,
        "drop_debugger": true,
        "evaluate": true,
        "expression": false,
        "hoist_funs": false,
        "hoist_props": true,
        "hoist_vars": false,
        "if_return": true,
        "join_vars": true,
        "keep_classnames": false,
        "keep_fargs": true,
        "keep_fnames": false,
        "keep_infinity": false,
        "loops": true,
        "negate_iife": true,
        "properties": true,
        "reduce_funcs": false,
        "reduce_vars": false,
        "side_effects": true,
        "switches": true,
        "typeofs": true,
        "unsafe": false,
        "unsafe_arrows": false,
        "unsafe_comps": false,
        "unsafe_Function": false,
        "unsafe_math": false,
        "unsafe_symbols": false,
        "unsafe_methods": false,
        "unsafe_proto": false,
        "unsafe_regexp": false,
        "unsafe_undefined": false,
        "unused": true,
        "const_to_let": true,
        "pristine_globals": true
      },
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": "unknown"
}
```

### Link to the code that reproduces this issue

https://play.swc.rs/?version=1.13.5&code=H4sIAAAAAAAAA0vOzysuUUhJTc5MSY3Kz891qnRMTi4tSkyuVLBV0ChKzEtP1VSwtVOo5lIAgmSw6szi0LyU1CKQgkSoYiQ1IFCUWlJalKcA1q5gY6sAU2YNVlELoTLTFDSgRmkYaGpiajc0harHUG5KonpDAyI0wAQNrbmALkytKMgvKoH6uAoYMkDvYgsmDXNTTWsuAKwTnAFHAQAA&config=H4sIAAAAAAAAA32US47bMAyG9zlF4HUXxaCYRQ%2FQXc8gKBblaEYWDZFKYgxy91K28%2BiE9s7mx5%2BUSIpfu%2F2%2B%2BaC2%2Bb3%2Fkk%2F5GWwmyPd%2FsdCY2F7E0vA4ALU5DNz8uFGmiryNBJPpOpOGbe6Aqwro7efbr0XRRESCm2Kx9SEFPz7nbLEfMhA92cQqIUsPiel%2F%2FcIynivgXJ7tB8QINm0QY8mExNBB1gK3GKMdCMzJZiVKPanNgVBLUWFhcGbIOKg8ucABk%2BR8pQ6sMy06UFDI0HI4gSaTXCJLJNdT7jNhB4fSdVOfv6nhZGOxrOSEy9QSOa0S9YiB2PiStBLOcKUGM1yK%2B10ZvMnAJadX3QeGtNKTTwCpQLREyfagxZ08vMzTmtpvKkPyMrI8KlzmW7tlgk6KakLwSmVrZSBz0LqZwZUWamVb7TgLXikfBQcGvJdZUULTOXB71JLWh45eAdJf67WpmoG5v8IVXh%2FEBv4jt2R9wBaP3vJxndLYHzBuJOiBj%2Bg2HKQVjOs4y5a4DOu8JAcyGuBUl0ITeF0C8gAYTZz25ctsyPOQiKaLeHisicXhet%2FDvU3d473Pq3i3ODQ9ujLBZcnX%2Fs6r%2Bb15ON228P3gTaC%2FN6Uc%2FzPhOTW76z%2FccfKONQYAAA%3D%3D

### SWC Info output

_No response_

### Expected behavior

Code that doesn't produce `ReferenceError`. Ideally `export const zoom = 15`

### Actual behavior

_No response_

### Version

1.13.5

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

The semantic of `NormalMultiRepalcer` becomes dubious after this PR. Do we have another inliner?

**BREAKING CHANGE:**

**Related issue (if exists):**
Closes #11102

### CODE REVIEW

File: crates/swc_ecma_minifier/src/compress/optimize/util.rs [hunk 1]
```diff
@@ -498,6 +500,15 @@ impl<'a> NormalMultiReplacer<'a> {
 
         e.visit_mut_children_with(self);
 
+        let e = if self.should_consume {
```
Comment (kdy1) [inline crates/swc_ecma_minifier/src/compress/optimize/util.rs:503]: Can we branch bit earlier to avoid `remove()` + `insert()` for `!self.should_consume` cases?

**Comment by kdy1** [comment]
> The semantic of NormalMultiRepalcer becomes dubious after this PR. Do we have another inliner?

We have `Finalizer`, which has very similar semantic

File: crates/swc_ecma_minifier/src/compress/optimize/util.rs (hunk 1 above)
Comment (Austaras) [reply crates/swc_ecma_minifier/src/compress/optimize/util.rs:503]: No since we do an inline for the value itself, it's necessary to avoid inline the value itself into its content(think recursive function).

**Review by kdy1 — APPROVED** [review]

**Comment by Austaras** [comment]
> > The semantic of NormalMultiRepalcer becomes dubious after this PR. Do we have another inliner?
> 
> We have `Finalizer`, which has very similar semantic

Which departure further from the intended behavior. Maybe just settle with `NormalMultiRepalcer`.
