### PR TITLE
fix(es/compat): use define for non-spread props

### LINKED ISSUE #4631: Bug: Object getter is statically evaluated when used with object spread
### Describe the bug

Object getter is statically evaluated when used with object spread

### Input code

```typescript
const b = {}
const a = {
	...b,
	get c() {
		console.log('get c')
	}
}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.181&code=H4sIAAAAAAAAA0vOzysuUUhSsFWoruVKBnMSQRwuTj09vSQdLs701BKFZA1NkAgnSD4%2FJ1UvJz9dQx0soa7JxVnLVcsFALEMklZHAAAA&config=H4sIAAAAAAAAA0WMTQrEIAxG75K1286id5hDBCctFv9IUhgR714tlu7C915ehUMsrBUyshCPS0pU%2FMMKZAOKZZcVTNf6tKEXagYUeScdiiyd%2BZSEJjUQXHRbGSWbQmYSeRHG3T9m66GQfucYKmjJdAc%2F0N7G%2FHPynaLySe0Cj9ke9LUAAAA%3D

### Expected behavior

`a.c; a.c` should print `get c` twice

### Actual behavior

`a.c; a.c` should print nothing, `get c` is printed once statically.

See [babel playground](https://babeljs.io/repl/#?browsers=&build=&builtIns=entry&corejs=3.6&spec=true&loose=false&code_lz=MYewdgzgLgBARjAvDA3gXwFCkrAhk1DASADoy4AaYgcwFNZgAKASkKKOwhABtaTuQ1RgHI6DYc2KZMQA&debug=false&forceAllTransforms=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=true&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=true&targets=&version=7.17.11&externalPlugins=&assumptions=%7B%7D)

### Version

1.2.181

### Additional context

SWC output:

```javascript
function _defineProperty(obj, key, value) {
    if (key in obj) {
        Object.defineProperty(obj, key, {
            value: value,
            enumerable: true,
            configurable: true,
            writable: true
        });
    } else {
        obj[key] = value;
    }
    return obj;
}
function _objectSpread(target) {
    for(var i = 1; i < arguments.length; i++){
        var source = arguments[i] != null ? arguments[i] : {};
        var ownKeys = Object.keys(source);
        if (typeof Object.getOwnPropertySymbols === "function") {
            ownKeys = ownKeys.concat(Object.getOwnPropertySymbols(source).filter(function(sym) {
                return Object.getOwnPropertyDescriptor(source, sym).enumerable;
            }));
        }
        ownKeys.forEach(function(key) {
            _defineProperty(target, key, source[key]);
        });
    }
    return target;
}
var b = {};
var a = _objectSpread({}, b, {
    get c () {
        console.log("get c");
    }
});

```

Babel output:

```javascript
"use strict";

function ownKeys(object, enumerableOnly) {
  var keys = Object.keys(object);
  if (Object.getOwnPropertySymbols) {
    var symbols = Object.getOwnPropertySymbols(object);
    enumerableOnly &&
      (symbols = symbols.filter(function (sym) {
        return Object.getOwnPropertyDescriptor(object, sym).enumerable;
      })),
      keys.push.apply(keys, symbols);
  }
  return keys;
}

function _objectSpread(target) {
  for (var i = 1; i < arguments.length; i++) {
    var source = null != arguments[i] ? arguments[i] : {};
    i % 2
      ? ownKeys(Object(source), !0).forEach(function (key) {
          _defineProperty(target, key, source[key]);
        })
      : Object.getOwnPropertyDescriptors
      ? Object.defineProperties(
          target,
          Object.getOwnPropertyDescriptors(source)
        )
      : ownKeys(Object(source)).forEach(function (key) {
          Object.defineProperty(
            target,
            key,
            Object.getOwnPropertyDescriptor(source, key)
          );
        });
  }
  return target;
}

function _defineProperty(obj, key, value) {
  if (key in obj) {
    Object.defineProperty(obj, key, {
      value: value,
      enumerable: true,
      configurable: true,
      writable: true
    });
  } else {
    obj[key] = value;
  }
  return obj;
}

var b = {};

var a = _objectSpread(
  _objectSpread({}, b),
  {},
  {
    get c() {
      console.log("get c");
    }
  }
);

```

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**

So, for following code
```js
({...a, b , ...c, c})
```

At first, I tried to copy babel's behavior, which would be
```js
_objectSpread(
  _objectSpread(
    _objectSpread({}, a),
    {},
    {
      b
    },
    c
  ),
  {},
  {
    c
  }
);
``` 

which seems a bit redundant, but it's necessary in babel's case: babel's helper `_objectSpread2`(swc copied `_objectSpread`) would only apply `getOwnPropertyDescriptors` for even targets, so it need an extra empty object for every non spread props, which doesn't seem to be optimal.

So I checkout esbuild and it would do
```js
var __spreadProps = (a, b) => __defProps(a, __getOwnPropDescs(b));

// project/index.ts
__spreadProps(__spreadValues(__spreadValues(__spreadProps(__spreadValues({}, a), { b }), c), d), { c });
```
which is more concise, but doesn't support loose.

So I took the third way, which introduces a new helper `objectSpreadProps` which is alike to `__spreadProps` and let `_objectSpread` remain the same.

This would result in an extra helper, but could reduce generated size and improve performance. I don't if it's the right thing to do.

**BREAKING CHANGE:**

**Related issue (if exists):**
closes #4631

### CODE REVIEW

**Comment by kdy1** [comment]
@kwonoj I think we should double-check this

**Comment by Austaras** [comment]
Yes, I'm also not quite sure about the correctness of this pr...

**Comment by kwonoj** [comment]
Initial glimpse looks ok, but not sure what test can ensure this other than we currently have in here.

**Comment by kdy1** [comment]
I'll try adding lots of execution tests for object rest/spread.
Let's see if it works...

**Comment by kdy1** [comment]
I updated the base branch as https://github.com/swc-project/swc/pull/4788 is merged

**Comment by kdy1** [comment]
Seems like we need `yarn link` for helpers...

**Comment by Austaras** [comment]
Or just don't `external_heleprs`

**Comment by kdy1** [comment]
Oh, I think it would be better.

Can you patch https://github.com/swc-project/swc/blob/bebdb8a8974d14e76f921a140fa04d49cb1ba438/crates/swc/tests/exec.rs#L80?

**Comment by Austaras** [comment]
Done.

File: packages/swc-helpers/src/_object_spread_props.js [hunk 1]
```diff
@@ -0,0 +1,30 @@
+function ownKeys(object, enumerableOnly) {
+  var keys = Object.keys(object);
+  if (Object.getOwnPropertySymbols) {
```
Comment (kdy1) [inline packages/swc-helpers/src/_object_spread_props.js:3]: https://caniuse.com/mdn-javascript_builtins_object_getownpropertysymbols

Hmm, it's not supported by ie11

File: packages/swc-helpers/src/_object_spread_props.js [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+      });
+    }
+    keys.push.apply(keys, symbols);
+  }
+  return keys;
+}
+
+export default function _objectSpreadProps(target, source) {
+  source = source != null ? source : {}
+  if (Object.getOwnPropertyDescriptors) {
```
Comment (kdy1) [inline packages/swc-helpers/src/_object_spread_props.js:17]: But well, this is supported by ie 11 so it's fine.

Comment (kdy1) [reply packages/swc-helpers/src/_object_spread_props.js:17]: https://caniuse.com/?search=getOwnPropertyDescriptor

File: packages/swc-helpers/src/_object_spread_props.js [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+    Object.defineProperties(target, Object.getOwnPropertyDescriptors(source));
+  } else {
+    ownKeys(Object(source)).forEach(function (key) {
```
Comment (kdy1) [inline packages/swc-helpers/src/_object_spread_props.js:20]: I'm not sure if a browser without `Object.getOwnPropertyDescriptors` will have `Array.forEach`

File: packages/swc-helpers/src/_object_spread_props.js (hunk 2 above)
Comment (kdy1) [reply packages/swc-helpers/src/_object_spread_props.js:17]: Do we really need this check?

**Review by kdy1 — COMMENTED** [review]
I'm simply not sure.
Btw, CI is passing, great work!

File: packages/swc-helpers/src/_object_spread_props.js (hunk 2 above)
Comment (Austaras) [reply packages/swc-helpers/src/_object_spread_props.js:17]: It's `getOwnPropertyDescriptors` and IE 11 doesn't support that.

File: packages/swc-helpers/src/_object_spread_props.js (hunk 1 above)
Comment (Austaras) [reply packages/swc-helpers/src/_object_spread_props.js:3]: It's for getting object symbol keys, and IE11 doesn't have symbol to begin with

File: packages/swc-helpers/src/_object_spread_props.js (hunk 2 above)
Comment (kdy1) [reply packages/swc-helpers/src/_object_spread_props.js:17]: Ah you are right, thank you!

File: packages/swc-helpers/src/_object_spread_props.js (hunk 3 above)
Comment (Austaras) [reply packages/swc-helpers/src/_object_spread_props.js:20]: Oh, that would be a problem

Comment (Austaras) [reply packages/swc-helpers/src/_object_spread_props.js:20]: Oh, IE support `Array#forEach` starting with 9

**Comment by kdy1** [comment]
Looks good, but I'll try some more verification

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_ecma_transforms_compat --breaking
