### PR TITLE
fix(es/parser): keep more comments around binop

### LINKED ISSUE #5783: One comment line is removed
### Describe the bug

One of the comments gets removed

### Input code

```typescript
function x(y) {
  return y && // 96 is one less than the char code
  // for "a" so this is checking that
  // it's a lowercase character
  false;
};
```

### Config

```json
{
  "$schema": "https://json.schemastore.org/swcrc",
  "jsc": {
    "parser": {
      "syntax": "ecmascript",
      "jsx": true
    },
    "target": "es2019",
    "transform": {
      "react": {
        "runtime": "automatic"
      }
    }
  },
  "isModule": true,
  "module": {
    "type": "es6"
  }
}
```

### Playground link

https://play.swc.rs/?version=1.2.249&code=H4sIAAAAAAAAAyWMwQrCQAxE7%2F2KoYeqp94E6deEmLWLywaSFC3ivxspDHOZ96ZsnaNqx%2Fu8X%2FAZAJPYrGPHNGGecbuiOrQLmrgjVupZAl7JwHqXVBIrahhphGuuKWR4FX7W%2Fvg7cVA1Tg5C05cYkx8vxCGWe6Hmsgzf5QefqlMMlAAAAA%3D%3D&config=H4sIAAAAAAAAAy2MSw6CUAxF99I4JKAOTGQPLqKpFR7xfdL2RQlh7xZwdnvv6VngpDRyROhhNCvad92kObVHq5aF2yxDpx8SggYmJegXKCjKsiWdk%2BHX35mcJwnFdswrk8prA4YysG2EXs%2BXu68mmPSVJW4CYSTbQ00WIjuI1XJECwTr6oKgj%2Fysbz6MDcT%2FtYDNhXfxzckfbCK5rswAAAA%3D

### Expected behavior

= Input

### Actual behavior

```js
function x(y) {
    return y && // for "a" so this is checking that
    // it's a lowercase character
    false;
}
;
```

### Version

1.2.249

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by RiESAEX**
**Description:**
attch comments to right of binExpr, instead of the operator

**BREAKING CHANGE:**

**Related issue (if exists):**
fix #5783

### CODE REVIEW

File: crates/swc_ecma_parser/src/lexer/state.rs [hunk 1]
```diff
@@ -316,6 +316,9 @@ impl<'a, I: Input> Iterator for Lexer<'a, I> {
 
         let span = self.span(start);
         if let Some(ref token) = token {
+            // match token {
```
Comment (kdy1) [inline crates/swc_ecma_parser/src/lexer/state.rs:319]: Is this change intentional?

Comment (RiESAEX) [reply crates/swc_ecma_parser/src/lexer/state.rs]: removed

**Review by kdy1 — APPROVED** [review]
Thank you!

---
swc-bump:
 - swc_ecma_parser
