### PR TITLE
fix(es/decorators): Handle default exported class

### LINKED ISSUE #8681: Decorators not working correctly for default exported classes
### Describe the bug

When a decorator is applied to a class that is exported as a default export, the default export contains the original class and not the new value returned from the class decorator.
This works as expected for normal exports.

### Input code

```typescript
@decorator
export default class Example {}
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "decorators": true
    },
    "target": "es2022",
    "transform": {
      "decoratorVersion": "2022-03"
    }
  }
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.4.3-nightly-20240301.1&code=H4sIAAAAAAAAA3NISU3OL0osyS%2FiSq0oyC8qUUhJTUsszSlRSM5JLC5WcK1IzC3ISVWorgUAU7BXiCoAAAA%3D&config=H4sIAAAAAAAAA02NsQrDMAxE93yF0ZxCcLd8SHfhqiGF2uakQkPIv1duSOgg0N3pndYuBHpqojGsvrqoDBWc2h1dsvHHHbKliibM1ag%2F0rukArYC9QvDW37BtudkjEmssaJxiJEOH5z1UfD6f3RW3QQ6l9ywBl2GK%2B2tXZvtC1n9TOu1AAAA

### SWC Info output

_No response_

### Expected behavior

The class should first be decorated and then exported, like this:
```tsx
let _Example;
class Example {
    static{
        ({ c: [_Example, _initClass] } = _apply_decs_2203_r(this, [], [
            decorator
        ]));
    }
    static{
        _initClass();
    }
}
export default _Example;
```

### Actual behavior

SWC compiles to 
```js
var _initClass, _Example;
export default class Example {
    static{
        ({ c: [_Example, _initClass] } = _apply_decs_2203_r(this, [], [
            decorator
        ]));
    }
    static{
        _initClass();
    }
}
```

Outside the module, only the original class is accessible, not the decorated version.

### Version

1.4.3

### Additional context

Might be related to https://github.com/swc-project/swc/issues/8515

### PR DESCRIPTION
**Pull request by magic-akari**
**Related issue:**

- Closes: #8681

### CODE REVIEW

File: crates/swc_ecma_transforms_proposal/src/decorator_2022_03.rs [hunk 1]
```diff
@@ -421,289 +421,273 @@ impl Decorator202203 {
         new_class_name
     }
 
-    fn handle_class_decl(&mut self, c: &mut ClassDecl) -> Option<Stmt> {
+    // This function will call `visit` internally.
+    fn handle_class_decl(&mut self, c: &mut ClassDecl) -> Stmt {
```
Comment (magic-akari) [inline crates/swc_ecma_transforms_proposal/src/decorator_2022_03.rs:425]: The git diff is misleading. 
There are minimal logical changes within this function.

1. Change `Option<Stmt>` to `Stmt`
2. All `class.decorators.is_empty` checks have been moved to the caller side.

**Review by kdy1 — APPROVED** [review]
swc-bump:
 - swc_ecma_transforms_proposal
