### PR TITLE
fix(es/decorators): Fix a regression about class expressions

### LINKED ISSUE #8095: Anonymous class TS method decorator broken
### Describe the bug

SWC fails to apply legacy TS method decorators for anonymous classes.

### Input code

```typescript
const foo = class { @foo foo(v){return v} }
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false,
      "decorators": true
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.74&code=H4sIAAAAAAAAA0vOzysuUUjLz1ewVUjOSSwuVqhWcABxgVijTLO6KLWktChPoaxWoRYAm3SIQysAAAA%3D&config=H4sIAAAAAAAAA2WPQQ7DIAwE73lF5HOv7aF%2F6CMQcSIqwMh2pEZR%2Fl4CCW3VG97Bu96163t4ioV7v%2BZnHpJhQW5zVmSJal5ZAV0SimWXFC4nVdnRaLxg0wa0xEaJJSPlGQvYKgc1PKHufijXwwg8keCvEQQX3bh8n2IpJEaRv8Rg4uTbfo3rjkgINMwFHhX3GjX%2BBp9PZ1gzBiePc7OU2N6FM0VqLgEAAA%3D%3D

### SWC Info output

_No response_

### Expected behavior

This should not error with `_class is not defined`

### Actual behavior

Errors with `_class is not defined`

### Version

1.3.74

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kdy1**
**Related issue:**

 - Closes #8095

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_transforms_proposal

File: crates/swc/tests/fixture/issues-5xxx/5626/output/index.ts [hunk 1]
```diff
@@ -5,13 +5,14 @@ import { _ as _ts_metadata } from "@swc/helpers/_/_ts_metadata";
...
     "use strict";
     _class_call_check(this, Example);
     _define_property(this, "prop", void 0);
 };
-export { Example as default };
 _ts_decorate([
     Prop(),
     _ts_metadata("design:type", typeof BigInt === "undefined" ? Object : BigInt)
 ], Example.prototype, "prop", void 0);
+export { Example as default };
```
Comment (kdy1) [inline crates/swc/tests/fixture/issues-5xxx/5626/output/index.ts:18]: This is a bugfix

File: crates/swc/tests/fixture/issues-4xxx/4063/1/output/index.ts [hunk 2]
```diff
@@ -17,13 +17,14 @@ define([
     function state() {}
     class Controller {
     }
-    class _class extends Controller {
+    var _class;
+    _class = class _$class extends Controller {
```
Comment (kdy1) [inline crates/swc/tests/fixture/issues-4xxx/4063/1/output/index.ts:21]: Minifier will be able to merge these, so I think this change is fine.
