### PR TITLE
fix(es/parser): Fix detection of `use strict` directive

### LINKED ISSUE #8616: JavaScript parsing error: Illegal 'use strict' directive in function with non-simple parameter list. with `node-sqlite3-wasm`
### Describe the bug

paste the code from https://unpkg.com/browse/node-sqlite3-wasm@0.8.9/dist/node-sqlite3-wasm.js

into [swc playground](https://swc.rs/playground)

got this error:

image

### Input code

_No response_

### Config

_No response_

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100&code=H4sIAAAAAAAAA7U9a1fbSLLf8yuMzqxHCsKxzSPEjsghxMywQyBrzGRmWR%2FH2DJoYkseSYYwRv%2F9VlU%2F1N2SILt39%2BQES1XV1dXV1dXVT92N49rHaLqa%2BzWvZttOzTuorV%2FUancAHyWTOFimH4IYcOnD0o9mtWk0WS38MK1teF7tx1U49WdB6E9%2FrNXrEteYrOIYfi8oee1dBaKRxJNapyZ5dCHbYFazeU6j0SyY%2B%2BF44Zt5Oapkj4%2BeQoo8Yj9dxWHNfjFbhZM0iEJ7QQU8jG%2BgHOvMgQK%2BuJPl9iS2i8DYH08fPsXRIkj8vp9E8zvf1WF%2F%2BJO0y9JeWYSyhl7o39c4hW3HMh3SOt7BuoSrx6m6Re4eS5g5XWuV%2BLUkjYNJanUnUZiktZOzwXZ79PHkzNtqt3Ze7%2Bxv7%2B3s67jD3zyJes1RZ5enp16Tv1z84%2FRk0Bud%2F2JC%2BuefvVbTAH44P%2BsBtKVDIa%2FeT72%2BZ4CPT88PB15bBw56vw28bR32%2FvT8vbejw0jIXR12OTjeNzMZ9A%2FPLk56ZwNvy8B86A16fVDOycXg5MhrN0E1cz%2Btpf5iyQmTP%2BdB6m9764xXYiMK%2B6swDRb%2BSRikwXge%2FOVPPRurDZN5STqefD2cz6OJveNwJndeuJrP%2BUvoWeFqce3HoooSz8I6C28EIGx5V%2BFQvLThxW00GmFLgrYFqC1BOwK0LUG7ArQjQElwE47B3P3EW0dLPxzdtTtAc5W4IfxLhkPX%2F%2BZPEBTuwnMcL5KbDmJbQ3cZ%2B8tx7PMkiJ%2FMo0S%2BAwU0N9KGeIds%2FFS8TOb%2BOB5dB%2BEUCpoIKL6PgpBRbefvezsaZBqtrue%2BBkr9b6kQhADX8%2Bi6AOB8BAhrgQBtDoASgRtI%2FRgynfrfSBlMEUnqL6Xs0Xy1CBW52hKmSJYDmWyJCpLSKVTguAwQ%2BiQj4SRahakhyPVD6ici6XycpCBa4sfpKI7ug6kkvh2HN75U9QQcR%2BqPhJcTVQ%2BlpcqX%2F6Dsd%2BP5ys%2Fla0mIKJeEyGJJSK4kCVJ0lCeURWCGspqnku6OysWBrMruVDomBoB2JIjJUQChJBqQTE3jz%2BXVYGD4UUyw7by2xiCbVkE3fjoar9JoEi0WgaiirDuLYpta2xUSu9DkhtA9nV%2Bji25AbxYHfmLnDdFx1tzFEP3Qm9zH46X9hQNHP6wRnH1BRlfNIf20hk6WdSdQ8wk6MqTrocg1UIwfTpMava1Jing1SUGihZ8k4xsfMlst%2Ffy1m94GSQNz8CyVk5VlwlBq4zgePwyin30Qi54dxrm2TGNvtBiTqyNEA2v11A9v0lun%2B3Pv8NPlfgNcAEO6QO50eW8Lz3kGzPnxHOBF8E%2FAl3hzYvcezQVdO%2BE3hRdXJUBqpyt4CVrM1WWosqzT6Ixc8Xl8FqX2dXBzEqbOOpjxxwOPoRvQRYwuDo9lN1avM4K3kuDwN43AWfPsGF6wzjiUveZygB9K%2FGP%2BBrEFxT8JKO5m4sKfO6ESeE68qyEZGXZUAfTIwVsk6wabm2rFgHX%2Bii0Nedxt7rwMXCvYbluiR8LG7XEba%2BTt3aZKQs6QrJvcB%2BnkliIsYD2G2ELvzDtA5Okq1FlS4yKeTvca%2FM%2FXrsqF%2Bn7ioadifoCJUkyFwUFJInQKVUkwduhw1RjJ0EuwZFDpyw0PQwpnjeyF%2Fc6DCcjiLjeNhGiRrGiZP098SoNh3SUUev8QLT4rSoLsSXiKBwifYZ02lqvkFqtKWghClSbip8I6%2BuSj7Mk37q2gSefVBJ5GQDFb6zqKoN8NrY4QPvd6OYd3rU5TVZsITzqgEm7eQXIxnkHAk%2Fo3YMw8C2oo7PnAk3Fmvc5Abz0ZXkoXV5o911%2BRBEwHiN5TU5F5ZqXU3GQUnkpxoLEBtzIdsBx4ElUDPB7jRoNx3SdoU5qjEqkMrmSHwJSncbdarhmFOt3RLPZ9m5NoGUfUT5DqGUPPI1spqBCBkA9TXk2S1yASSMfhBC0ht0ThGERBVJcuyiFZKF78qTqklqMUtJC4WO7SqmP9tMpJq3G1TynhqGuSZZDeQhxUw7aodmn2l8sQOr9lFKf%2BlPxfDbxoTTYxll2nZv2w1lpSZn0R1gQjyjHS%2FA8yyFhv%2FmEMcQbYgdZ3i9Gqu8anj6sk7X0LkrSjvXmzMZSdxp7n4fyhIx4YPIPxi7NGvz6bj28SVtmMwFkTyBODvE%2B9s1G%2FdwijuNPfmT7L8Z%2F78IqMNjQ5HKJ%2B1MiPgH7Qy5gNxhPpgvkQJC8g1qNLDFxyxCw8GWn9GdHwvgyLMYHhvhygkkuSiQBDbER%2BYsCSU2AO5XV5FK3m01oYpTWUspbe%2BrUprxysQSEyVR5jJyo6oW7g43iZ3WAPnZxDelvGA6pw2IYZUTiIx2EyZvMPzpoRgUFAUM%2BSi%2BhFFEUPPpUCgb9oZlTQcj4yPCXDrIEVGtKz%2Fi2xHSf2F9GdjEpspBA1klPTuM4WcBhyTOc%2BU%2BETWlcrlpQg517IDPDNXU9xXLYIQjCqYNLR3lSjLiujaHIYSi%2F9KRYBHUx5OPVs7EXxEGur3TR%2BWHPHjLk0gP%2F8wcYyIG3iZJMx9sUwgjB9rtZ5AL6RRhcEAk2bnQgNQPRepNBpMIPInooMMtkY8vq6HSekZActUqtfkxJMjFMWKn3qg0p8hs1ya6KuZTqVHBX1u9ZdEARWkVXCc3E5A6ZtfwDdaN9fesqsDrZ2zQocQSW9jTad85RJFsbCuXG6UpoGG3u4IhvySUJO9iL%2FOLKFIqMMp1Ewt1LzfMIuMAnZWLXsxDqXVliIKU5GszHzh7XRQ2Z8HqdSOl4M8ogpaAlbA%2BXnYoosXoWYlA3jEzlUSxepR8xU9ry1MMcFFA1MzBNK%2BQghpo5sEBCgSg7u2v%2B2BDV02I%2Fa8jWP%2BufKjx%2FUdKw%2FZKkc9LL%2FDabQJec8i%2BgEanIuCZ7XDVg0S%2BJoakJhSwXNeISjEqO6qoirlazVOcqxQRKy3sqp6BQtEZ7UxnOahq6Rb59aoAvVVJl4R9HU50ME8ap11RWZSDun2Ue10xBBkjRLLUqaXpOBPuV1pd6n1%2BVtK5%2FjtJFEbV8Qx1Pk8XTrej5eySl4cFKlaxhN34LotTSqcbGk95xee9NrChxESGLGFxwdJMe8zqclEQgfWmRKq9QcQh%2BrWHbtOF8qyDgI50ilx1iL%2BUbpZNm7LSRitUjzlSc0Xdmn2cry%2BYPCrKbBBowB6GIwhHLjf7pJQ86JSCdac2U7KmFFg6rGLI4WTKwnRckc5n6eZc7jYxZdPC1tI8RhpnTWfKg0jUL%2FHU2YcgAlyvJ2L6NjxTAqDVA2M9naBaOppXZSVY1JZqs2YdFujPgvG9FiQW6kefCoLhvoca50JfW6Ej%2F5aQVV9rJSnd9r9qyG2IxwwqsIqvaIAGcQN0DY3L2%2FhbGBrbYQ5yHwYTAh6UECmzPJOxM1o9whC704VaNaKx%2BoECl0CqLalnEA40%2FwH1x9lJjlYFFsyMw4SOhX5C2UgYk0hJxpYO8bVHP1Oh%2FLMiDoW0xhqHzY7HeBkZYU%2BgZLLtpqqZkf5TXWws6LqVU2mFSOKAmhjO741BiQ6BOY%2FfPPHeEWoEvX5uhw%2FVIgqXUq4%2F4ye0fmIFN5vQoZo3tcQdSnbTkpDzPZBC5i73I7G6jTtMq6kRIABrKUnL58qvauYqJWXdvSuFbP2N6ZEvHZN02mionbQlqaL3smZen8rbKwpqdXJ3Lvqqdx1bU0veAsxrr7ztncO3UuV3UQHq%2Ffq2CIMgmDoPVlXEwqaEKuMOnlYcTsL7QR6531g9WhV2TLF5ZgWHd%2BH9pgZy6hcHgX3V%2FR8%2FCK5TD07nj4KDHeWuA6d1mWY%2FMEYj4aoFnB13HrRplpWUL3j0b5aCVTbZylrYGaATFkc%2BIGk4J68gELpsmKbmutZ8OgapsrdzRQa26w2eKOWXdg63yNjxaQWfhfsswnXSpTTCBVUrb4rBSLMGTJAc7nVHXRXy7Dr2F0H0oHLznSLCO94QRVt7SIoLwsKwCXURLgmJgZKui2qy8vEBVfXfiOWXJG3lV9tFy%2BVwvMc%2F1Pp82fW7FgYlC%2FSo%2FaegVBtKnugrhBWCotYyvHZIU0mkuVqfj8Npcpq0hecKpmriUrHN8vA68XlYdYKvq3Cl9YO1IWMIhArl8U2NIKRpGvEWf8%2BwsavGiCQdVyRkEeoycpmKTJrWp9o5RxeS0YKx5mDv%2BTBQ%2FuK9R1CDZM%2BH%2BuczzJl80CGMP%2FymBKD8T%2Fi4OWPKyGfL93riNI8mmOjO8BE0hPPIjNYSoPT30p25u3HKe3Xuz%2FuQpi37bCaOp3ECQX6SfxwzKNDAoGlDRcoUeHZwNca%2FFaxh65k%2FNev08LNl57b68Md%2FHzeX%2FAKHbb7TKK44vfz468VnO7lDctBHmvX%2B%2BXIT%2F0TnuAbe%2B%2Bbpahj07PL3reTqtZKtmgf3l2dAjJW7s7pQTHF4PDgdfab5aKfXp%2B9Iu3vb9bmvPlGaHbzV1Dbm0BzNxJqK9%2BmfsWlcUuc6sioXq%2FHZ1eXpz8CgUyinN4dNS7uFA4tyrxZqZYjNEZ7rk0yvn%2B8uJ3bzdfDBnNprTSdhLOIjnOltNUArO5wyer8s0HoyA5jSZf%2Fe9Kvs%2BTb3hNhQMMTA0W7pzenXVSwoLhsG8pCoMtpCgILhAMxIJKUapWmzNSOSUsQChu%2B3lbsevn8ZFvC6ra9MN8SVOEpMbeH9wvzHYPn9%2F5cRxMIWjmASM4vOAmtNeZy%2FyIQ5uLx2IxaoTBNULQeX2KoxsI7Dyr8YrPKtO7RQTgKdKRZ%2BMkwCpx02iAEtHeVBKNAzKi7Z39etI%2FP%2FsI%2Fcro5GL0%2Bbz%2FS6%2FPJqTK8GfnH3oejZYRKbdU%2Bzj7%2BgDjktzSoPrACx%2FjNAjWFmlW7IDOcdZQ1l4ZkpK6RjZye4wB30TiTGzIHtEy%2BGHyEE7o6T10AfEDev%2BSIsEgEZLNktzNzhKL6R%2F97SfNR3P3XOTElAfWbKhFsGhMg5jGLmaBNq1XFt8XYSQdjXgaIqFyeflS%2BTWVCWtWgDzsH%2Bf%2BZf9EUjnvaAzbP80hHSlRGMULNkEnkcJwZ0kD80N2F6BEM9d3cp6mY63S2T60z26uZ08KdLBmNYI71EF6ZZ0%2F5hHaBiAb16vZzI9ZRKaPuVk4ICc5U5YNVayiiiicR%2BMp%2FNCyKZeRLPW%2FrR5FL8%2FqxMVFXhcn6FEKnACIY4fLSM9dinOZ8DZnguRcHx1KmoFqUU%2BihSgOwBrW69D2J36SNHCdmo9pD1ps7ky4CZXkqjWEAizn44lvv%2FrXv17duGBaTqb4GY0hmzRpO91KryLI%2FW9Bigs8HiPp6t6G2Tc1z2iVeqIsyxgHLcPHR%2By2YPDRmEc3FDHbHMBaIehKTwLxlJqKNGqk090qS%2B0avtfpms6YJnIUXyX1Aq5K0VEJWk2lVZGjVkUphZoU9QxpmLp1IKnifpwscmcmCHIopM1fvDJ8N592%2FexfH0KcvbieP2wos7bjawjsMdasheM0uPMp0xoP%2BGu4AD9JKRYWAn30F%2BCuSL7D9xBKqj3IbycDDNEuL%2BgV5%2BL2XTYjRz%2BtPfbGf7fb7JX%2FHvPfvR0G5r%2FHezt5V7NaQjPxmQi%2FBv49TkphVtdeLhpvUPIQDolhDWlqcJ88zol0ONeORtba43StPUHY2iulvBQcL%2FdNJ2ZSSqaXnCvSVrCFmIXRbreFANvtcraS9JLTItsK4mNJfMyJj8ENVVLv7QjqvZ2cem%2BnlFoSc1o2uK0gvpTUlzn5ZaDSk6GNRoeDT%2F0eDAhGMhhC2MnZyUCHfDq%2FGGhkcfG0DrPQfPd17PdXfB089zQIwxglbzEmzvMswcNyCsgrEzLkS0MmnDtuaHrT6Xn4iQlTIEpugxkuBGXZZDyf8yNIR%2FB4PZ58TWxVQUqQG0CpOS0urhVVwZc%2FKjgy9Sr8llGSFnXFgBXKEshybUnsVQFU0JdAGArjIhXJvkdlwlqUMqrVMLl21qpqG6uQcQWEkQK1KumZ4p6gFlLLDIQgWhpuvx%2F8pQ%2FhRTgJoJdqdk3ow2fcdOaztVTCTpUEx6s5xCpzqGtCq2L0VSZ2MCULUTPb3JStdRFB%2BaK4rxNYw3cN20ikFJVtMXs2m62t%2FyQb2v5pKMdrsi0nJdrZEDORtKaMM8Px3XheSgqBcJV6M9qFVqJd1u9MuHV5pTTdJ%2BpFpMTdOYqtUG98fzuG8alQURQeIpR0Qpgu%2FvUsgsIQ29rE903LsboQ2XAS1jVTa897Za9FSTdhLFl7vwrm09p9kN7WtpLDi4tef3ByfnZBc3vQi%2BJE7CxqsFGmT55aCSAavHGxuTOWY%2FGgqu2L%2FbY%2BWTZGuBCPQ1ObBd88C187uKEygFEgFP5VBJFGupWkwGnRxVk2iACYAEHygaVVBhviqQExaJwmn6EktpaDw5PyYcAzSS0Edl694mPBPIjC5F391aOpuS0%2B67uFyAb%2BsSh2l8LaeirHWRtslIGzQZpbxI2fMrgcmZHF44Pn6anq9fxdjrWN4EShyPiucCNBDmK5ZVSFP%2BIgrDbzoWXgyhPtI%2Bax4mwMZNNO7SFaQXug7hXHOLUgxc0IZVFpbTEOV7gvxK3hKbbFZNJYPoAtzue1aQSMxymZITK8v%2FVRByFuuMGMfx58PK3Z16uUtkD8%2FcL5Ue38cOkAuro0H8a6AU0b5XMxVLt8zFiiWz5IKBg8KwYft3HL4isVBdoTjuAny5kIfKx9JVLx4ckwF5%2FtUv0MeuJBLabz1tbY6qDyThYYkSdZV%2FG2Ex8idpmdwZqZW%2B8bJfMEEsZuBOjmAbOn0F1ZKxg1lITZRD%2BgVWmNPBoDfd4harg7CBG6ZX0CWcOWUl%2BWnItQGGSFLqssnRKYKAhUIwYoypbUSiobFe0a2pRbu501etUvfMLfSCw7AN4KmENlB0prP6z97EuFY8z47BVt%2FjINV2%2FWmv0UKp2xuGoOWfRQFvl4E%2Fl0sGYxloSIWYQmrvEKGA%2BkuF7x8KnqjthcK22WxO0qVrBvyUCwgedRmT99aTkOI3hpFY8WWkHLErtuaGB2BQwPDppDtqwIPJ%2FCwpBKRbf2GL4l8DDcUfHbbYZvCzyMQlT83g7Db3P8DIc7GsWxyYIt1%2Bo0JpuXGvpSYSFW3Fh3%2FyUIITIJlMU1oWW0IQRmX7jBhFHvm4zw5Yhfg%2BJcCfX76mnCvM7Ysv%2F%2Ft%2Ba0SvGIp7oqjNX3HAnWoV55JURYkXoNlhBhberV6Glr7ioxr1qjTotMRf0aFVskfMloLiuYPVfTSVVNB8mpP17%2BDqGr94B%2FDvDv33Zwf0i9btNLq9mEILf5%2BMhQzSZtHqG%2B6eP52eDn0YfD3y9GpyDd6Ojy4%2BUpDFN%2B7XlXTXe75e413Tctt9WG%2F7ttt7Xfdtutbbe9s%2BO2X%2B%2B4281dd3t7d2jy6vd%2BAjb9IrvdN%2B6bJrCD%2F7vAcr8F7IDlDrB8vQ3sgOX2DmP3MB0%2FHIM3hCDJ97Cb4fPGEKUvvbzUGMv5uDUe4uY5ARxWNBgxpLcfxg%2FJ0WqxmtOclYdp31WXufNkEaRUXgnrKyHGR8TZznBTAFB%2B29lqCceMHNhCC64TnZwNdre9N83m69abN%2B3dndc7Tfhl6JMzjt4qxbPdHYPoZHf76NbHlTEYMSy8A%2FjzVqZ9fITXA5nTu7PxWYevPwFCORM1GmGUOUfPMPojsfHXTRe4mWBNPqSYG9EwXVP1YHhDhUX4y5a%2FzQ77g8ETHzJ5oZQLfxKBH7F1ks0djehjEK5Sv0C0rxH9HK3iAkmrrdGwKjBI9vS8WLXpNO2mRpNb2FYLasSg3TGyxL3C0mJUYyaLdR7N9KxYSKgjtpmgW9LQB6Dev6LQP5%2FNaA%2Fwyz3emGmUkldDUWwXmh0nXS0Wfsw4PJliD1KUZcoGPwGOljkXyr2SdJqknq3muuGpqev1qtJ53kdcdlkEoa0mcFVeTkGb29wAkjRjPkO7LQL3oklvEnpN2nJIzpT2AgJWbATc3Az4AB7T4NmFGNczDlOb7SidvPVa7de4KS7c3JQ7lADabu5wsNfO4Qfe7m77zV69DhS7r7d3tjnJDmbElkPofVvur4TXjFdufoMFDdE8usfiFjyaG63Sk%2Bk3dzH%2BRkUcRJ9jGHDy9aUN24BDDOdw7s3cboCBx%2FiwoXw4zSGbBgdwZs9rbFWusZXUwUrqgMhbJj1y6q68vd3d7b1N217VW832tvP2bavpPK5a9IZD0xWvAnhk0h54THiH9ayooStejs2ht5K1sRK1JFNutp5O23rTflwdHOwV4O39x1V9b1tljWLvqrzbT%2FNut3eQd6tdyhwyBf5P5qtktf1MVjtNymq%2FIqtWuyqvZ8TIFMTQk%2FsdGGBLmFnRnpkpAxlueitaccH0iZyvF1Wk0vI48%2B%2BNZv%2FUHTJicVq%2FQYZtVXMKF8nE6IvUi2RoPZqtOqR%2FgXOC3tSjLhG9mgvufR7c3KZu%2BhetHXN5%2BJV2FMbZwh87ui9WXG7uspWEpncvJ9oTRJrzZi%2BV3lvrLthLNW061eHcgY%2B%2FPeHAuyI2Fooi911gBV2d8PNCkUTIIxqV%2F4anZyADHf9bGo8n6T%2BBKeuJ2aQPDuJZ751GmKk4hN0gjP3qX7Z9dbj1z%2FHWX7XhpvMv54dXssaJ4h39vWoNO9ZPHwdWlqsYN8V7aq4MrGq2QMLAakUhibqNmtu0nWNNhmXUOZYsWlXRW1V7zlpWCNkpaVkTpKsT8NBNy525pRJGGlU5Iy2vjDcof8E2w%2FjhCGtqFEb3dMMeGnkDXrgFqnR4IQJguiUwSrr04xnu6MAZr5wDxpXgyj6OvxGRckMiYePons%2BIkR85qFxaRvhyfOODB0DKrWtlF%2B8m6yFeUf9G5%2BaU9JiFTSmd0kk2bnmtfPKpREexj5mO0CnTViU%2FSf3pRS5xNGdv%2FCwM78A1yoODA76wBO0XVUIJcvXY3DGqSRRKOVnMjjPS5jVoteHl0rMhXoEBb7CcoxP8tmmLt61vf5MI%2BSTjjckq%2FRDdh7gRkj29xS2V7PGl12aNObrz459Ag6GUmBf1pd3abLRfcXqnWySUwWYB5Wql3IRB9d7eNgQyfE%2BYf6%2BnV7Tg8jLb0hFqrNxCVhB2o1HwgSzfmYNbSrzc9GyeI68ASZKfa41Xvgwjmf6JHfqBDzD8mkIPwddk8SIDDtpQT9vRPigFafNtXZ38tlXB8ZDttGde07PR5s5jArqBFpri7m3R6%2FEgM9AiTCQQISi6MMDyBV%2BF6RVDDuv1DZs9ypDH2dxkEDpdRU9bwOOgBSGnwoE30Xpd0Ye2bZTDGlP6VTNvJKtrOllgY9FYFg6bVsUIw7K4vIB9y7EsxG16ahECip5oKcheNesQReGlfzB48ZgW6SDxEY%2BHgYK2dqcwJmYNCQLmIjeMzoAh8oOAEgZPELI%2BwRTptlsQU%2B9BRG3ybz%2FDf6cJ%2FDGXNRSMSrCL0TmEyC1iyMY9AvkacfuEQ5I2kpTyp5i%2B%2BZa1gCf1wQ%2FkoVe49VbNLeZJK1PQsONxcgsBbtPdhbbbhBc2qJDtBBLnrSQ356UWYXITBuC7gunbPCwtSdFR98KOcGXwj%2BRwgvvk7LtZ4uKyEu4w5BcdQVzb51e20b177LalWdKgzdzjME0ax6PzX7A2GMqr2DPulCXtQ9JHDfL5OWaVfKjvAuiYykILE9q2a1Ewx2UcnK6caJaFdFtiRzd1aOsSCrnnm1dVfoDbVCrNT0EqP77zp7i%2FHERQ9VmU98sPa7GB3MkauM38i1tQ9f9ebrqeCURYc8BlOOfSm5v6HaF0OoJCZWD7%2BB0hiZ6bcqzieTk%2BsGt8NKOcBjHmIq%2BSBBhUr1de0UK4VTgPwq8kHU%2BgXYTENr82JnQDiNU7O%2B%2BdDSynTHB2XIT2WAg56NKyKd7cTJlN0S7xSi6Zm9xaLbJ2rdiivbozXKNmS7nTp9RF51vyqwlMhX9P4ux5bdNuarafGI2UhU2YmWpLFCeQ6Ok41aq7gTGeS4sbT4szOBx8hzAw2sQqJMWhAcQ%2BvdMQVyBRTPEsDGIG7x6pnV9IrvsAzsYxbmLFVCo3LZt82zkAeHT6ViV4J8vRMY47FcolvMDcv%2FPn7B4F9fiKI53C4iu3sDKfoFkvF05YsAcW3Pvt5GJgvVMO2nQKJ48y7dAL2%2FL%2BfL30x%2BE0WoSir6DT6ai493yPPKsECGnkwXYRokiinHyTkkN3T0fGGjHxBjOcU7mBidQ8ERaFgd6MWytnzeXhQ8f%2FSBhsz%2FRI8R%2FWhnzz%2BP561e5dYA%2BuVcv4CfPHDgzdR87TY%2FmuC6oXc3iS9IBvHpOAtzwpCbmaNXC7ls1loZ7%2BOUGyMkx%2B3q4UTQizJvh%2BFBYySBvO%2Fdt39AnMTz1rgIMYADiXBLkl0kVhZinHaLUjD1ER7VP5i8N8z4uQ94Z5K6YnGa3I7rFeL2%2Fd8eJ7W%2Ff3903sxKDRrGm89R3tmiYrMcF1WUNCqXljQjgSw7gem8M9ptM0bjY1wVBtZLLByOrhOekNnuezwZrIO620FFJ28gJVVyxRZoUSjyAqJs2PmEfP7%2FYRh0ZgKJvinAx41PsghNDpXXuv2dlpvtkrMsMe3zYi5wVdMIb%2BJGIRa1PGtfXSY5dOxC8n1UK%2BcyIoT8oOc1alI2x5QnGAtCppn7DVaVlEX5n4c1%2B9W0%2BNiCoi8khRmVaXWy22vQCv9sCLGmEYjvMPbNyO1SA3lYysTcIN8%2B46nLBBFFkpHx7xCTN%2B6Ts%2F2wX8aPuHch08xxQXCc7DC%2FyExr85ia98dqPiJvjqCfwJ7nTybCqdy5B4kQ7e6Im%2FCV3t6UbLNBETGml05K3l%2FRe5pCgJWWEiL3it19mznEoRgCa%2Fg6BYdCqbeuzNtUhnVgd%2BlJyUMgNC7IrvFmsD0VgwrejKJi4wrjs6cI9IFovSlUny8j66h8iT3ykpP3ZLh%2FUKScS9EsKnvmfvtimOtDdhiaw%2B2NTY5JBffM%2BXMcE8SM105%2BpaX6Ok%2B9TVO5WIASshToVFR1eiYq%2BCIc3LSCwVmfHHCkq4IcLfi%2FEdbi0gQSCZJ5OQDADhsxSSgIMzsbGveGEskSoLFlH4AZcEhOYp2w0pBowy0wgvj8QXqbmKmkPj8RR%2BRZPHu1mfMnnV2sPVwo8DVgcbguLxUTw1oG8GG6MdYgcpr3Z%2BI8vjY2raQVdh2aezoSL3jdzCsFZymnpdEaFe3yDhlDPoqr3ImVBxC60kpGb%2BdCtn5%2FlY4flEO%2Fi%2B61Z7vxdS8G%2BHbgp0fsoX3cO3OJ23ZjB2Y1EobuVQYX%2FDtVP474YHB68F6ySAdo%2B7Ril%2FD16Fe4F3umIJnExgdWhewbX%2BwCcY%2FrnWDJ5mBJviE8F8eMLvf8Rh7M%2FgfcnTsayoFtbyfqCkcyW%2BdpJ02JdFQPd31rurYedK5n7FMEP%2BVRPWxFq4DSC40bYB0H7BnDkrs84GWpqsGtrXxtdfaCM3XUJMDgO%2FjKJomGsJzQTzZAdS8%2BXP4OYTZqrgOAZzwLlArsBW%2BzUphH7%2FwN89UmKrvUsqbLV3SIGtVivrqvWGs%2F6aAdgiT3E5MJfV3CehU3EtKYylgFeClGmIboSl8mJ16GmaJYbVcjVOkHAorIu7hr8n4j5mZmseXeSN35HhJlw8DtoQKbQjW%2BoBgjJiWzdnfHXotmQ2Y47ZXPhE%2BT6aPnhXrWHXrH5W%2Bzohq1CKUHFv4ZvXbqu167aab9wWhLn4DxjpdWRwEFXFB6D0Q9rjzpiFyoVsczq77UKu%2BK%2FJ%2FrYp39furqu8i92ITx0XME%2BGkkT%2F5umBNVrqGs2XArCMLx7nd20XtvZfAbGM2hTCTJ5soX38HwO6teZqqIPFQulnAeiFKZ7y5xd%2BK5GiwemKk7ClD7IEOqnCoAcmuYhfysEiPwj5qrLxdCHoGmVxq7jaK3C%2FTqutjA92hWyE5NItdbxlyFvKT0JBpwYbLAW0dvawSUnzkAOCsIVX0BvfHYVI4FXMgCJkxNL1bLwpl9CJWpEX10%2Bn4M8TpgO2H6xc%2FCKQW9z4K7LV1QK%2BNtcnrx%2Bzg1WFFyp3Hh%2BbXPTYZ9xO8I47XwZxQNlbLNMHwl3Mo5R9Qg%2B1bqSQpz1FviZ%2BGS1tJxML67zucV29ZY70N%2FBJvVGsj1cU06E1ecMqULATTtZliKzwzBJyY2eb6NrERu0CBp2Hp6fnn0eDw%2FenvdFP%2FfPPg58bltCNqTQYZbEeq9CMaGmRVIZnMWQysgKBKVh8gNuudEMHEB9LKTfw676e4tA09IpWw7%2FtgLF7GuYHv9JQxq6F6rLZ5H%2BhQBhucq%2F%2FjO7R4RdVr%2Fgyr6IHywvVLc%2Bep88PzZntixiUxsX6NxE8upgRLxEpYcQ%2FglDSwjGRUyYcYVw6hdotmjH2NCxt7pj5IS9vPe%2FoG7fdr51835m76JTtmXHHnZLtMO4fnYrNI27S0ZYr3ahTtdLmzjrqYpabdrQ1JTfuGKsebtApWXpw%2F%2BwoE%2FfubacwDe76HWU22r3uKDOi7qRjzFq6y442iehOO%2BoEnHvTqZidcsOOOtWUV4A4LqcexuO7%2FkaIH%2BGgYoQ39iT6Obg7fmfHSHzJT1xEl0%2BomBhrqLO4N1nQDc%2FF9AQ2E38zE%2BtXaRe56HiT3YPJLv9%2BWpFVjjPZ%2FFXOBq8DrWKDOJPNYYU0FCVWiYNIk9H7ckbstE8VJ34WyGB1VM6K7rKo4kRIk9GHCh3h%2BKhKR4Az2fRKrEd8cKvUhgTSZHT8BKOyomlok9lPFcyqNK6hTWY%2FVzCj85aVvAhrsjqpYAU1VMmIri%2FS2fy9ms0Tqio1g18qWGH3UckJkSaj0wpG5Y1OQZqMPpqM8Lr1IgeEmknPCt5IuRS6xBcpWJPVeQWrcrtWkCajT1WMyr2IijVZ%2FaOCVZVVa2iTWb%2BCWYUNqViT1UUFq%2FKqV5Amo0EVo1KnpCBNRpcVjOgihipGiDQZ%2FVolkbxGvVouSWIy%2FWwylRf4FplJlMnkt0omZdWnIE1Gv5cyqrIpBWky%2Bmcpo1LXJjAmi1EVi8oylRrkD6Vsyl2aRJlMxuNSLuVGLVEml%2BtyLsat7BUMDSqT96TAGz%2FbVeSFUDPttJA2%2FyxRkUOOM%2Fn4RRnok0olUhDcTD8rpC98lKfIqkBicr0pcOXfCSpprQxhcrgtcuBfGCyLaRnG5BEUeRQ%2BCVfCrUBj8v2jwJd%2F47LIjCNMDl8LHPRPPRYZ6XiT31zyY6ec8vTs3aRfSHocoObU%2BGbShoJWrpDp%2BKWG5wtYOsmfGgmtZeoEMRIIKWjVyuLfSJdQZcIDcMqbpNBH9UCkA9h0%2BRjvYuqvwopLmvJbVlYh3qThx%2FzDaTKhgx%2FSYtea5rByZpKHenuLuFbNuNPqoClmZDJxUV3JzVcKleQ4jeRVbYqQRNSVAHYnlNSwAIOSCIGfCcKro0Q67UI54yoTth9Q3GCs3MMShf3CzXPW0HkaDezlbXOZwgzGuhd0yyhe51ICtC1IEuKu8EbDolkYPOYVrVI5n2vTrdMl0FJulpPhghNXJj6zZRgBUGWDCsIyVF4byJBV9wZy7FUBVHJzIEMot7UUcTQvigIyu3zx4kWtJk6yEfFhfPMiewGYzEHC7otgVhNC86WDmud5tR%2FZ5aA%2F1ur1GkczBhrWAfYM3JCJedm7L%2FhmO8me7YVg6YUuiD9DXP04Xkx%2FHCJLBrCvhm7NdmreQU3Y1%2F8B0p4Sn4yIAAA%3D&config=H4sIAAAAAAAAA1WPSw6DMAxE95wCed1tN71DDxFRg4Lyk8dIRYi7N6EJLbt4ZvI83rq%2BpxkDPfotP%2FOQjIDlnLOCNah5Z4V0TYxBbFK6NVdRrNE48CHtX4dUTMAYxRfUKRqZWAuKca8McjGCG6Nq3gY7rv8thuiTMHANlqgJk%2BNrh672IB9fy2HW68oFZX2m%2BRhm0C%2FZNp50sni27yoLd%2FsHaBrtuS4BAAA%3D

### SWC Info output

_No response_

### Expected behavior

Work expected as [babel repl](https://babeljs.io/repl)

### Actual behavior

_No response_

### Version

1.3.100

### Additional context

I see that https://github.com/swc-project/swc/pull/3278/files#diff-569a1e82f9f711c8951ae1d7da5ef327d1075f6f35e940c9f06faf8fef04c981 throw this error

_No response_

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

Directives should be at the start of the file, and this PR changes the parser to match only at the start of a file.

**Related issue:**

 - Closes #8616.

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_ast
 - swc_ecma_parser

File: crates/swc_ecma_parser/src/parser/class_and_fn.rs [hunk 1]
```diff
@@ -1615,10 +1615,22 @@ pub(super) trait FnBodyParser<Body> {
...
 }
 fn has_use_strict(block: &BlockStmt) -> Option<Span> {
-    match block.stmts.iter().find(|stmt| stmt.is_use_strict()) {
-        Some(Stmt::Expr(ExprStmt { span, expr: _ })) => Some(*span),
-        _ => None,
+    for stmt in &block.stmts {
+        match stmt {
+            Stmt::Expr(s) => match &*s.expr {
+                Expr::Lit(Lit::Str(..)) => {
+                    if stmt.is_use_strict() {
```
Comment (magic-akari) [inline crates/swc_ecma_parser/src/parser/class_and_fn.rs:1622]: What are the differences?

Comment (kdy1) [reply crates/swc_ecma_parser/src/parser/class_and_fn.rs:1622]: Directives should be at the start of the file, and this PR changes the parser to match only at the start of a file.

Comment (kdy1) [reply crates/swc_ecma_parser/src/parser/class_and_fn.rs:1622]: We skip non-use-strict directives, because those can be also a directive

Comment (magic-akari) [reply crates/swc_ecma_parser/src/parser/class_and_fn.rs:1622]: Check this
https://github.com/swc-project/swc/blob/f7baf240ba15286c9e381f3b037d677ee7b1f63c/crates/swc_ecma_transforms_module/src/util.rs#L199-L210

File: crates/swc/tests/fixture/issues-8xxx/8616/input/1.js [hunk 2]
```diff
@@ -0,0 +1,18 @@
+
+var Module = (() => {
+    var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
+    if (typeof __filename !== 'undefined') _scriptDir ||= __filename;
+    return (
+        function (moduleArg = {}) {
+            var Module = moduleArg;
+            var readyPromiseResolve, readyPromiseReject; Module["ready"] = new Promise((resolve, reject) => { readyPromiseResolve = resolve; readyPromiseReject = reject }); "use strict";
```
[the remark this answers is not in the document]
Comment (kdy1) [reply crates/swc/tests/fixture/issues-8xxx/8616/input/1.js:8]: It does not matter, because it's not at the start anyway

**Review by magic-akari — APPROVED** [review]
