### PR TITLE
fix(ecma/lexer/jsx): jsx back slash escape parse

### LINKED ISSUE #2162: Issue parsing JSX attribute with single back slash
**Input code**

```ts
function test() {
  return (
      <>
          <A b="\" />
      </>
  );
}
```

**Expected behavior**

Should parse because back slashes are valid like that in JSX.

Ex. https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4BYAKABMk0AbFIuNCAOwGd4BBALjhRsAnhUpVMAVzYZg7ODCRcAFAEo4Abypw4RGBKhs4SrdtMAeAHwnTNuGe5wARgF58AHXxwA9Fcq27PiYqogC+VEA (even though syntax highlighting breaks)

**Version**

swc_ecmascript 0.57.0

### PR DESCRIPTION
**Pull request by RiESAEX**
attempt to fix #2162 
maybe relate to #299
I think babel only escape `\` to `\\` [babel playground](https://babeljs.io/repl#?browsers=IE%208&build=&builtIns=false&corejs=false&spec=true&loose=true&code_lz=MYewdgzgLgBAhjAvDAPAPgFAoIIwEaIDkAOoTAPRoDcWuBJArgKwAsApgGxmU075HEAHgCYAjN2q1-JUhUl96xDDAm9KQA&debug=false&forceAllTransforms=true&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env%2Creact%2Ctypescript&prettier=true&targets=&version=7.16.3&externalPlugins=&assumptions=%7B%7D)

### CODE REVIEW

File: crates/swc_ecma_parser/src/lexer/jsx.rs [hunk 1]
```diff
@@ -157,9 +157,8 @@ impl<'a, I: Input> Lexer<'a, I> {
             if ch == '\\' {
                 has_escape = true;
                 out.push_str(self.input.slice(chunk_start, cur_pos));
-
-                let chars = self.read_jsx_escaped_char(&mut Raw(None))?;
-                out.extend(IntoIterator::into_iter(chars).flatten().flatten());
+                out.push_str("\\");
+                self.bump();
```
Comment (kdy1) [inline crates/swc_ecma_parser/src/lexer/jsx.rs:161]: I think this will break all other valid jsx usages.

**Review by kdy1 — COMMENTED** [review]
Let's see if tests work.

File: crates/swc_ecma_parser/src/lexer/jsx.rs (hunk 1 above)
Comment (kdy1) [reply crates/swc_ecma_parser/src/lexer/jsx.rs:161]: Hmm...
Tests succeed, but I'm still confused. It makes all tokens handled as `raw`... So I thought it would break things, but seems like it does not?

**Review by kdy1 — APPROVED** [review]
I was stupid, thanks!
