### PR TITLE
fix(es/codegen): Add quotes to property names when `ascii_only` is `true`

### LINKED ISSUE #7805: ascii_only handles object attribute names missing double quotes
### Describe the bug

input: https://unpkg.com/lower-case@2.0.2/dist.es2015/index.js

```js
{
	Ì: "\u0069\u0307\u0300",
}
```
asciiOnly = true

```js
{
	 \xcc: "i\u0307\u0300",
}
```

`\xcc` should be in double quotes

### Input code

_No response_

### Config

_No response_

### Playground link

https://play.swc.rs/?version=1.3.74&code=H4sIAAAAAAAAA8VUTU%2FCMBi%2B8yve6IURsg4wfoxwIAMTzQwE5ITG1FKWmbEtXadE5exF%2F4cn43%2BQoz%2FKdh0DlqFHe%2Bjb7Xnet0%2BfvimqVEpQgWEQM0JNmPLQREjMeuy7JJhQPWAO6se3nkvQyOogD3MacRSTCRqGlLjYs3Dk%2Bo7O51wUQqV7zGA46vd7g8tu58buWW27Cy14KoEYnJnpSg5GHToPTUBXsVFrGM8iGAcnaRBzwzhCTjWjz3C4mS3H8tOEPck%2FPNmrbiFnCqg1anng%2B6UoZ6GWacCPv%2Bj8J00e36UpM60tQ63eTb4sS4WO%2Bnn8h%2ByzTIFyPifxfAW3C%2BHlR3q2%2Bmkh%2FvWaK5%2FMRp71VsTKu7V8L2I1Co1bNEtIdbgdEOy5j3QCXvBAGRAcUT3pWOFjwDhMY59wN%2FAFLpjUlizR27QccVZNf2qpabLJPew7orHzvT5WTJ0H6wradTNJc6dQlmnaxjXymPlK0mozndHQw4QmVF1ddHUtrzwTKrJESRG3OZ5dN2GhaWqfoqoCWqy9WDkAOAKc1d7lx2aZ1IF0Cyl366TJLmgfouRBucBhKB6H0cBuuf6EzvW7SKr9AViblfp1BAAA&config=H4sIAAAAAAAAA2VQuw7CMAzc%2BxWVZ2YGvoAF8Q1WcFFQXrJTqVHVfycJSSliiey78%2FmcdRhHeImCy7jmMjcBWYj3PiOSXMQlIxBTIFGsQ4RTZ6MUakIjVKHtwwAtkdihuZIJxJI1kWdqpPFeqI81zGqnp3RcrLwNTCK%2FwiJF9zT0B0%2BeLcaDQ8ZQlNZ3Z1IL0Jht6G%2FNC9Y%2F5urYfqFcWi4mOcNX1BPua0HLrU9W9%2B0NfSXnk1EBAAA%3D

### Expected behavior

ascii_only When dealing with object attribute names, double quotes should be used

```diff
- \xcc: "i\u0307\u0300",
+ "\xcc": "i\u0307\u0300",
```

### Actual behavior

_No response_

### Version

1.3.74

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by kdy1**
**Description:**

**Related issue:**

 - Closes #7805.

### CODE REVIEW

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_ecma_codegen

File: crates/swc_ecma_codegen/src/tests.rs [hunk 1]
```diff
@@ -872,17 +872,17 @@ fn ascii_only_tpl_lit() {
 #[test]
 fn ascii_only_issue_7240() {
     test_all(
-        r"
+        r#"
         export default {
-            \u3131: '\u11B0',
+            "\u3131": '\u11B0',
```
Comment (jridgewell) [inline crates/swc_ecma_codegen/src/tests.rs:877]: Nit: This is actually fine, `\u` escapes are [legal](https://tc39.es/ecma262/#prod-IdentifierName). It's just `\x` escapes that aren't.
