### PR TITLE
fix(es/parser): Parse `yield<T> (v: T)=>v`

### LINKED ISSUE #9914: SWC should parse `yield<T> (v: T)=>v`
### Describe the bug

sub issue of #9878 

### Input code

```typescript
(function* () {
    yield <T>(v: T) => v;
});
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2022"
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.10.9&code=H4sIAAAAAAAAA9NIK81LLsnMz9NS0NBUqOZSAILKzNScFAWbEDuNMiuFEE0FWzuFMmuuWk1rAMYyBAQtAAAA&config=H4sIAAAAAAAAA02NOQ6EMAxF%2B5wick2BUlBwBw4RgUFBLJFtpIkQd58kkBk6%2F%2FcXn0prmLmHVp%2FxjMJbYqSfjoTDJvYTCUjwyD05L1AVVzhZo10YM7puB8TShJJayKY2BtTjwboPx4L%2Fj2n1zjWvkNvcGMpyRo670hQ6UF1fU15err0AAAA%3D

### SWC Info output

_No response_

### Expected behavior

SWC should parse successfully.

### Actual behavior

_No response_

### Version

all

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by magic-akari**
**Related issue:**

- Closes: #9914

### CODE REVIEW

File: crates/swc_ecma_parser/src/parser/expr.rs [hunk 1]
```diff
@@ -39,34 +39,32 @@ impl<I: Tokens> Parser<I> {
     pub(super) fn parse_assignment_expr(&mut self) -> PResult<Box<Expr>> {
         trace_cur!(self, parse_assignment_expr);
 
-        if self.input.syntax().typescript() && self.input.syntax().jsx() {
+        if self.input.syntax().typescript() && is!(self, JSXTagStart) {
```
Comment (kdy1) [inline crates/swc_ecma_parser/src/parser/expr.rs:42]: Does this mean we now produce `Token::JSXTagStart` even when `jsx()` is not enabled?

Comment (magic-akari) [reply crates/swc_ecma_parser/src/parser/expr.rs:42]: Actually, when we encounter `JSXTagStart`, it indicates that JSX is enabled. The current implementation has just one fewer condition compared to the previous code, but logically, it should be equivalent in functionality.

This code ended up in its current state due to my rebase and squash process. However, upon reviewing it, I realize this part doesn’t actually need to be changed. If needed, I’m happy to revert this change. Please let me know your thoughts!

Comment (kdy1) [reply crates/swc_ecma_parser/src/parser/expr.rs:42]: I think the previous check is needless, as the existence of a such token proves `self.input.syntax().jsx() == true`. Thank you for clarification!

**Review by kdy1 — APPROVED** [review]
