### PR TITLE
fix(es/ast): Add `definite` and `is_override` to `AutoAccessor`

### LINKED ISSUE #8344: AutoAccessor missing "definite" in AST
### Describe the bug

`AutoAccessor` nodes are missing a "definite" property for non-null assertions in TypeScript.

### Input code

```typescript
class Test {
    prop!: string;
    accessor includeSource!: string;
}
```

### Config

_No response_

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.3.100-nightly-20231125.1&code=H4sIAAAAAAAAA0vOSSwuVghJLS5RqOblUgCCgqL8AkUrheKSosy8dGuIWGJycmpxcX6RQmZeck5pSmpwfmlRciqyqloAhwjVK0kAAAA%3D&config=H4sIAAAAAAAAA2WPQQ7DIAwE73lF5HOv7aF%2F6CMQcSIqwMh2pEZR%2Fl4CCW3VG97Bu96163t4ioV7v%2BZnHpJhQW5zVmSJal5ZAV0SimWXFC4nVdnRaLxg0wa0xEaJJSPlGQvYKgc1PKHufijXwwg8keCvEQQX3bh8n2IpJEaRv8Rg4uTbfo3rjkgINMwFHhX3GjX%2BBp9PZ1gzBiePc7OU2N6FM0VqLgEAAA%3D%3D

### SWC Info output

_No response_

### Expected behavior

Should have `definite` property.

### Actual behavior

_No response_

### Version

1.3.100-nightly-20231125.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by dsherret**
**Description:**

Adds a `definite` and `is_override` property to `AutoAccessor` as they were missing.

Also fixes codegen for `AutoAccessor` when emitting TypeScript (which is the main reason I need this PR).

**BREAKING CHANGE:**

Adds a `definite` and `is_override` property.

**Related issue (if exists):**

Closes #8344

### CODE REVIEW

File: crates/swc_ecma_codegen/src/lib.rs [hunk 1]
```diff
@@ -1572,9 +1583,7 @@ where
             emit!(dec)
         }
 
-        if n.accessibility != Some(Accessibility::Public) {
-            self.emit_accessibility(n.accessibility)?;
-        }
+        self.emit_accessibility(n.accessibility)?;
```
Comment (dsherret) [inline crates/swc_ecma_codegen/src/lib.rs:1586]: This will internally handle whether to emit the accessibility or not.

File: crates/swc_ecma_parser/tests/tsc/autoAccessor1.ts [hunk 2]
```diff
@@ -6,4 +6,5 @@ class C1 {
     accessor b = 1;
     static accessor c: any;
     static accessor d = 2;
+    accessor e!: string;
```
Comment (kdy1) [inline crates/swc_ecma_parser/tests/tsc/autoAccessor1.ts:9]: Please revert this. `tests/tsc` of the parser is copied from the conformance test suite of TypeScript

Comment (dsherret) [reply crates/swc_ecma_parser/tests/tsc/autoAccessor1.ts]: Done.

**Comment by dsherret** [comment]
Some feedback I've given in the past: the CI that fails every time in the SWC project makes it difficult to spot actual CI failures. If the CI only failed when there was a mistake in the code I could be alerted to it faster instead of needing to go and manually check back.

**Review by kdy1 — APPROVED** [review]
Thanks! I'll merge this along with other AST-breaking changes.

---


swc-bump:
 - swc_ecma_ast --breaking

**Comment by kdy1** [comment]
I'll merge this into a new branch named `dev` and publish crates once all AST-breaking changes are ready.
