### PR TITLE
fix(es/codegen): Fix codegen of large numeric literals

### LINKED ISSUE #9223: Large numeric literals are emitted as `Infinity` / `-Infinity` instead of remaining as they are.
### Describe the bug

Roundtripping an AST containing the code below, the output contains `-Infinity` instead of `-1e999`. I think the output should remain as `-1e999`.

### Input code

```typescript
const x = -1e999;
```

### Config

```json
{
  "jsc": {
    "parser": {
      "syntax": "typescript",
      "tsx": false
    },
    "target": "es2022",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    },
    "transform": {
      "react": {
        "importSource": "npm:react",
        "runtime": "automatic"
      }
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link (or link to the minimal reproduction)

https://play.swc.rs/?version=1.6.7&code=H4sIAAAAAAAAA0vOzysuUahQsFXQNUy1tLS0BgAenTgBEQAAAA%3D%3D&config=H4sIAAAAAAAAA21QOw7CMAzde4rKMwPqwMAdmDiBFVwU1HxkOxJV1buTtA0tEksUv4%2Bf7alpW3iJgWs75W8uIrIQf%2BuMyOgV3xkBHSOJYRsVTpVVKVSPg9ACzSsDivwkLS6S7tx1mwOGEISqY8Oc9bYfj5kmuMgk8issUvTPgf4nMnrpA7tjIyY0egAyZF0MrPeQ2JRG4KO7rrLTLuLk1bqFx6TBoVoDGz039V2iwYVHWmbaTljOtC5%2BgV1Ud%2FzuA1Zu1amcqJk%2FtsEHsI4BAAA%3D

### SWC Info output

_No response_

### Expected behavior

```js
const x = -1e999;
```

### Actual behavior

```js
const x = -Infinity;
```

### Version

1.6.7

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by imranbarbhuiya**
**Description:**

This PR moves the infinite check below the raw number check

**Related issue:**

 - Closes https://github.com/swc-project/swc/issues/9223

### CODE REVIEW

File: crates/swc_ecma_transforms_optimization/src/simplify/expr/tests.rs [hunk 1]
```diff
@@ -843,6 +843,12 @@ fn test_fold_arithmetic_infinity() {
     fold("x = Infinity ** -2", "x = 0");
 }
 
+#[test]
```
Comment (kdy1) [inline crates/swc_ecma_transforms_optimization/src/simplify/expr/tests.rs:846]: I think this is not a good place to add a test. You can add a test in https://github.com/swc-project/swc/tree/2f22fee353e7e6be013d5ee9335bd558f20bd72b/crates/swc/tests/fixture/issues-9xxx and run `UPDATE=1 cargo test --test projects` from `./crates/swc` instead.

File: crates/swc_ecma_codegen/src/lib.rs [hunk 2]
```diff
@@ -703,7 +703,7 @@ where
         self.emit_leading_comments_of_span(num.span(), false)?;
 
         // Handle infinity
-        if num.value.is_infinite() {
+        if num.value.is_infinite() && num.raw.is_none() {
```
Comment (kdy1) [inline crates/swc_ecma_codegen/src/lib.rs:706]: About the question on Discord, I think some code is removing `Number.raw` .

Comment (kdy1) [reply crates/swc_ecma_codegen/src/lib.rs:706]: image

You can see a list of codes touching `Number.raw` by using vscode feature.

Comment (kdy1) [reply crates/swc_ecma_codegen/src/lib.rs:706]: As [the playground link](https://play.swc.rs/?version=1.6.7&code=H4sIAAAAAAAAA0vOzysuUahQsFXQNUy1tLS0BgAenTgBEQAAAA%3D%3D&config=H4sIAAAAAAAAA21QOw7CMAzde4rKMwPqwMAdmDiBFVwU1HxkOxJV1buTtA0tEksUv4%2Bf7alpW3iJgWs75W8uIrIQf%2BuMyOgV3xkBHSOJYRsVTpVVKVSPg9ACzSsDivwkLS6S7tx1mwOGEISqY8Oc9bYfj5kmuMgk8issUvTPgf4nMnrpA7tjIyY0egAyZF0MrPeQ2JRG4KO7rrLTLuLk1bqFx6TBoVoDGz039V2iwYVHWmbaTljOtC5%2BgV1Ud%2FzuA1Zu1amcqJk%2FtsEHsI4BAAA%3D) uses `ES2022` as the target and does not enable optimization, you need to check for 

 - swc_ecma_transforms_typescript
 - swc_ecma_transforms_proposal
 - swc_ecma_transforms_base (unlikely, but well)

File: crates/swc_ecma_codegen/src/lib.rs [hunk 3]
```diff
@@ -718,17 +718,25 @@ where
         srcmap!(self, num, true);
 
         if self.cfg.minify {
-            value = minify_number(num.value);
-            self.wr.write_str_lit(DUMMY_SP, &value)?;
+            if num.value.is_infinite() && num.raw.is_some() {
+                self.wr.write_str_lit(DUMMY_SP, &num.raw.clone().unwrap())?;
```
Comment (imranbarbhuiya) [inline crates/swc_ecma_codegen/src/lib.rs:722]: I'm not sure if I should be using `num.raw.as_ref().unwrap().as_str()` here or if there's any other way which can avoid the clone or if clone is fine here. Lemme know what should I use

Comment (kdy1) [inline crates/swc_ecma_codegen/src/lib.rs:722]:
```suggestion
                self.wr.write_str_lit(DUMMY_SP, num.raw.as_ref().unwrap())?;
```

(in case this works)

File: crates/swc_ecma_codegen/src/lib.rs [hunk 4]
```diff
@@ -718,17 +718,25 @@ where
...
         } else {
             match &num.raw {
                 Some(raw) => {
                     if raw.len() > 2 && self.cfg.target < EsVersion::Es2015 && {
                         let slice = &raw.as_bytes()[..2];
                         slice == b"0b" || slice == b"0o" || slice == b"0B" || slice == b"0O"
                     } {
-                        value = num.value.to_string();
-                        self.wr.write_str_lit(DUMMY_SP, &value)?;
+                        if num.value.is_infinite() && num.raw.is_some() {
```
Comment (kdy1) [inline crates/swc_ecma_codegen/src/lib.rs:734]: Isn't this logic duplicate of the logic above?

**Review by kdy1 — COMMENTED** [review]
swc-bump:
 - swc_core
 - swc_ecma_codegen

File: crates/swc_ecma_codegen/src/lib.rs (hunk 4 above)
Comment (imranbarbhuiya) [reply crates/swc_ecma_codegen/src/lib.rs:734]: the condition is the same but the statement isn't

**Review by kdy1 — APPROVED** [review]
Thanks!

---

swc-bump:
 - swc_core
 - swc_ecma_codegen
