### PR TITLE
fix(es/compat): hoist env in function params

### LINKED ISSUE #4208: Wrong "this" in async arrow function params
### Describe the bug

define an async arrow function property in the class . if the function param has a default value , the context "this" will reference error

### Input code

```typescript
export class CompanyBgStore {
  public corpName =123

  public getBusinessInfo = async(corpName=this.corpName) => {
    console.log(corpName)
  };
}
```

### Config

```json
{
  "jsc": {
    "externalHelpers": true,
    "parser": {
      "syntax": "typescript",
      "decorators": true,
      "tsx": true
    },
    "transform": {
      "legacyDecorator": true,
      "decoratorMetadata": false
    },
    "target": "es5",
    "loose": false,
    "minify": {
      "compress": false,
      "mangle": false
    }
  },
  "module": {
    "type": "es6"
  },
  "minify": false,
  "isModule": true
}
```

### Playground link

https://play.swc.rs/?version=1.2.161&code=H4sIAAAAAAAAA0WMsQrCMBRF93zFHe1SUEeJQ51cXPoFaXjGQPpeyEvBUvrvFqE63nMPh95ZSoVPThU3GbPjuQt9lUJYDJCnIUUPLyU%2F3Eiwx9PZ%2FHmg2k0amVTv%2FBRYOJ3ZH3bf1lfUdl8N7PVbxRZklURtkvCTm%2B1ZL2Y1H%2FanAiWVAAAA&config=H4sIAAAAAAAAA0WOvQ6DMAyE38Uzaztk7tCFh7CCQanyJ9tIRIh3b5JC2U723Xe3w0csmB1oU%2BKI%2Fk0%2BEwsY5ZUGyMhC3AxSouIGBrRkEssuKwwwkU2Mmu6EyvaTR9WMUebEoQE8LWjL6wpc%2Fj9hJMUJFcHM6KXHkRfSWknyqF0%2BJaHzO0Bw0c2lgW0KmUnkfmFc%2FOU8KiikaW2HvY%2FvwCccN%2BPMORlPY9%2F%2FBaxpS4QcAQAA

### Expected behavior

import * as swcHelpers from "@swc/helpers";
import regeneratorRuntime from "regenerator-runtime";
export var CompanyBgStore = function CompanyBgStore() {
    "use strict";
    var _this = this;
    swcHelpers.classCallCheck(this, CompanyBgStore);
    this.corpName = 123;
    this.getBusinessInfo = swcHelpers.asyncToGenerator(regeneratorRuntime.mark(function _callee() {
        var corpName, _args = arguments;
        return regeneratorRuntime.wrap(function _callee$(_ctx) {
            while(1)switch(_ctx.prev = _ctx.next){
                case 0:
                    corpName = _args.length > 0 && _args[0] !== void 0 ? _args[0] : _this.corpName;
                    console.log(corpName);
                case 2:
                case "end":
                    return _ctx.stop();
            }
        }, _callee, this);
    }));
};

### Actual behavior

import * as swcHelpers from "@swc/helpers";
import regeneratorRuntime from "regenerator-runtime";
export var CompanyBgStore = function CompanyBgStore() {
    "use strict";
    swcHelpers.classCallCheck(this, CompanyBgStore);
    this.corpName = 123;
    this.getBusinessInfo = swcHelpers.asyncToGenerator(regeneratorRuntime.mark(function _callee() {
        var corpName, _args = arguments;
        return regeneratorRuntime.wrap(function _callee$(_ctx) {
            while(1)switch(_ctx.prev = _ctx.next){
                case 0:
                    corpName = _args.length > 0 && _args[0] !== void 0 ? _args[0] : this.corpName;
                    console.log(corpName);
                case 2:
                case "end":
                    return _ctx.stop();
            }
        }, _callee, this);
    }));
};

### Version

1.2.161

### Additional context

babel:
image
swc:
image

### PR DESCRIPTION
**Pull request by magic-akari**
**Description:**

**BREAKING CHANGE:**

**Related issue (if exists):**
- fix #4208

### CODE REVIEW

File: crates/swc_ecma_transforms_compat/src/es2017/async_to_generator.rs [hunk 1]
```diff
@@ -309,6 +309,7 @@ impl Actual {
             Expr::Arrow(arrow_expr @ ArrowExpr { is_async: true, .. }) => {
                 let mut state = FnEnvHoister::default();
 
+                arrow_expr.params.visit_mut_with(&mut state);
```
Comment (Austaras) [inline crates/swc_ecma_transforms_compat/src/es2017/async_to_generator.rs:312]:
```rs
arrow_expr.visit_mut_with(&mut state);
```
seems to be enough

**Review by kdy1 — APPROVED** [review]
Thank you!

---

swc-bump:
 - swc_ecma_transforms_compat

**Review by kdy1 — APPROVED** [review]
