### PR TITLE
fix(es/preset-env): use `core-js-compat` and `@babel/compat-data` directly

### LINKED ISSUE #1604: Direct usage of `core-js-compat`
As I could see, copy of `core-js-compat` data used in `swc` version of `preset-env` is critically obsolete - 1.5 year. Each new version of `core-js-compat` contains updates engines support data,
```js
// .swcrc:
{
  "env": {
    "targets": {
      "safari": "14"
    },
    "mode": "entry",
    "coreJs": "3.11"
  }
}
// input.js:
import 'core-js/stable';
// output.js:
import   "core-js/modules/es.typed-array.int32-array";
import   "core-js/modules/es.typed-array.from";
import   "core-js/modules/web.immediate";
import   "core-js/modules/web.url-search-params";
import   "core-js/modules/es.typed-array.uint32-array";
import   "core-js/modules/web.url";
import   "core-js/modules/es.typed-array.float64-array";
import   "core-js/modules/es.typed-array.uint8-array";
import   "core-js/modules/es.typed-array.int16-array";
import   "core-js/modules/es.typed-array.int8-array";
import   "core-js/modules/es.string.replace";
import   "core-js/modules/es.typed-array.uint8-clamped-array";
import   "core-js/modules/es.typed-array.float32-array";
import   "core-js/modules/web.url.to-json";
import   "core-js/modules/es.typed-array.of";
import   "core-js/modules/es.typed-array.uint16-array";
// expected:
import   "core-js/modules/web.immediate";
```
`core-js-compat` contains information about new modules and entry points. Without this information impossible to use it correctly - new modules will not be injected even if they are required.
```js
// .swcrc:
{
  "env": {
    "targets": {
      "safari": "13"
    },
    "mode": "entry",
    "coreJs": "3.11"
  }
}
// input.js:
import 'core-js/stable/promise';
// output.js:
import   "core-js/modules/es.promise.finally";
import   "core-js/modules/web.dom-collections.iterator";
// expected:
import   "core-js/modules/es.aggregate-error";
import   "core-js/modules/es.promise.any";
import   "core-js/modules/es.promise.finally";
import   "core-js/modules/web.dom-collections.iterator";
```
Compat data should be updated even without `swc` updates for making possible to use actual `core-js` versions properly, so the only way to do it - usage of `core-js-compat` as a dependency.

### LINKED ISSUE #2607: swc not polyfill `string.replaceAll`
### Describe the bug

i use `string.replaceAll`, while `replaceAll` not be polyfilled

### Input code

```typescript
'1234'.replaceAll('1', '2');
```

### Config

```json
{
  "env": {
    "targets": {
      "chrome": "49",
      "ie": "11",
    },
    "mode": "entry",
    "coreJs": "3.7"
  }
}
```

### Playground link

https://swc-play.vercel.app/?version=1.2.106&code=H4sIAAAAAAAAA1WNsQrCMBRF93zF3ZLCo5i0TlLBX3BwCR0ez6BCbMszGfx746bTGe65HOvDMNpe05ZZ0ilnZ70lhO5gjKzLq4BV%2Be0xIcYdwc%2BEGAjDlyNhP8%2FtfK2Szo%2FbvTgDOBapz5q5rEqQqpqWcuFcU4fpiJ%2B1bwXh4v4c09If9Cye%2BpYAAAA%3D&config=H4sIAAAAAAAAA0WMSw7CMAxE7%2BJ1trDIHTiEFdwqKD%2FZrkQU9e44NIjdaObNG%2FCSAH5AQxbimaQXxTd4oJBRAsem4AyzasMkdDpQ5J10InKzLdUqBF75IAc5lrj1KQo1NyaR9bMJy57opzFPrs9jFgO0N%2Fr67nD%2BHesX5bHA6%2FkBJNbjgrUAAAA%3D

### Expected behavior

`string.replaceAll` should be polyfilled

### Version

1.2.10

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Austaras**
**Description:**
Instead of generate json, include json from node_modules

**BREAKING CHANGE:**
This would require js deps reside in node_modules, so pnp mode of package manager would not work

**Related issue (if exists):**
closes #1604

### CODE REVIEW

**Review by kdy1 — APPROVED** [review]
Thank you!

---


swc-bump:
 - preset_env_base --breaking

File: crates/swc_ecma_preset_env/src/corejs3/entry.rs [hunk 1]
```diff
@@ -12,33 +12,37 @@ use swc_ecma_visit::{Fold, FoldWith};
...
-            (
-                k,
-                v.into_iter()
-                    .map(|s: String| &*Box::leak(s.into_boxed_str()))
-                    .collect::<Vec<_>>(),
-            )
-        })
-        .collect()
+    serde_json::from_str::<AHashMap<String, Vec<String>>>(include_str!(
+        "../../../../node_modules/core-js-compat/entries.json"
```
Comment (Brooooooklyn) [inline crates/swc_ecma_preset_env/src/corejs3/entry.rs:16]: `error: couldn't read /Users/longyinan/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_preset_env-0.105.0/src/corejs3/../../../../node_modules/core-js-compat/modules-by-versions.json: No such file or directory (os error 2)`

Comment (kdy1) [reply crates/swc_ecma_preset_env/src/corejs3/entry.rs:16]: https://github.com/swc-project/swc/issues/3971 is the issue for this
